/*

 jQuery JavaScript Library v1.4.2
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Sat Feb 13 22:33:48 2010 -0500
*/
(function(){var S,V;(function(){function k(G){var H=y[G];if(H)return H;if(!u[G])throw new Error("Module "+G+" not found");for(var x=u[G],D=x.deps||(x.length?["require","exports","module"]:[]),I=y[G]={},O=0;O<D.length;O++){var q=D[O];switch(q){case "require":q=function(K){if(K.charAt(0)==="."){for(K=G.substring(0,G.lastIndexOf("/")+1)+K;T!==K;){var T=K;K=K.replace(/\/[^\/]*\/\.\.\//,"/")}K=K.replace(/\/\.\//g,"/")}return k(K)};break;case "exports":q=I;break;case "module":H=q={exports:I};break;default:q=
k(q)}D[O]=q}I=x.apply(this,D);if(H&&H.exports!=y[G])I=H.exports;if(I)return y[G]=I;return y[G]}var u={},y={};S=function(G,H){for(var x=[],D=0;D<G.length;D++)x.push(k(G[D]));H.apply(k,x)};V=S.def=function(G,H,x){if(typeof H=="function")u[G]=H;else(u[G]=x).deps=H}})();V("lingwo_dictionary/util/extendPrototype",[],function(){return function(k,u){for(var y in u)k.prototype[y]=u[y]}});V("lingwo_dictionary/util/declare",["lingwo_dictionary/util/extendPrototype"],function(k){return function(u){var y=u._constructor;
delete u._constructor;k(y,u);return y}});V("lingwo_dictionary/layout/Popup",["jquery","lingwo_dictionary/util/declare"],function(k,u){return u({_constructor:function(y){this.popup=y.node},shutdown:function(){},layout:function(y){y=k(y);var G=k(this.popup),H=G.width(),x=y.offset(),D=x.left+y.width()/2-H/2;y=x.top+y.height()+40;x=k(document).width();if(D+H>x)D=x-H;if(D<0)D=0;G.show().css({left:D,top:y})}})});V("lingwo_dictionary/util/clobber",[],function(){return function(k,u,y){old_fn=k[u];k[u]=function(){old_fn.apply(this,
arguments);y()}}});V("lingwo_dictionary/util/clone",[],function(){return function(k){var u={},y;for(y in k)u[y]=k[y];return u}});V("lingwo_dictionary/util/proxy",[],function(){return function(k,u){return function(){return k.apply(u,arguments)}}});S.def("lingwo_dictionary/annotation/Reader2",["jquery","lingwo_dictionary/layout/Popup","lingwo_dictionary/util/clobber","lingwo_dictionary/util/clone","lingwo_dictionary/util/proxy"],function(k,u,y,G,H){var x,D,I=/MSIE 6/i.test(navigator.userAgent),O={layout:"docked"};
D={popup:{setup:function(){x.bubbleNode.addClass("popup");this._layout=new u({node:x.bubbleNode})},shutdown:function(){x.bubbleNode.removeClass("popup");this._layout.shutdown()},show:function(){var q=x.bubbleNode;this._layout.layout(x.selectedNode);q.css("height","");if(I||q.height()>200)q.css({height:200})},hide:function(){x.bubbleNode.hide()}},docked:{_dock:null,_footer:null,_footerId:null,_footerMargin:null,_positionBubble:function(){x.bubbleNode.show();var q=x.bubbleNode,K=this._dock.offset(),
T=this._footer.offset().top;q.outerWidth();q.innerWidth();var aa=q.outerHeight()-q.innerHeight(),W=Math.max(K.top-k(window).scrollTop()+1,0);T=Math.min(T-k(window).scrollTop()-W-this._footerMargin+1,k(window).height()-W)-aa;q.css({left:K.left-k(window).scrollLeft(),top:W,height:T})},_drupalHack:false,setup:function(){x.bubbleNode.addClass("docked");this._dock=k("#lingwo-korpus-dock");this._footerId=this._dock.attr("data-footer-id");this._footerMargin=this._dock.attr("data-footer-margin");this._footer=
k("#"+this._footerId);var q=H(this._positionBubble,this);k(window).bind("scroll.lingwoReaderDocked",q);k(window).bind("resize.lingwoReaderDocked",q);if(!this._drupalHack){typeof window.Drupal!="undefined"&&Drupal.adminToolbar&&y(Drupal.adminToolbar,"setState",function(){if(x.layout===D.docked){x.bubbleNode.hide();setTimeout(q,500)}});this._drupalHack=true}x.setBubbleContent("<em>Click a work in the text to look it up in the dictionary.</em>");setTimeout(q,0)},shutdown:function(){x.bubbleNode.removeClass("docked");
this._dock=this._footerId=this._footerMargin=this._footer=null;k(window).unbind(".lingwoReaderDocked")},show:function(){},hide:function(){}}};return x={defaultLayouts:D,onLoad:function(){},config:null,bubbleNode:null,contentNode:null,selectedNode:null,shown:false,isSetup:false,layout:null,setup:function(q){if(typeof q=="undefined")q=G(O);this.config=q;if(this.config.layout=="docked"&&I)this.config.layout="popup";if(this.isSetup){this.layout.shutdown();this.layout=null;this.isSetup=false}if(!this.bubbleNode)this.bubbleNode=
k("<div></div>").attr("id","lingwo-korpus-entry-view-wrapper").appendTo(k("body")).hide();if(!this.contentNode)this.contentNode=k("<div></div>").attr("id","lingwo-korpus-entry-view").appendTo(this.bubbleNode);q=typeof this.config.layout=="string"?D[this.config.layout]:this.config.layout;q.setup();this.config.skipHoverEvents||this.setupHoverEvents();this.layout=q;this.isSetup=false},setupHoverEvents:function(){k(".anno, .anno-anchor").unbind("mouseenter mouseleave").bind("mouseenter",function(q){q=
k(q.target);q.addClass("hover");if(q=x._getAnnoText(q))q.addClass("hover")}).bind("mouseleave",function(q){q=k(q.target);q.removeClass("hover");if(q=x._getAnnoText(q))q.removeClass("hover")})},_getAnnoText:function(q){if(q.hasClass("anno-anchor"))if(q=q.attr("data-anno"))return k("#"+q);return null},setSelection:function(q){var K;if(this.selectedNode){this.selectedNode.removeClass("selected");if(K=this._getAnnoText(this.selectedNode))K.removeClass("selected");this.selectedNode=null}if(q){q=k(q);q.addClass("selected");
this.selectedNode=q;if(K=this._getAnnoText(this.selectedNode))K.addClass("selected")}},clearSelection:function(){this.setSelection(null)},isInsideBubble:function(q){for(;q=q.parentNode;)if(q.id=="lingwo-korpus-entry-view")return true;return false},showBubble:function(){this.layout.show();this.shown=true},hideBubble:function(){this.layout.hide();this.shown=false},setBubbleContent:function(q){this.contentNode.html(q)},setBubbleLoading:function(){this.setBubbleContent("Loading...")},isWordNode:function(q){return k(q).hasClass("anno")||
k(q).hasClass("anno-anchor")},handleClick:function(q){if(this.isWordNode(q)){if(this.isInsideBubble(q))this.onLoad(k(q));else{this.setSelection(q);this.onLoad(this.selectedNode);this.showBubble()}return false}this.clearSelection();this.hideBubble()}}});V("lingwo_dictionary/layout/isPositionFixedSupported",[],function(){function k(){var u=null;if(document.createElement){var y=document.createElement("div");if(y&&y.style){y.style.position="fixed";y.style.top="10px";var G=document.body;if(G&&G.appendChild&&
G.removeChild){G.appendChild(y);u=y.offsetTop===10;G.removeChild(y)}}}return u}return function(){var u=navigator.userAgent.toLowerCase();return k()&&!/iphone|ipod|android/.exec(u)}});V("lingwo_dictionary/layout/BottomDock",["jquery","lingwo_dictionary/util/declare","lingwo_dictionary/util/proxy","lingwo_dictionary/layout/isPositionFixedSupported"],function(k,u,y,G){var H=G();return u({_constructor:function(x){this.node=x.node;this.size=x.size;this.spacerNode=k("<div></div>").appendTo(k("body")).css("height",
this.size).get(0);k(this.node).css({position:H?"fixed":"absolute",overflow:"hidden"}).appendTo(k("body"));this._layoutProxy=y(this.layout,this);k(window).bind("resize",this._layoutProxy);H||k(window).bind("scroll",this._layoutProxy)},shutdown:function(){k(window).unbind("resize",this._layoutProxy);H||k(window).unbind("scroll",this._layoutProxy);k(this.node).remove();k(this.spacer).remove()},onlayout:function(){},layout:function(){var x=Math.min(k(window).width(),k(document).width()),D=k(window).height(),
I=k(document).height();D=D-this.size;var O=0;if(!H){D+=k(window).scrollTop();O+=k(window).scrollLeft()}if(D+this.size>I)D=I-this.size;k(this.spacerNode).css("height",this.size);k(this.node).css({top:D,left:O,width:x,height:this.size});this.onlayout(D,O,x,this.size)}})});V("bibliobird/Embed",["jquery","lingwo_dictionary/util/declare","lingwo_dictionary/annotation/Reader2","lingwo_dictionary/layout/BottomDock","lingwo_dictionary/layout/isPositionFixedSupported"],function(k,u,y,G,H){function x(w){var c=
aa[q.lang][w];return c?c:w}function D(w,c,M){var N;for(N in c)if(!M||typeof w[N]=="undefined")w[N]=c[N]}function I(w){var c=q.url.replace("<lang>",q.lang);if(w)return c+"/"+w;return c}function O(w){this.node=w;this.url=k(w).attr("data-url")||q.getPageUrl();this.teaser=k(w).attr("data-teaser")=="true";this.links=k('<div class="bibliobird-links"></div>').insertBefore(w);this.data={};this.lookupContent()}var q={},K={url:"http://<lang>.bibliobird.com",lang:"en",showLinks:true,oninit:function(){},onlogin:function(){},
onlogout:function(){},onlookup:function(){},pageUrlRemove:"#",getPageUrl:function(){var w=""+window.self.location.href;switch(q.pageUrlRemove){case "?":w=w.split("?")[0];case "#":w=w.split("#")[0]}return w}},T={en:"English",pl:"Polski"},aa={en:{}},W=H(),X;aa.pl={"Translate to":"T\u0142umacz na","Words I Am Learning":"M\u00f3j osobisty s\u0142owniczek",Hello:"Cze\u015b\u0107",Login:"Zaloguj si\u0119",or:"lub",register:"utw\u00f3rz konto","on BiblioBird":"w systemie BiblioBird","not me!":"to nie ja!"};
X=u({_constructor:function(){this.innerNode=k('<div id="bibliobird-dock" class="clear-block"></div>').get(0);this.node=k("<div></div>").css("zIndex","101").append(this.innerNode).get(0);this.userNode=k("<div></div>").css({"float":"left","padding-left":10}).get(0);this._rebuild();this._layout=new G({node:this.node,size:35});this._layout.layout()},_rebuild:function(){var w,c,M,N=this;this.innerNode.innerHTML="";c=k('<select id="bibliobird-language-switcher"></select>').css({"float":"left","margin-top":5,
"margin-left":5}).get(0);for(w in T){M=k("<option>"+T[w]+"</option>");M.attr("value",w);w==q.lang&&M.attr("selected","selected");k(c).append(M)}k(c).bind("change",function(){q.lang=k("option:selected",c).val();N._rebuild()});w=k('<a id="bibliobird-wial-button"></a>').css({display:"block","float":"left",background:"transparent url('http://en.bibliobird.com/sites/all/themes/lingwoorg_theme/images/join-btn-left.png') left no-repeat","padding-left":11,height:27,"margin-left":10,"margin-top":2,color:"white",
"font-size":"12px","font-weight":"bold","text-decoration":"none",cursor:"pointer"}).attr({href:I("wial"),target:"_blank"}).append(k("<span></span>").css({display:"block","float":"left",background:"transparent url('http://en.bibliobird.com/sites/all/themes/lingwoorg_theme/images/join-btn-right.png') right no-repeat","padding-right":14,height:27,cursor:"pointer"}).append(k("<span></span>").css({display:"block","float":"left",background:"transparent url('http://en.bibliobird.com/sites/all/themes/lingwoorg_theme/images/join-btn-middle.png') center repeat-x",
"padding-top":4,height:23,cursor:"pointer"}).text(x("Words I Am Learning"))));k(this.innerNode).css({height:"100%",background:"#e5e5f9","border-top":"1px solid black","font-size":"14pt"}).append(k("<div>BiblioBird</div>").css({"float":"left",background:"#07104C","font-weight":"bold",height:"100%",color:"white","font-size":"16pt",padding:"0 10px","border-right":"1px solid white"})).append(this.userNode).append(k("<div></div>").css({"float":"right","padding-right":"10px"}).append('<label for="bibliobird-language-switcher" style="float: left">'+
x("Translate to")+": </label>").append(c).append(w));this.rebuildLinks()},rebuildLinks:function(){var w=k(this.userNode);k("#bibliobird-wial-button",this.node)[q.username?"show":"hide"]();w.html("");if(q.username){w.append(x("Hello")+", "+q.username+"!  (");w.append(k("<a></a>").html(x("not me!")).attr("href",I("logout")).click(function(){q.logout();return false}));w.append(")")}else{w.append(x("Hello")+"!  ");w.append(k("<a></a>").html(x("Login")).attr("href",I("remote/login")+(q.localRelayUrl?"?relay="+
q.localRelayUrl:"")).click(function(c){q.openEmbedWindow(c.target.href);return false}));w.append(" "+x("or")+" ");w.append(k("<a></a>").html(x("register")).attr({href:I("user/register"),target:"_blank"}));w.append(" "+x("on BiblioBird")+".")}}});if(typeof window.BiblioBird!="undefined")q=window.BiblioBird;D(q,K,true);D(q,{initialized:false,contentAreas:[],embedWindow:null,embedIframe:null,embedWindowShown:false,username:null,isRemoteIframe:false,bottomDock:null,hasContent:false,start:function(){window.self!==
window.top&&window.self.location.hash&&this._readHashOptions();k(".bibliobird-content").each(function(){q.contentAreas.push(new O(this))})},_readHashOptions:function(){var w=(""+window.self.location.hash).split("&"),c={},M,N;for(M=0;M<w.length;M++){N=w[M].split("=");c[N[0]]=N[1]}if(c["#iam"]=="bibliobird")this.isRemoteIframe=true},initialize:function(w,c){function M(){var t=(k(window).width()-400)/2,U=(k(window).height()-200)/2;if(!W){U+=k(window).scrollTop();t+=k(window).scrollLeft()}N.css({top:U,
left:t})}this.username=w;if(!this.hasContent&&c){if(!this.isRemoteIframe)this.bottomDock=new X;this.hasContent=c}if(!this.initialized){var N=k('<div class="clear-block"><div class="bibliobird-embed-titlebar"><span class="bibliobird-embed-title">BiblioBird</span> <a href="#" class="bibliobird-embed-close">close</a></div></div>');c=k('<iframe height="100%" width="100%" frameBorder="0" id="bibliobirdEmbedIframe" name="bibliobirdEmbedIframe"></iframe>').appendTo(N);N.css({width:400,height:200,position:W?
"fixed":"absolute",border:"1px solid black",background:"white",display:"none",zIndex:101}).appendTo(k("body"));k(".bibliobird-embed-close",N).click(function(){q.hideEmbedWindow();return false});k(window).resize(M);W||k(window).scroll(M);setTimeout(M,0);y.setup({layout:"popup",skipHoverEvents:true});k("body").click(function(t){q.hideEmbedWindow();return y.handleClick(t.target)});D(this,{embedWindow:N,embedIframe:c,username:w,initialized:true});this.oninit();w&&this.onlogin()}},receiveMessage:function(w){if(w.indexOf("#login-successful")==
0){w=w.split(":");if(w[1])this.username=w[1];else alert("Login failed!  Problem with cookies.  Do you use IE6?  If so, try a different browser.");this.hideEmbedWindow();this.onlogin()}},openEmbedWindow:function(w){if(this.embedWindow!==null&&!this.embedWindowShown){this.embedIframe.attr("src",w);this.embedWindow.show();this.embedWindowShown=true}},hideEmbedWindow:function(){if(this.embedWindow!==null&&this.embedWindowShown){this.embedWindow.hide();this.embedWindowShown=false;this.refreshAll()}},logout:function(){var w=
this;k.ajax({url:I("remote/logout"),dataType:"jsonp",success:function(){w.username=null;w.refreshAll();w.onlogout()}})},refreshAll:function(){k.each(this.contentAreas,function(){this.refresh()});this.bottomDock&&this.bottomDock.rebuildLinks()}});y.onLoad=function(w){w=(w.attr("data-entry")||"").split("#");var c=w[0],M=w[1];y.setBubbleLoading();k.ajax({url:I("embed-reader/lookup_entry"),dataType:"jsonp",data:{hash:c,lang:q.lang},success:function(N){y.setBubbleContent(N.content);k(".node",y.contentNode).removeClass("clear-block").removeAttr("id");
k("ul.links.inline",y.contentNode).remove();M&&k(".lingwo-sense-id-"+M,y.contentNode).addClass("selected");k("a",y.contentNode).each(function(t,U){t=U.href;var ja;if(t){ja=window.self.location.protocol+"//"+window.self.location.host;U.href=t.replace(ja,I());U.target="_blank"}});q.onlookup()}})};D(O.prototype,{lookupContent:function(){var w=this;k.ajax({url:I("embed-reader/lookup_content"),dataType:"jsonp",data:{url:this.url},success:function(c){q.initialize(c.username,!!c.content);w.data=c;w.rebuildLinks();
if(c.content){w.node.innerHTML=c.content;y.setupHoverEvents()}}})},rebuildLinks:function(){if(q.showLinks){var w=this.links,c=this.data;w.html("");c.not_found&&w.append(k("<a></a>").html("Add to Bibliobird").attr({href:I("node/add/content?remote_url="+escape(this.url)),target:"_blank"}))}},refresh:function(){this.rebuildLinks()}});return window.BiblioBird=q});(function(k,u){function y(){if(!c.isReady){try{t.documentElement.doScroll("left")}catch(a){setTimeout(y,1);return}c.ready()}}function G(a,b){b.src?
c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}function H(a,b,d,f,e,i){var j=a.length;if(typeof b==="object"){for(var p in b)H(a,p,b[p],f,e,d);return a}if(d!==u){f=!i&&f&&c.isFunction(d);for(p=0;p<j;p++)e(a[p],b,f?d.call(a[p],p,e(a[p],b)):d,i);return a}return j?e(a[0],b):u}function x(){return(new Date).getTime()}function D(){return false}function I(){return true}function O(a,b,d){d[0].type=a;return c.event.handle.apply(b,
d)}function q(a){var b,d=[],f=[],e=arguments,i,j,p,l,o,v;j=c.data(this,"events");if(!(a.liveFired===this||!j||!j.live||a.button&&a.type==="click")){a.liveFired=this;var A=j.live.slice(0);for(l=0;l<A.length;l++){j=A[l];j.origType.replace(fa,"")===a.type?f.push(j.selector):A.splice(l--,1)}i=c(a.target).closest(f,a.currentTarget);o=0;for(v=i.length;o<v;o++)for(l=0;l<A.length;l++){j=A[l];if(i[o].selector===j.selector){p=i[o].elem;f=null;if(j.preType==="mouseenter"||j.preType==="mouseleave")f=c(a.relatedTarget).closest(j.selector)[0];
if(!f||f!==p)d.push({elem:p,handleObj:j})}}o=0;for(v=d.length;o<v;o++){i=d[o];a.currentTarget=i.elem;a.data=i.handleObj.data;a.handleObj=i.handleObj;if(i.handleObj.origHandler.apply(i.elem,e)===false){b=false;break}}return b}}function K(a,b){return"live."+(a&&a!=="*"?a+".":"")+b.replace(/\./g,"`").replace(/ /g,"&")}function T(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function aa(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var f=c.data(a[d++]),e=c.data(this,
f);if(f=f&&f.events){delete e.handle;e.events={};for(var i in f)for(var j in f[i])c.event.add(this,i,f[i][j],f[i][j].data)}}})}function W(a,b,d){var f,e,i;b=b&&b[0]?b[0].ownerDocument||b[0]:t;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===t&&!Ba.test(a[0])&&(c.support.checkClone||!Ca.test(a[0]))){e=true;if(i=c.fragments[a[0]])if(i!==1)f=i}if(!f){f=b.createDocumentFragment();c.clean(a,b,f,d)}if(e)c.fragments[a[0]]=i?f:1;return{fragment:f,cacheable:e}}function X(a,b){var d={};c.each(Da.concat.apply([],
Da.slice(0,b)),function(){d[this]=a});return d}function w(a){return"scrollTo"in a&&a.document?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var c=function(a,b){return new c.fn.init(a,b)},M=k.jQuery,N=k.$,t=k.document,U,ja=/^[^<]*(<[\w\W]+>)[^>]*$|^#([\w-]+)$/,Ya=/^.[^:#\[\.,]*$/,Za=/\S/,$a=/^(\s|\u00A0)+|(\s|\u00A0)+$/g,ab=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,ga=navigator.userAgent,Ea=false,ba=[],na=!!(typeof S!=="undefined"&&S.def),ca,oa=Object.prototype.toString,pa=Object.prototype.hasOwnProperty,
qa=Array.prototype.push,ha=Array.prototype.slice,Fa=Array.prototype.indexOf;c.fn=c.prototype={init:function(a,b){var d,f;if(!a)return this;if(a.nodeType){this.context=this[0]=a;this.length=1;return this}if(a==="body"&&!b){this.context=t;this[0]=t.body;this.selector="body";this.length=1;return this}if(typeof a==="string")if((d=ja.exec(a))&&(d[1]||!b))if(d[1]){f=b?b.ownerDocument||b:t;if(a=ab.exec(a))if(c.isPlainObject(b)){a=[t.createElement(a[1])];c.fn.attr.call(a,b,true)}else a=[f.createElement(a[1])];
else{a=W([d[1]],[f]);a=(a.cacheable?a.fragment.cloneNode(true):a.fragment).childNodes}return c.merge(this,a)}else{if(b=t.getElementById(d[2])){if(b.id!==d[2])return U.find(a);this.length=1;this[0]=b}this.context=t;this.selector=a;return this}else if(!b&&/^\w+$/.test(a)){this.selector=a;this.context=t;a=t.getElementsByTagName(a);return c.merge(this,a)}else return!b||b.jquery?(b||U).find(a):c(b).find(a);else if(c.isFunction(a))return U.ready(a);if(a.selector!==u){this.selector=a.selector;this.context=
a.context}return c.makeArray(a,this)},selector:"",jquery:"1.4.2",length:0,size:function(){return this.length},toArray:function(){return ha.call(this,0)},get:function(a){return a==null?this.toArray():a<0?this.slice(a)[0]:this[a]},pushStack:function(a,b,d){var f=c();c.isArray(a)?qa.apply(f,a):c.merge(f,a);f.prevObject=this;f.context=this.context;if(b==="find")f.selector=this.selector+(this.selector?" ":"")+d;else if(b)f.selector=this.selector+"."+b+"("+d+")";return f},each:function(a,b){return c.each(this,
a,b)},ready:function(a){c.bindReady();if(c.isReady&&(!na||S.s.isDone))a.call(t,c);else{ba||(ba=[]);ba.push(a)}return this},eq:function(a){return a===-1?this.slice(a):this.slice(a,+a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(ha.apply(this,arguments),"slice",ha.call(arguments).join(","))},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},end:function(){return this.prevObject||c(null)},push:qa,
sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a=arguments[0]||{},b=1,d=arguments.length,f=false,e,i,j,p;if(typeof a==="boolean"){f=a;a=arguments[1]||{};b=2}if(typeof a!=="object"&&!c.isFunction(a))a={};if(d===b){a=this;--b}for(;b<d;b++)if((e=arguments[b])!=null)for(i in e){j=a[i];p=e[i];if(a!==p)if(f&&p&&(c.isPlainObject(p)||c.isArray(p))){j=j&&(c.isPlainObject(j)||c.isArray(j))?j:c.isArray(p)?[]:{};a[i]=c.extend(f,j,p)}else if(p!==u)a[i]=p}return a};
c.extend({noConflict:function(a){k.$=N;if(a)k.jQuery=M;return c},isReady:false,ready:function(){if(!c.isReady){if(!t.body)return setTimeout(c.ready,13);c.isReady=true;c.callReady()}},callReady:function(){if(c.isReady&&(!na||S.s.isDone)){if(ba){for(var a,b=0;a=ba[b++];)a.call(t,c);ba=null}c.fn.triggerHandler&&c(t).triggerHandler("ready")}},bindReady:function(){if(!Ea){Ea=true;if(t.readyState==="complete")return c.ready();if(t.addEventListener){t.addEventListener("DOMContentLoaded",ca,false);k.addEventListener("load",
c.ready,false)}else if(t.attachEvent){t.attachEvent("onreadystatechange",ca);k.attachEvent("onload",c.ready);var a=false;try{a=k.frameElement==null}catch(b){}t.documentElement.doScroll&&a&&y()}}},isFunction:function(a){return oa.call(a)==="[object Function]"},isArray:function(a){return oa.call(a)==="[object Array]"},isPlainObject:function(a){if(!a||oa.call(a)!=="[object Object]"||a.nodeType||a.setInterval)return false;if(a.constructor&&!pa.call(a,"constructor")&&!pa.call(a.constructor.prototype,"isPrototypeOf"))return false;
var b;for(b in a);return b===u||pa.call(a,b)},isEmptyObject:function(a){for(var b in a)return false;return true},error:function(a){throw a;},parseJSON:function(a){if(typeof a!=="string"||!a)return null;a=c.trim(a);if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return k.JSON&&k.JSON.parse?k.JSON.parse(a):(new Function("return "+a))();else c.error("Invalid JSON: "+
a)},noop:function(){},globalEval:function(a){if(a&&Za.test(a)){var b=t.getElementsByTagName("head")[0]||t.documentElement,d=t.createElement("script");d.type="text/javascript";if(c.support.scriptEval)d.appendChild(t.createTextNode(a));else d.text=a;b.insertBefore(d,b.firstChild);b.removeChild(d)}},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===b.toUpperCase()},each:function(a,b,d){var f,e=0,i=a.length,j=i===u||c.isFunction(a);if(d)if(j)for(f in a){if(b.apply(a[f],d)===false)break}else for(;e<
i;){if(b.apply(a[e++],d)===false)break}else if(j)for(f in a){if(b.call(a[f],f,a[f])===false)break}else for(d=a[0];e<i&&b.call(d,e,d)!==false;d=a[++e]);return a},trim:function(a){return(a||"").replace($a,"")},makeArray:function(a,b){b=b||[];if(a!=null)a.length==null||typeof a==="string"||c.isFunction(a)||typeof a!=="function"&&a.setInterval?qa.call(b,a):c.merge(b,a);return b},inArray:function(a,b){if(b.indexOf)return b.indexOf(a);for(var d=0,f=b.length;d<f;d++)if(b[d]===a)return d;return-1},merge:function(a,
b){var d=a.length,f=0;if(typeof b.length==="number")for(var e=b.length;f<e;f++)a[d++]=b[f];else for(;b[f]!==u;)a[d++]=b[f++];a.length=d;return a},grep:function(a,b,d){for(var f=[],e=0,i=a.length;e<i;e++)!d!==!b(a[e],e)&&f.push(a[e]);return f},map:function(a,b,d){for(var f=[],e,i=0,j=a.length;i<j;i++){e=b(a[i],i,d);if(e!=null)f[f.length]=e}return f.concat.apply([],f)},guid:1,proxy:function(a,b,d){if(arguments.length===2)if(typeof b==="string"){d=a;a=d[b];b=u}else if(b&&!c.isFunction(b)){d=b;b=u}if(!b&&
a)b=function(){return a.apply(d||this,arguments)};if(a)b.guid=a.guid=a.guid||b.guid||c.guid++;return b},uaMatch:function(a){a=a.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||!/compatible/.test(a)&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},browser:{}});ga=c.uaMatch(ga);if(ga.browser){c.browser[ga.browser]=true;c.browser.version=ga.version}if(c.browser.webkit)c.browser.safari=true;
if(Fa)c.inArray=function(a,b){return Fa.call(b,a)};U=c(t);if(t.addEventListener)ca=function(){t.removeEventListener("DOMContentLoaded",ca,false);c.ready()};else if(t.attachEvent)ca=function(){if(t.readyState==="complete"){t.detachEvent("onreadystatechange",ca);c.ready()}};(function(){c.support={};var a=t.documentElement,b=t.createElement("script"),d=t.createElement("div"),f="script"+x();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";
var e=d.getElementsByTagName("*"),i=d.getElementsByTagName("a")[0];if(!(!e||!e.length||!i)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(i.getAttribute("style")),hrefNormalized:i.getAttribute("href")==="/a",opacity:/^0.55$/.test(i.style.opacity),cssFloat:!!i.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:t.createElement("select").appendChild(t.createElement("option")).selected,
parentNode:d.removeChild(d.appendChild(t.createElement("div"))).parentNode===null,deleteExpando:true,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null};b.type="text/javascript";try{b.appendChild(t.createTextNode("window."+f+"=1;"))}catch(j){}a.insertBefore(b,a.firstChild);if(k[f]){c.support.scriptEval=true;delete k[f]}try{delete b.test}catch(p){c.support.deleteExpando=false}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function l(){c.support.noCloneEvent=
false;d.detachEvent("onclick",l)});d.cloneNode(true).fireEvent("onclick")}d=t.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";a=t.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var l=t.createElement("div");l.style.width=l.style.paddingLeft="1px";t.body.appendChild(l);c.boxModel=c.support.boxModel=l.offsetWidth===2;t.body.removeChild(l).style.display="none"});a=function(l){var o=
t.createElement("div");l="on"+l;var v=l in o;if(!v){o.setAttribute(l,"return;");v=typeof o[l]==="function"}return v};c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=e=i=null}})();c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",frameborder:"frameBorder"};var Y="jQuery"+x(),bb=0,Ga={};c.extend({cache:{},expando:Y,noData:{embed:true,object:true,
applet:true},data:function(a,b,d){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=a==k?Ga:a;var f=a[Y],e=c.cache;if(!f&&typeof b==="string"&&d===u)return null;f||(f=++bb);if(typeof b==="object"){a[Y]=f;e[f]=c.extend(true,{},b)}else if(!e[f]){a[Y]=f;e[f]={}}a=e[f];if(d!==u)a[b]=d;return typeof b==="string"?a[b]:a}},removeData:function(a,b){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=a==k?Ga:a;var d=a[Y],f=c.cache,e=f[d];if(b){if(e){delete e[b];c.isEmptyObject(e)&&c.removeData(a)}}else{if(c.support.deleteExpando)delete a[c.expando];
else a.removeAttribute&&a.removeAttribute(c.expando);delete f[d]}}}});c.fn.extend({data:function(a,b){if(typeof a==="undefined"&&this.length)return c.data(this[0]);else if(typeof a==="object")return this.each(function(){c.data(this,a)});var d=a.split(".");d[1]=d[1]?"."+d[1]:"";if(b===u){var f=this.triggerHandler("getData"+d[1]+"!",[d[0]]);if(f===u&&this.length)f=c.data(this[0],a);return f===u&&d[1]?this.data(d[0]):f}else return this.trigger("setData"+d[1]+"!",[d[0],b]).each(function(){c.data(this,
a,b)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var f=c.data(a,b);if(!d)return f||[];if(!f||c.isArray(d))f=c.data(a,b,c.makeArray(d));else f.push(d);return f}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),f=d.shift();if(f==="inprogress")f=d.shift();if(f){b==="fx"&&d.unshift("inprogress");f.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===
u)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||"fx",[])}});var Ha=/[\n\t]/g,ra=/\s+/,cb=/\r/g,db=/href|src|style/,eb=/(button|input)/i,fb=/(button|input|object|select|textarea)/i,
gb=/^(a|area)$/i,Ia=/radio|checkbox/;c.fn.extend({attr:function(a,b){return H(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(o){var v=c(this);v.addClass(a.call(this,o,v.attr("class")))});if(a&&typeof a==="string")for(var b=(a||"").split(ra),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===1)if(e.className){for(var i=" "+e.className+" ",
j=e.className,p=0,l=b.length;p<l;p++)if(i.indexOf(" "+b[p]+" ")<0)j+=" "+b[p];e.className=c.trim(j)}else e.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(l){var o=c(this);o.removeClass(a.call(this,l,o.attr("class")))});if(a&&typeof a==="string"||a===u)for(var b=(a||"").split(ra),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===1&&e.className)if(a){for(var i=(" "+e.className+" ").replace(Ha," "),j=0,p=b.length;j<p;j++)i=i.replace(" "+b[j]+" ",
" ");e.className=c.trim(i)}else e.className=""}return this},toggleClass:function(a,b){var d=typeof a,f=typeof b==="boolean";if(c.isFunction(a))return this.each(function(e){var i=c(this);i.toggleClass(a.call(this,e,i.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var e,i=0,j=c(this),p=b,l=a.split(ra);e=l[i++];){p=f?p:!j.hasClass(e);j[p?"addClass":"removeClass"](e)}else if(d==="undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=
this.className||a===false?"":c.data(this,"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(Ha," ").indexOf(a)>-1)return true;return false},val:function(a){if(a===u){var b=this[0];if(b){if(c.nodeName(b,"option"))return(b.attributes.value||{}).specified?b.value:b.text;if(c.nodeName(b,"select")){var d=b.selectedIndex,f=[],e=b.options;b=b.type==="select-one";if(d<0)return null;var i=b?d:0;for(d=b?d+1:e.length;i<d;i++){var j=
e[i];if(j.selected){a=c(j).val();if(b)return a;f.push(a)}}return f}if(Ia.test(b.type)&&!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace(cb,"")}return u}var p=c.isFunction(a);return this.each(function(l){var o=c(this),v=a;if(this.nodeType===1){if(p)v=a.call(this,l,o.val());if(typeof v==="number")v+="";if(c.isArray(v)&&Ia.test(this.type))this.checked=c.inArray(o.val(),v)>=0;else if(c.nodeName(this,"select")){var A=c.makeArray(v);c("option",this).each(function(){this.selected=
c.inArray(c(this).val(),A)>=0});if(!A.length)this.selectedIndex=-1}else this.value=v}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,f){if(!a||a.nodeType===3||a.nodeType===8)return u;if(f&&b in c.attrFn)return c(a)[b](d);f=a.nodeType!==1||!c.isXMLDoc(a);var e=d!==u;b=f&&c.props[b]||b;if(a.nodeType===1){var i=db.test(b);if(b in a&&f&&!i){if(e){b==="type"&&eb.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");
a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:fb.test(a.nodeName)||gb.test(a.nodeName)&&a.href?0:u;return a[b]}if(!c.support.style&&f&&b==="style"){if(e)a.style.cssText=""+d;return a.style.cssText}e&&a.setAttribute(b,""+d);a=!c.support.hrefNormalized&&f&&i?a.getAttribute(b,2):a.getAttribute(b);return a===null?u:a}return c.style(a,b,d)}});var fa=/\.(.*)$/,hb=function(a){return a.replace(/[^\w\s\.\|`]/g,
function(b){return"\\"+b})};c.event={add:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){if(a.setInterval&&a!==k&&!a.frameElement)a=k;var e,i;if(d.handler){e=d;d=e.handler}if(!d.guid)d.guid=c.guid++;if(i=c.data(a)){var j=i.events=i.events||{},p=i.handle;if(!p)i.handle=p=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(p.elem,arguments):u};p.elem=a;b=b.split(" ");for(var l,o=0,v;l=b[o++];){i=e?c.extend({},e):{handler:d,data:f};if(l.indexOf(".")>-1){v=l.split(".");
l=v.shift();i.namespace=v.slice(0).sort().join(".")}else{v=[];i.namespace=""}i.type=l;i.guid=d.guid;var A=j[l],F=c.event.special[l]||{};if(!A){A=j[l]=[];if(!F.setup||F.setup.call(a,f,v,p)===false)if(a.addEventListener)a.addEventListener(l,p,false);else a.attachEvent&&a.attachEvent("on"+l,p)}if(F.add){F.add.call(a,i);if(!i.handler.guid)i.handler.guid=d.guid}A.push(i);c.event.global[l]=true}a=null}}},global:{},remove:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){var e,i=0,j,p,l,o,v,A,F=c.data(a),
L=F&&F.events;if(F&&L){if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charAt(0)==="."){b=b||"";for(e in L)c.event.remove(a,e+b)}else{for(b=b.split(" ");e=b[i++];){o=e;j=e.indexOf(".")<0;p=[];if(!j){p=e.split(".");e=p.shift();l=new RegExp("(^|\\.)"+c.map(p.slice(0).sort(),hb).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(v=L[e])if(d){o=c.event.special[e]||{};for(J=f||0;J<v.length;J++){A=v[J];if(d.guid===A.guid){if(j||l.test(A.namespace)){f==null&&v.splice(J--,1);o.remove&&o.remove.call(a,A)}if(f!=
null)break}}if(v.length===0||f!=null&&v.length===1){if(!o.teardown||o.teardown.call(a,p)===false)Ja(a,e,F.handle);delete L[e]}}else for(var J=0;J<v.length;J++){A=v[J];if(j||l.test(A.namespace)){c.event.remove(a,o,A.handler,J);v.splice(J--,1)}}}if(c.isEmptyObject(L)){if(b=F.handle)b.elem=null;delete F.events;delete F.handle;c.isEmptyObject(F)&&c.removeData(a)}}}}},trigger:function(a,b,d,f){var e=a.type||a;if(!f){a=typeof a==="object"?a[Y]?a:c.extend(c.Event(e),a):c.Event(e);if(e.indexOf("!")>=0){a.type=
e=e.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[e]&&c.each(c.cache,function(){this.events&&this.events[e]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return u;a.result=u;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(f=c.data(d,"handle"))&&f.apply(d,b);f=d.parentNode||d.ownerDocument;try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+e]&&d["on"+e].apply(d,b)===false)a.result=false}catch(i){}if(!a.isPropagationStopped()&&
f)c.event.trigger(a,b,f,true);else if(!a.isDefaultPrevented()){f=a.target;var j,p=c.nodeName(f,"a")&&e==="click",l=c.event.special[e]||{};if((!l._default||l._default.call(d,a)===false)&&!p&&!(f&&f.nodeName&&c.noData[f.nodeName.toLowerCase()])){try{if(f[e]){if(j=f["on"+e])f["on"+e]=null;c.event.triggered=true;f[e]()}}catch(o){}if(j)f["on"+e]=j;c.event.triggered=false}}},handle:function(a){var b,d,f,e;a=arguments[0]=c.event.fix(a||k.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;
if(!b){d=a.type.split(".");a.type=d.shift();f=new RegExp("(^|\\.)"+d.slice(0).sort().join("\\.(?:.*\\.)?")+"(\\.|$)")}e=c.data(this,"events");d=e[a.type];if(e&&d){d=d.slice(0);e=0;for(var i=d.length;e<i;e++){var j=d[e];if(b||f.test(j.namespace)){a.handler=j.handler;a.data=j.data;a.handleObj=j;j=j.handler.apply(this,arguments);if(j!==u){a.result=j;if(j===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY originalTarget pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),
fix:function(a){if(a[Y])return a;var b=a;a=c.Event(b);for(var d=this.props.length,f;d;){f=this.props[--d];a[f]=b[f]}if(!a.target)a.target=a.srcElement||t;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=t.documentElement;d=t.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||
d&&d.scrollTop||0)-(b&&b.clientTop||d&&d.clientTop||0)}if(!a.which&&(a.charCode||a.charCode===0?a.charCode:a.keyCode))a.which=a.charCode||a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==u)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,a.origType,c.extend({},a,{handler:q}))},remove:function(a){var b=true,d=a.origType.replace(fa,"");c.each(c.data(this,
"events").live||[],function(){if(d===this.origType.replace(fa,""))return b=false});b&&c.event.remove(this,a.origType,q)}},beforeunload:{setup:function(a,b,d){if(this.setInterval)this.onbeforeunload=d;return false},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};var Ja=t.removeEventListener?function(a,b,d){a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=
a;this.type=a.type}else this.type=a;this.timeStamp=x();this[Y]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=I;var a=this.originalEvent;if(a){a.preventDefault&&a.preventDefault();a.returnValue=false}},stopPropagation:function(){this.isPropagationStopped=I;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=I;this.stopPropagation()},isDefaultPrevented:D,isPropagationStopped:D,
isImmediatePropagationStopped:D};var Ka=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},La=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?La:Ka,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?La:Ka)}}});if(!c.support.submitBubbles)c.event.special.submit=
{setup:function(){if(this.nodeName.toLowerCase()!=="form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length)return O("submit",this,arguments)});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13)return O("submit",this,arguments)})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var sa=
/textarea|input|select/i,ta,Ma=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(f){return f.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},ua=function(a,b){var d=a.target,f,e;if(!(!sa.test(d.nodeName)||d.readOnly)){f=c.data(d,"_change_data");e=Ma(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",e);if(!(f===u||e===f))if(f!=null||
e){a.type="change";return c.event.trigger(a,b,d)}}};c.event.special.change={filters:{focusout:ua,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return ua.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return ua.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",Ma(a))}},setup:function(){if(this.type===
"file")return false;for(var a in ta)c.event.add(this,a+".specialChange",ta[a]);return sa.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return sa.test(this.nodeName)}};ta=c.event.special.change.filters}t.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(f){f=c.event.fix(f);f.type=b;return c.event.handle.call(this,f)}c.event.special[b]={setup:function(){this.addEventListener(a,d,true)},teardown:function(){this.removeEventListener(a,
d,true)}}});c.each(["bind","one"],function(a,b){c.fn[b]=function(d,f,e){if(typeof d==="object"){for(var i in d)this[b](i,f,d[i],e);return this}if(c.isFunction(f)){e=f;f=u}var j=b==="one"?c.proxy(e,function(l){c(this).unbind(l,j);return e.apply(this,arguments)}):e;if(d==="unload"&&b!=="one")this.one(d,f,e);else{i=0;for(var p=this.length;i<p;i++)c.event.add(this[i],d,j,f)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,a[d]);else{d=
0;for(var f=this.length;d<f;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,f){return this.live(b,d,f,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<b.length;)c.proxy(a,
b[d++]);return this.click(c.proxy(a,function(f){var e=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,e+1);f.preventDefault();return b[e].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var Na={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,f,e,i){var j,p=0,l,o,v=i||this.selector,A=i?this:c(this.context);if(c.isFunction(f)){e=f;f=u}for(d=
(d||"").split(" ");(j=d[p++])!=null;){i=fa.exec(j);l="";if(i){l=i[0];j=j.replace(fa,"")}if(j==="hover")d.push("mouseenter"+l,"mouseleave"+l);else{o=j;if(j==="focus"||j==="blur"){d.push(Na[j]+l);j+=l}else j=(Na[j]||j)+l;b==="live"?A.each(function(){c.event.add(this,K(j,v),{data:f,selector:v,handler:e,origType:j,origHandler:e,preType:o})}):A.unbind(K(j,v),e)}}return this}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),
function(a,b){c.fn[b]=function(d){return d?this.bind(b,d):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});k.attachEvent&&!k.addEventListener&&k.attachEvent("onunload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});(function(){function a(g){for(var h="",m,n=0;g[n];n++){m=g[n];if(m.nodeType===3||m.nodeType===4)h+=m.nodeValue;else if(m.nodeType!==8)h+=a(m.childNodes)}return h}function b(g,h,m,n,s,r){s=0;for(var B=n.length;s<B;s++){var z=n[s];
if(z){z=z[g];for(var E=false;z;){if(z.sizcache===m){E=n[z.sizset];break}if(z.nodeType===1&&!r){z.sizcache=m;z.sizset=s}if(z.nodeName.toLowerCase()===h){E=z;break}z=z[g]}n[s]=E}}}function d(g,h,m,n,s,r){s=0;for(var B=n.length;s<B;s++){var z=n[s];if(z){z=z[g];for(var E=false;z;){if(z.sizcache===m){E=n[z.sizset];break}if(z.nodeType===1){if(!r){z.sizcache=m;z.sizset=s}if(typeof h!=="string"){if(z===h){E=true;break}}else if(l.filter(h,[z]).length>0){E=z;break}}z=z[g]}n[s]=E}}}var f=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^[\]]*\]|['"][^'"]*['"]|[^[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,
e=0,i=Object.prototype.toString,j=false,p=true;[0,0].sort(function(){p=false;return 0});var l=function(g,h,m,n){m=m||[];var s=h=h||t;if(h.nodeType!==1&&h.nodeType!==9)return[];if(!g||typeof g!=="string")return m;for(var r=[],B,z,E,ia,Z=true,da=C(h),$=g;(f.exec(""),B=f.exec($))!==null;){$=B[3];r.push(B[1]);if(B[2]){ia=B[3];break}}if(r.length>1&&v.exec(g))if(r.length===2&&o.relative[r[0]])z=va(r[0]+r[1],h);else for(z=o.relative[r[0]]?[h]:l(r.shift(),h);r.length;){g=r.shift();if(o.relative[g])g+=r.shift();
z=va(g,z)}else{if(!n&&r.length>1&&h.nodeType===9&&!da&&o.match.ID.test(r[0])&&!o.match.ID.test(r[r.length-1])){B=l.find(r.shift(),h,da);h=B.expr?l.filter(B.expr,B.set)[0]:B.set[0]}if(h){B=n?{expr:r.pop(),set:F(n)}:l.find(r.pop(),r.length===1&&(r[0]==="~"||r[0]==="+")&&h.parentNode?h.parentNode:h,da);z=B.expr?l.filter(B.expr,B.set):B.set;if(r.length>0)E=F(z);else Z=false;for(;r.length;){var P=r.pop();B=P;if(o.relative[P])B=r.pop();else P="";if(B==null)B=h;o.relative[P](E,B,da)}}else E=[]}E||(E=z);
E||l.error(P||g);if(i.call(E)==="[object Array]")if(Z)if(h&&h.nodeType===1)for(g=0;E[g]!=null;g++){if(E[g]&&(E[g]===true||E[g].nodeType===1&&Q(h,E[g])))m.push(z[g])}else for(g=0;E[g]!=null;g++)E[g]&&E[g].nodeType===1&&m.push(z[g]);else m.push.apply(m,E);else F(E,m);if(ia){l(ia,s,m,n);l.uniqueSort(m)}return m};l.uniqueSort=function(g){if(J){j=p;g.sort(J);if(j)for(var h=1;h<g.length;h++)g[h]===g[h-1]&&g.splice(h--,1)}return g};l.matches=function(g,h){return l(g,null,null,h)};l.find=function(g,h,m){var n,
s;if(!g)return[];for(var r=0,B=o.order.length;r<B;r++){var z=o.order[r];if(s=o.leftMatch[z].exec(g)){var E=s[1];s.splice(1,1);if(E.substr(E.length-1)!=="\\"){s[1]=(s[1]||"").replace(/\\/g,"");n=o.find[z](s,h,m);if(n!=null){g=g.replace(o.match[z],"");break}}}}n||(n=h.getElementsByTagName("*"));return{set:n,expr:g}};l.filter=function(g,h,m,n){for(var s=g,r=[],B=h,z,E,ia=h&&h[0]&&C(h[0]);g&&h.length;){for(var Z in o.filter)if((z=o.leftMatch[Z].exec(g))!=null&&z[2]){var da=o.filter[Z],$,P;P=z[1];E=false;
z.splice(1,1);if(P.substr(P.length-1)!=="\\"){if(B===r)r=[];if(o.preFilter[Z])if(z=o.preFilter[Z](z,B,m,r,n,ia)){if(z===true)continue}else E=$=true;if(z)for(var ka=0;(P=B[ka])!=null;ka++)if(P){$=da(P,z,ka,B);var Oa=n^!!$;if(m&&$!=null)if(Oa)E=true;else B[ka]=false;else if(Oa){r.push(P);E=true}}if($!==u){m||(B=r);g=g.replace(o.match[Z],"");if(!E)return[];break}}}if(g===s)if(E==null)l.error(g);else break;s=g}return B};l.error=function(g){throw"Syntax error, unrecognized expression: "+g;};var o=l.selectors=
{order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},
attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")}},relative:{"+":function(g,h){var m=typeof h==="string",n=m&&!/\W/.test(h);m=m&&!n;if(n)h=h.toLowerCase();n=0;for(var s=g.length,r;n<s;n++)if(r=g[n]){for(;(r=r.previousSibling)&&r.nodeType!==1;);g[n]=m||r&&r.nodeName.toLowerCase()===h?r||false:r===h}m&&l.filter(h,g,true)},">":function(g,h){var m=typeof h==="string";if(m&&!/\W/.test(h)){h=h.toLowerCase();for(var n=0,s=g.length;n<s;n++){var r=g[n];
if(r){m=r.parentNode;g[n]=m.nodeName.toLowerCase()===h?m:false}}}else{n=0;for(s=g.length;n<s;n++)if(r=g[n])g[n]=m?r.parentNode:r.parentNode===h;m&&l.filter(h,g,true)}},"":function(g,h,m){var n=e++,s=d;if(typeof h==="string"&&!/\W/.test(h)){var r=h=h.toLowerCase();s=b}s("parentNode",h,n,g,r,m)},"~":function(g,h,m){var n=e++,s=d;if(typeof h==="string"&&!/\W/.test(h)){var r=h=h.toLowerCase();s=b}s("previousSibling",h,n,g,r,m)}},find:{ID:function(g,h,m){if(typeof h.getElementById!=="undefined"&&!m)return(g=
h.getElementById(g[1]))?[g]:[]},NAME:function(g,h){if(typeof h.getElementsByName!=="undefined"){var m=[];h=h.getElementsByName(g[1]);for(var n=0,s=h.length;n<s;n++)h[n].getAttribute("name")===g[1]&&m.push(h[n]);return m.length===0?null:m}},TAG:function(g,h){return h.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,h,m,n,s,r){g=" "+g[1].replace(/\\/g,"")+" ";if(r)return g;r=0;for(var B;(B=h[r])!=null;r++)if(B)if(s^(B.className&&(" "+B.className+" ").replace(/[\t\n]/g," ").indexOf(g)>=0))m||
n.push(B);else if(m)h[r]=false;return false},ID:function(g){return g[1].replace(/\\/g,"")},TAG:function(g){return g[1].toLowerCase()},CHILD:function(g){if(g[1]==="nth"){var h=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&"0n+"+g[2]||g[2]);g[2]=h[1]+(h[2]||1)-0;g[3]=h[3]-0}g[0]=e++;return g},ATTR:function(g,h,m,n,s,r){h=g[1].replace(/\\/g,"");if(!r&&o.attrMap[h])g[1]=o.attrMap[h];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,h,m,n,s){if(g[1]===
"not")if((f.exec(g[3])||"").length>1||/^\w/.test(g[3]))g[3]=l(g[3],null,null,h);else{g=l.filter(g[3],h,m,true^s);m||n.push.apply(n,g);return false}else if(o.match.POS.test(g[0])||o.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},
empty:function(g){return!g.firstChild},has:function(g,h,m){return!!l(m[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===
g.type||g.nodeName.toLowerCase()==="button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)}},setFilters:{first:function(g,h){return h===0},last:function(g,h,m,n){return h===n.length-1},even:function(g,h){return h%2===0},odd:function(g,h){return h%2===1},lt:function(g,h,m){return h<m[3]-0},gt:function(g,h,m){return h>m[3]-0},nth:function(g,h,m){return m[3]-0===h},eq:function(g,h,m){return m[3]-0===h}},filter:{PSEUDO:function(g,h,m,n){var s=h[1],r=o.filters[s];if(r)return r(g,
m,h,n);else if(s==="contains")return(g.textContent||g.innerText||a([g])||"").indexOf(h[3])>=0;else if(s==="not"){h=h[3];m=0;for(n=h.length;m<n;m++)if(h[m]===g)return false;return true}else l.error("Syntax error, unrecognized expression: "+s)},CHILD:function(g,h){var m=h[1],n=g;switch(m){case "only":case "first":for(;n=n.previousSibling;)if(n.nodeType===1)return false;if(m==="first")return true;n=g;case "last":for(;n=n.nextSibling;)if(n.nodeType===1)return false;return true;case "nth":m=h[2];var s=
h[3];if(m===1&&s===0)return true;h=h[0];var r=g.parentNode;if(r&&(r.sizcache!==h||!g.nodeIndex)){var B=0;for(n=r.firstChild;n;n=n.nextSibling)if(n.nodeType===1)n.nodeIndex=++B;r.sizcache=h}g=g.nodeIndex-s;return m===0?g===0:g%m===0&&g/m>=0}},ID:function(g,h){return g.nodeType===1&&g.getAttribute("id")===h},TAG:function(g,h){return h==="*"&&g.nodeType===1||g.nodeName.toLowerCase()===h},CLASS:function(g,h){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(h)>-1},ATTR:function(g,h){var m=
h[1];g=o.attrHandle[m]?o.attrHandle[m](g):g[m]!=null?g[m]:g.getAttribute(m);m=g+"";var n=h[2];h=h[4];return g==null?n==="!=":n==="="?m===h:n==="*="?m.indexOf(h)>=0:n==="~="?(" "+m+" ").indexOf(h)>=0:!h?m&&g!==false:n==="!="?m!==h:n==="^="?m.indexOf(h)===0:n==="$="?m.substr(m.length-h.length)===h:n==="|="?m===h||m.substr(0,h.length+1)===h+"-":false},POS:function(g,h,m,n){var s=o.setFilters[h[2]];if(s)return s(g,m,h,n)}}},v=o.match.POS;for(var A in o.match){o.match[A]=new RegExp(o.match[A].source+/(?![^\[]*\])(?![^\(]*\))/.source);
o.leftMatch[A]=new RegExp(/(^(?:.|\r|\n)*?)/.source+o.match[A].source.replace(/\\(\d+)/g,function(g,h){return"\\"+(h-0+1)}))}var F=function(g,h){g=Array.prototype.slice.call(g,0);if(h){h.push.apply(h,g);return h}return g};try{Array.prototype.slice.call(t.documentElement.childNodes,0)}catch(L){F=function(g,h){h=h||[];if(i.call(g)==="[object Array]")Array.prototype.push.apply(h,g);else if(typeof g.length==="number")for(var m=0,n=g.length;m<n;m++)h.push(g[m]);else for(m=0;g[m];m++)h.push(g[m]);return h}}var J;
if(t.documentElement.compareDocumentPosition)J=function(g,h){if(!g.compareDocumentPosition||!h.compareDocumentPosition){if(g==h)j=true;return g.compareDocumentPosition?-1:1}g=g.compareDocumentPosition(h)&4?-1:g===h?0:1;if(g===0)j=true;return g};else if("sourceIndex"in t.documentElement)J=function(g,h){if(!g.sourceIndex||!h.sourceIndex){if(g==h)j=true;return g.sourceIndex?-1:1}g=g.sourceIndex-h.sourceIndex;if(g===0)j=true;return g};else if(t.createRange)J=function(g,h){if(!g.ownerDocument||!h.ownerDocument){if(g==
h)j=true;return g.ownerDocument?-1:1}var m=g.ownerDocument.createRange(),n=h.ownerDocument.createRange();m.setStart(g,0);m.setEnd(g,0);n.setStart(h,0);n.setEnd(h,0);g=m.compareBoundaryPoints(Range.START_TO_END,n);if(g===0)j=true;return g};(function(){var g=t.createElement("div"),h="script"+(new Date).getTime();g.innerHTML="<a name='"+h+"'/>";var m=t.documentElement;m.insertBefore(g,m.firstChild);if(t.getElementById(h)){o.find.ID=function(n,s,r){if(typeof s.getElementById!=="undefined"&&!r)return(s=
s.getElementById(n[1]))?s.id===n[1]||typeof s.getAttributeNode!=="undefined"&&s.getAttributeNode("id").nodeValue===n[1]?[s]:u:[]};o.filter.ID=function(n,s){var r=typeof n.getAttributeNode!=="undefined"&&n.getAttributeNode("id");return n.nodeType===1&&r&&r.nodeValue===s}}m.removeChild(g);m=g=null})();(function(){var g=t.createElement("div");g.appendChild(t.createComment(""));if(g.getElementsByTagName("*").length>0)o.find.TAG=function(h,m){m=m.getElementsByTagName(h[1]);if(h[1]==="*"){h=[];for(var n=
0;m[n];n++)m[n].nodeType===1&&h.push(m[n]);m=h}return m};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!=="undefined"&&g.firstChild.getAttribute("href")!=="#")o.attrHandle.href=function(h){return h.getAttribute("href",2)};g=null})();t.querySelectorAll&&function(){var g=l,h=t.createElement("div");h.innerHTML="<p class='TEST'></p>";if(!(h.querySelectorAll&&h.querySelectorAll(".TEST").length===0)){l=function(n,s,r,B){s=s||t;if(!B&&s.nodeType===9&&!C(s))try{return F(s.querySelectorAll(n),
r)}catch(z){}return g(n,s,r,B)};for(var m in g)l[m]=g[m];h=null}}();(function(){var g=t.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){o.order.splice(1,0,"CLASS");o.find.CLASS=function(h,m,n){if(typeof m.getElementsByClassName!=="undefined"&&!n)return m.getElementsByClassName(h[1])};g=null}}})();var Q=t.compareDocumentPosition?
function(g,h){return!!(g.compareDocumentPosition(h)&16)}:function(g,h){return g!==h&&(g.contains?g.contains(h):true)},C=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false},va=function(g,h){var m=[],n="",s;for(h=h.nodeType?[h]:h;s=o.match.PSEUDO.exec(g);){n+=s[0];g=g.replace(o.match.PSEUDO,"")}g=o.relative[g]?g+"*":g;s=0;for(var r=h.length;s<r;s++)l(g,h[s],m);return l.filter(n,m)};c.find=l;c.expr=l.selectors;c.expr[":"]=c.expr.filters;c.unique=l.uniqueSort;c.text=
a;c.isXMLDoc=C;c.contains=Q})();var ib=/Until$/,jb=/^(?:parents|prevUntil|prevAll)/,kb=/,/;ha=Array.prototype.slice;var Pa=function(a,b,d){if(c.isFunction(b))return c.grep(a,function(e,i){return!!b.call(e,i,e)===d});else if(b.nodeType)return c.grep(a,function(e){return e===b===d});else if(typeof b==="string"){var f=c.grep(a,function(e){return e.nodeType===1});if(Ya.test(b))return c.filter(b,f,!d);else b=c.filter(b,f)}return c.grep(a,function(e){return c.inArray(e,b)>=0===d})};c.fn.extend({find:function(a){for(var b=
this.pushStack("","find",a),d=0,f=0,e=this.length;f<e;f++){d=b.length;c.find(a,this[f],b);if(f>0)for(var i=d;i<b.length;i++)for(var j=0;j<d;j++)if(b[j]===b[i]){b.splice(i--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,f=b.length;d<f;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(Pa(this,a,false),"not",a)},filter:function(a){return this.pushStack(Pa(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>
0},closest:function(a,b){if(c.isArray(a)){var d=[],f=this[0],e,i={},j;if(f&&a.length){e=0;for(var p=a.length;e<p;e++){j=a[e];i[j]||(i[j]=c.expr.match.POS.test(j)?c(j,b||this.context):j)}for(;f&&f.ownerDocument&&f!==b;){for(j in i){e=i[j];if(e.jquery?e.index(f)>-1:c(f).is(e)){d.push({selector:j,elem:f});delete i[j]}}f=f.parentNode}}return d}var l=c.expr.match.POS.test(a)?c(a,b||this.context):null;return this.map(function(o,v){for(;v&&v.ownerDocument&&v!==b;){if(l?l.index(v)>-1:c(v).is(a))return v;
v=v.parentNode}return null})},index:function(a){if(!a||typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(T(a[0])||T(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},
parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},
contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,f){var e=c.map(this,b,d);ib.test(a)||(f=d);if(f&&typeof f==="string")e=c.filter(f,e);e=this.length>1?c.unique(e):e;if((this.length>1||kb.test(f))&&jb.test(a))e=e.reverse();return this.pushStack(e,a,ha.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return c.find.matches(a,b)},dir:function(a,b,d){var f=[];for(a=
a[b];a&&a.nodeType!==9&&(d===u||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&f.push(a);a=a[b]}return f},nth:function(a,b,d){b=b||1;for(var f=0;a;a=a[d])if(a.nodeType===1&&++f===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Qa=/ jQuery\d+="(?:\d+|null)"/g,la=/^\s+/,Ra=/(<([\w:]+)[^>]*?)\/>/g,lb=/^(?:area|br|col|embed|hr|img|input|link|meta|param)$/i,Sa=/<([\w:]+)/,mb=/<tbody/i,nb=/<|&#?\w+;/,Ba=/<script|<object|<embed|<option|<style/i,
Ca=/checked\s*(?:[^=]|=\s*.checked.)/i,Ta=function(a,b,d){return lb.test(d)?a:b+"></"+d+">"},R={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};R.optgroup=R.option;R.tbody=R.tfoot=R.colgroup=R.caption=R.thead;R.th=R.td;if(!c.support.htmlSerialize)R._default=
[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==u)return this.empty().append((this[0]&&this[0].ownerDocument||t).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=
this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,
true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,
false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,f;(f=this[d])!=null;d++)if(!a||c.filter(a,[f]).length){if(!b&&f.nodeType===1){c.cleanData(f.getElementsByTagName("*"));c.cleanData([f])}f.parentNode&&f.parentNode.removeChild(f)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);
return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,f=this.ownerDocument;if(!d){d=f.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(Qa,"").replace(/=([^="'>\s]+\/)>/g,'="$1">').replace(la,"")],f)[0]}else return this.cloneNode(true)});if(a===true){aa(this,b);aa(this.find("*"),b.find("*"))}return b},html:function(a){if(a===u)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(Qa,
""):null;else if(typeof a==="string"&&!Ba.test(a)&&(c.support.leadingWhitespace||!la.test(a))&&!R[(Sa.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Ra,Ta);try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(f){this.empty().append(a)}}else c.isFunction(a)?this.each(function(e){var i=c(this),j=i.html();i.empty().append(function(){return a.call(this,e,j)})}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&
this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),f=d.html();d.replaceWith(a.call(this,b,f))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){function f(A){return c.nodeName(A,"table")?A.getElementsByTagName("tbody")[0]||
A.appendChild(A.ownerDocument.createElement("tbody")):A}var e,i,j=a[0],p=[],l;if(!c.support.checkClone&&arguments.length===3&&typeof j==="string"&&Ca.test(j))return this.each(function(){c(this).domManip(a,b,d,true)});if(c.isFunction(j))return this.each(function(A){var F=c(this);a[0]=j.call(this,A,b?F.html():u);F.domManip(a,b,d)});if(this[0]){e=j&&j.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:W(a,this,p);l=e.fragment;if(i=l.childNodes.length===
1?(l=l.firstChild):l.firstChild){b=b&&c.nodeName(i,"tr");for(var o=0,v=this.length;o<v;o++)d.call(b?f(this[o],i):this[o],o>0||e.cacheable||this.length>1?l.cloneNode(true):l)}p.length&&c.each(p,G)}return this}});c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var f=[];d=c(d);var e=this.length===1&&this[0].parentNode;if(e&&e.nodeType===11&&e.childNodes.length===1&&d.length===1){d[b](this[0]);
return this}else{e=0;for(var i=d.length;e<i;e++){var j=(e>0?this.clone(true):this).get();c.fn[b].apply(c(d[e]),j);f=f.concat(j)}return this.pushStack(f,a,d.selector)}}});c.extend({clean:function(a,b,d,f){b=b||t;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||t;for(var e=[],i=0,j;(j=a[i])!=null;i++){if(typeof j==="number")j+="";if(j){if(typeof j==="string"&&!nb.test(j))j=b.createTextNode(j);else if(typeof j==="string"){j=j.replace(Ra,Ta);var p=(Sa.exec(j)||["",
""])[1].toLowerCase(),l=R[p]||R._default,o=l[0],v=b.createElement("div");for(v.innerHTML=l[1]+j+l[2];o--;)v=v.lastChild;if(!c.support.tbody){o=mb.test(j);p=p==="table"&&!o?v.firstChild&&v.firstChild.childNodes:l[1]==="<table>"&&!o?v.childNodes:[];for(l=p.length-1;l>=0;--l)c.nodeName(p[l],"tbody")&&!p[l].childNodes.length&&p[l].parentNode.removeChild(p[l])}!c.support.leadingWhitespace&&la.test(j)&&v.insertBefore(b.createTextNode(la.exec(j)[0]),v.firstChild);j=v.childNodes}if(j.nodeType)e.push(j);else e=
c.merge(e,j)}}if(d)for(i=0;e[i];i++)if(f&&c.nodeName(e[i],"script")&&(!e[i].type||e[i].type.toLowerCase()==="text/javascript"))f.push(e[i].parentNode?e[i].parentNode.removeChild(e[i]):e[i]);else{e[i].nodeType===1&&e.splice.apply(e,[i+1,0].concat(c.makeArray(e[i].getElementsByTagName("script"))));d.appendChild(e[i])}return e},cleanData:function(a){for(var b,d,f=c.cache,e=c.event.special,i=c.support.deleteExpando,j=0,p;(p=a[j])!=null;j++)if(d=p[c.expando]){b=f[d];if(b.events)for(var l in b.events)e[l]?
c.event.remove(p,l):Ja(p,l,b.handle);if(i)delete p[c.expando];else p.removeAttribute&&p.removeAttribute(c.expando);delete f[d]}}});var ob=/z-?index|font-?weight|opacity|zoom|line-?height/i,Ua=/alpha\([^)]*\)/,Va=/opacity=([^)]*)/,wa=/float/i,xa=/-([a-z])/ig,pb=/([A-Z])/g,qb=/^-?\d+(?:px)?$/i,rb=/^-?\d/,sb={position:"absolute",visibility:"hidden",display:"block"},tb=["Left","Right"],ub=["Top","Bottom"],vb=t.defaultView&&t.defaultView.getComputedStyle,Wa=c.support.cssFloat?"cssFloat":"styleFloat",ya=
function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){return H(this,a,b,true,function(d,f,e){if(e===u)return c.curCSS(d,f);if(typeof e==="number"&&!ob.test(f))e+="px";c.style(d,f,e)})};c.extend({style:function(a,b,d){if(!a||a.nodeType===3||a.nodeType===8)return u;if((b==="width"||b==="height")&&parseFloat(d)<0)d=u;var f=a.style||a,e=d!==u;if(!c.support.opacity&&b==="opacity"){if(e){f.zoom=1;b=parseInt(d,10)+""==="NaN"?"":"alpha(opacity="+d*100+")";a=f.filter||c.curCSS(a,"filter")||"";f.filter=
Ua.test(a)?a.replace(Ua,b):b}return f.filter&&f.filter.indexOf("opacity=")>=0?parseFloat(Va.exec(f.filter)[1])/100+"":""}if(wa.test(b))b=Wa;b=b.replace(xa,ya);if(e)f[b]=d;return f[b]},css:function(a,b,d,f){if(b==="width"||b==="height"){var e,i=b==="width"?tb:ub;d=function(){e=b==="width"?a.offsetWidth:a.offsetHeight;f!=="border"&&c.each(i,function(){f||(e-=parseFloat(c.curCSS(a,"padding"+this,true))||0);if(f==="margin")e+=parseFloat(c.curCSS(a,"margin"+this,true))||0;else e-=parseFloat(c.curCSS(a,
"border"+this+"Width",true))||0})};a.offsetWidth!==0?d():c.swap(a,sb,d);return Math.max(0,Math.round(e))}return c.curCSS(a,b,d)},curCSS:function(a,b,d){var f,e=a.style;if(!c.support.opacity&&b==="opacity"&&a.currentStyle){f=Va.test(a.currentStyle.filter||"")?parseFloat(RegExp.$1)/100+"":"";return f===""?"1":f}if(wa.test(b))b=Wa;if(!d&&e&&e[b])f=e[b];else if(vb){if(wa.test(b))b="float";b=b.replace(pb,"-$1").toLowerCase();e=a.ownerDocument.defaultView;if(!e)return null;if(a=e.getComputedStyle(a,null))f=
a.getPropertyValue(b);if(b==="opacity"&&f==="")f="1"}else if(a.currentStyle){d=b.replace(xa,ya);f=a.currentStyle[b]||a.currentStyle[d];if(!qb.test(f)&&rb.test(f)){b=e.left;var i=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;e.left=d==="fontSize"?"1em":f||0;f=e.pixelLeft+"px";e.left=b;a.runtimeStyle.left=i}}return f},swap:function(a,b,d){var f={};for(var e in b){f[e]=a.style[e];a.style[e]=b[e]}d.call(a);for(e in b)a.style[e]=f[e]}});if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=
a.offsetWidth,d=a.offsetHeight,f=a.nodeName.toLowerCase()==="tr";return b===0&&d===0&&!f?true:b>0&&d>0&&!f?false:c.curCSS(a,"display")==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var wb=x(),xb=/<script(.|\s)*?\/script>/gi,yb=/select|textarea/i,zb=/color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week/i,ea=/=\?(&|$)/,za=/\?/,Ab=/(\?|&)_=.*?(&|$)/,Bb=/^(\w+:)?\/\/([^\/?#]+)/,Cb=/%20/g,Db=c.fn.load;c.fn.extend({load:function(a,b,
d){if(typeof a!=="string")return Db.call(this,a);else if(!this.length)return this;var f=a.indexOf(" ");if(f>=0){var e=a.slice(f,a.length);a=a.slice(0,f)}f="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);f="POST"}var i=this;c.ajax({url:a,type:f,dataType:"html",data:b,complete:function(j,p){if(p==="success"||p==="notmodified")i.html(e?c("<div />").append(j.responseText.replace(xb,"")).find(e):j.responseText);d&&i.each(d,[j.responseText,
p,j])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||yb.test(this.nodeName)||zb.test(this.type))}).map(function(a,b){a=c(this).val();return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),
function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:f})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b={}}return c.ajax({type:"POST",url:a,data:b,success:d,dataType:f})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,
global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:k.XMLHttpRequest&&(k.location.protocol!=="file:"||!k.ActiveXObject)?function(){return new k.XMLHttpRequest}:function(){try{return new k.ActiveXObject("Microsoft.XMLHTTP")}catch(a){}},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},lastModified:{},etag:{},ajax:function(a){function b(){e.success&&
e.success.call(l,p,j,C);e.global&&f("ajaxSuccess",[C,e])}function d(){e.complete&&e.complete.call(l,C,j);e.global&&f("ajaxComplete",[C,e]);e.global&&!--c.active&&c.event.trigger("ajaxStop")}function f(s,r){(e.context?c(e.context):c.event).trigger(s,r)}var e=c.extend(true,{},c.ajaxSettings,a),i,j,p,l=a&&a.context||e,o=e.type.toUpperCase();if(e.data&&e.processData&&typeof e.data!=="string")e.data=c.param(e.data,e.traditional);if(e.dataType==="jsonp"){if(o==="GET")ea.test(e.url)||(e.url+=(za.test(e.url)?
"&":"?")+(e.jsonp||"callback")+"=?");else if(!e.data||!ea.test(e.data))e.data=(e.data?e.data+"&":"")+(e.jsonp||"callback")+"=?";e.dataType="json"}if(e.dataType==="json"&&(e.data&&ea.test(e.data)||ea.test(e.url))){i=e.jsonpCallback||"jsonp"+wb++;if(e.data)e.data=(e.data+"").replace(ea,"="+i+"$1");e.url=e.url.replace(ea,"="+i+"$1");e.dataType="script";k[i]=k[i]||function(s){p=s;b();d();k[i]=u;try{delete k[i]}catch(r){}F&&F.removeChild(L)}}if(e.dataType==="script"&&e.cache===null)e.cache=false;if(e.cache===
false&&o==="GET"){var v=x(),A=e.url.replace(Ab,"$1_="+v+"$2");e.url=A+(A===e.url?(za.test(e.url)?"&":"?")+"_="+v:"")}if(e.data&&o==="GET")e.url+=(za.test(e.url)?"&":"?")+e.data;e.global&&!c.active++&&c.event.trigger("ajaxStart");v=(v=Bb.exec(e.url))&&(v[1]&&v[1]!==location.protocol||v[2]!==location.host);if(e.dataType==="script"&&o==="GET"&&v){var F=t.getElementsByTagName("head")[0]||t.documentElement,L=t.createElement("script");L.src=e.url;if(e.scriptCharset)L.charset=e.scriptCharset;if(!i){var J=
false;L.onload=L.onreadystatechange=function(){if(!J&&(!this.readyState||this.readyState==="loaded"||this.readyState==="complete")){J=true;b();d();L.onload=L.onreadystatechange=null;F&&L.parentNode&&F.removeChild(L)}}}F.insertBefore(L,F.firstChild);return u}var Q=false,C=e.xhr();if(C){e.username?C.open(o,e.url,e.async,e.username,e.password):C.open(o,e.url,e.async);try{if(e.data||a&&a.contentType)C.setRequestHeader("Content-Type",e.contentType);if(e.ifModified){c.lastModified[e.url]&&C.setRequestHeader("If-Modified-Since",
c.lastModified[e.url]);c.etag[e.url]&&C.setRequestHeader("If-None-Match",c.etag[e.url])}v||C.setRequestHeader("X-Requested-With","XMLHttpRequest");C.setRequestHeader("Accept",e.dataType&&e.accepts[e.dataType]?e.accepts[e.dataType]+", */*":e.accepts._default)}catch(va){}if(e.beforeSend&&e.beforeSend.call(l,C,e)===false){e.global&&!--c.active&&c.event.trigger("ajaxStop");C.abort();return false}e.global&&f("ajaxSend",[C,e]);var g=C.onreadystatechange=function(s){if(!C||C.readyState===0||s==="abort"){Q||
d();Q=true;if(C)C.onreadystatechange=c.noop}else if(!Q&&C&&(C.readyState===4||s==="timeout")){Q=true;C.onreadystatechange=c.noop;j=s==="timeout"?"timeout":!c.httpSuccess(C)?"error":e.ifModified&&c.httpNotModified(C,e.url)?"notmodified":"success";var r;if(j==="success")try{p=c.httpData(C,e.dataType,e)}catch(B){j="parsererror";r=B}if(j==="success"||j==="notmodified")i||b();else c.handleError(e,C,j,r);d();s==="timeout"&&C.abort();if(e.async)C=null}};try{var h=C.abort;C.abort=function(){C&&h.call(C);
g("abort")}}catch(m){}e.async&&e.timeout>0&&setTimeout(function(){C&&!Q&&g("timeout")},e.timeout);try{C.send(o==="POST"||o==="PUT"||o==="DELETE"?e.data:null)}catch(n){c.handleError(e,C,null,n);d()}e.async||g();return C}},handleError:function(a,b,d,f){if(a.error)a.error.call(a.context||a,b,d,f);if(a.global)(a.context?c(a.context):c.event).trigger("ajaxError",[b,a,f])},active:0,httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===
1223||a.status===0}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),f=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(f)c.etag[b]=f;return a.status===304||a.status===0},httpData:function(a,b,d){var f=a.getResponseHeader("content-type")||"",e=b==="xml"||!b&&f.indexOf("xml")>=0;a=e?a.responseXML:a.responseText;e&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b===
"json"||!b&&f.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&f.indexOf("javascript")>=0)c.globalEval(a);return a},param:function(a,b){function d(j,p){if(c.isArray(p))c.each(p,function(l,o){b||/\[\]$/.test(j)?f(j,o):d(j+"["+(typeof o==="object"||c.isArray(o)?l:"")+"]",o)});else!b&&p!=null&&typeof p==="object"?c.each(p,function(l,o){d(j+"["+l+"]",o)}):f(j,p)}function f(j,p){p=c.isFunction(p)?p():p;e[e.length]=encodeURIComponent(j)+"="+encodeURIComponent(p)}var e=[];if(b===u)b=c.ajaxSettings.traditional;
if(c.isArray(a)||a.jquery)c.each(a,function(){f(this.name,this.value)});else for(var i in a)d(i,a[i]);return e.join("&").replace(Cb,"+")}});var Aa={},Eb=/toggle|show|hide/,Fb=/^([+-]=)?([\d+-.]+)(.*)$/,ma,Da=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]];c.fn.extend({show:function(a,b){if(a||a===0)return this.animate(X("show",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");
this[a].style.display=d||"";if(c.css(this[a],"display")==="none"){d=this[a].nodeName;var f;if(Aa[d])f=Aa[d];else{var e=c("<"+d+" />").appendTo("body");f=e.css("display");if(f==="none")f="block";e.remove();Aa[d]=f}c.data(this[a],"olddisplay",f)}}a=0;for(b=this.length;a<b;a++)this[a].style.display=c.data(this[a],"olddisplay")||"";return this}},hide:function(a,b){if(a||a===0)return this.animate(X("hide",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");!d&&d!=="none"&&c.data(this[a],
"olddisplay",c.css(this[a],"display"))}a=0;for(b=this.length;a<b;a++)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b){var d=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,arguments);else a==null||d?this.each(function(){var f=d?a:c(this).is(":hidden");c(this)[f?"show":"hide"]()}):this.animate(X("toggle",3),a,b);return this},fadeTo:function(a,b,d){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d)},
animate:function(a,b,d,f){var e=c.speed(b,d,f);if(c.isEmptyObject(a))return this.each(e.complete);return this[e.queue===false?"each":"queue"](function(){var i=c.extend({},e),j,p=this.nodeType===1&&c(this).is(":hidden"),l=this;for(j in a){var o=j.replace(xa,ya);if(j!==o){a[o]=a[j];delete a[j];j=o}if(a[j]==="hide"&&p||a[j]==="show"&&!p)return i.complete.call(this);if((j==="height"||j==="width")&&this.style){i.display=c.css(this,"display");i.overflow=this.style.overflow}if(c.isArray(a[j])){(i.specialEasing=
i.specialEasing||{})[j]=a[j][1];a[j]=a[j][0]}}if(i.overflow!=null)this.style.overflow="hidden";i.curAnim=c.extend({},a);c.each(a,function(v,A){var F=new c.fx(l,i,v);if(Eb.test(A))F[A==="toggle"?p?"show":"hide":A](a);else{var L=Fb.exec(A),J=F.cur(true)||0;if(L){A=parseFloat(L[2]);var Q=L[3]||"px";if(Q!=="px"){l.style[v]=(A||1)+Q;J=(A||1)/F.cur(true)*J;l.style[v]=J+Q}if(L[1])A=(L[1]==="-="?-1:1)*A+J;F.custom(J,A,Q)}else F.custom(J,A,"")}});return true})},stop:function(a,b){var d=c.timers;a&&this.queue([]);
this.each(function(){for(var f=d.length-1;f>=0;f--)if(d[f].elem===this){b&&d[f](true);d.splice(f,1)}});b||this.dequeue();return this}});c.each({slideDown:X("show",1),slideUp:X("hide",1),slideToggle:X("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"}},function(a,b){c.fn[a]=function(d,f){return this.animate(b,d,f)}});c.extend({speed:function(a,b,d){var f=a&&typeof a==="object"?a:{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};f.duration=c.fx.off?0:typeof f.duration===
"number"?f.duration:c.fx.speeds[f.duration]||c.fx.speeds._default;f.old=f.complete;f.complete=function(){f.queue!==false&&c(this).dequeue();c.isFunction(f.old)&&f.old.call(this)};return f},easing:{linear:function(a,b,d,f){return d+f*a},swing:function(a,b,d,f){return(-Math.cos(a*Math.PI)/2+0.5)*f+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||
c.fx.step._default)(this);if((this.prop==="height"||this.prop==="width")&&this.elem.style)this.elem.style.display="block"},cur:function(a){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];return(a=parseFloat(c.css(this.elem,this.prop,a)))&&a>-10000?a:parseFloat(c.curCSS(this.elem,this.prop))||0},custom:function(a,b,d){function f(i){return e.step(i)}this.startTime=x();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;
this.pos=this.state=0;var e=this;f.elem=this.elem;if(f()&&c.timers.push(f)&&!ma)ma=setInterval(c.fx.tick,13)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=x(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=
this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=true;for(var f in this.options.curAnim)if(this.options.curAnim[f]!==true)d=false;if(d){if(this.options.display!=null){this.elem.style.overflow=this.options.overflow;a=c.data(this.elem,"olddisplay");this.elem.style.display=a?a:this.options.display;if(c.css(this.elem,"display")==="none")this.elem.style.display="block"}this.options.hide&&c(this.elem).hide();if(this.options.hide||this.options.show)for(var e in this.options.curAnim)c.style(this.elem,
e,this.options.orig[e]);this.options.complete.call(this.elem)}return false}else{e=b-this.startTime;this.state=e/this.options.duration;a=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||a](this.state,e,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||
c.fx.stop()},stop:function(){clearInterval(ma);ma=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};c.fn.offset="getBoundingClientRect"in
t.documentElement?function(a){var b=this[0];if(a)return this.each(function(e){c.offset.setOffset(this,a,e)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);var d=b.getBoundingClientRect(),f=b.ownerDocument;b=f.body;f=f.documentElement;return{top:d.top+(self.pageYOffset||c.support.boxModel&&f.scrollTop||b.scrollTop)-(f.clientTop||b.clientTop||0),left:d.left+(self.pageXOffset||c.support.boxModel&&f.scrollLeft||b.scrollLeft)-(f.clientLeft||b.clientLeft||
0)}}:function(a){var b=this[0];if(a)return this.each(function(v){c.offset.setOffset(this,a,v)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d=b.offsetParent,f=b,e=b.ownerDocument,i,j=e.documentElement,p=e.body;f=(e=e.defaultView)?e.getComputedStyle(b,null):b.currentStyle;for(var l=b.offsetTop,o=b.offsetLeft;(b=b.parentNode)&&b!==p&&b!==j;){if(c.offset.supportsFixedPosition&&f.position==="fixed")break;i=e?e.getComputedStyle(b,
null):b.currentStyle;l-=b.scrollTop;o-=b.scrollLeft;if(b===d){l+=b.offsetTop;o+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&/^t(able|d|h)$/i.test(b.nodeName))){l+=parseFloat(i.borderTopWidth)||0;o+=parseFloat(i.borderLeftWidth)||0}f=d;d=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&i.overflow!=="visible"){l+=parseFloat(i.borderTopWidth)||0;o+=parseFloat(i.borderLeftWidth)||0}f=i}if(f.position==="relative"||f.position==="static"){l+=p.offsetTop;
o+=p.offsetLeft}if(c.offset.supportsFixedPosition&&f.position==="fixed"){l+=Math.max(j.scrollTop,p.scrollTop);o+=Math.max(j.scrollLeft,p.scrollLeft)}return{top:l,left:o}};c.offset={initialize:function(){var a=t.body,b=t.createElement("div"),d,f,e,i=parseFloat(c.curCSS(a,"marginTop",true))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
a.insertBefore(b,a.firstChild);d=b.firstChild;f=d.firstChild;e=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=f.offsetTop!==5;this.doesAddBorderForTableAndCells=e.offsetTop===5;f.style.position="fixed";f.style.top="20px";this.supportsFixedPosition=f.offsetTop===20||f.offsetTop===15;f.style.position=f.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=f.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==i;a.removeChild(b);
c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=parseFloat(c.curCSS(a,"marginTop",true))||0;d+=parseFloat(c.curCSS(a,"marginLeft",true))||0}return{top:b,left:d}},setOffset:function(a,b,d){if(/static/.test(c.curCSS(a,"position")))a.style.position="relative";var f=c(a),e=f.offset(),i=parseInt(c.curCSS(a,"top",true),10)||0,j=parseInt(c.curCSS(a,"left",true),10)||0;if(c.isFunction(b))b=b.call(a,
d,e);d={top:b.top-e.top+i,left:b.left-e.left+j};"using"in b?b.using.call(a,d):f.css(d)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),f=/^body|html$/i.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.curCSS(a,"marginTop",true))||0;d.left-=parseFloat(c.curCSS(a,"marginLeft",true))||0;f.top+=parseFloat(c.curCSS(b[0],"borderTopWidth",true))||0;f.left+=parseFloat(c.curCSS(b[0],"borderLeftWidth",true))||0;return{top:d.top-
f.top,left:d.left-f.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||t.body;a&&!/^body|html$/i.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(f){var e=this[0],i;if(!e)return null;if(f!==u)return this.each(function(){if(i=w(this))i.scrollTo(!a?f:c(i).scrollLeft(),a?f:c(i).scrollTop());else this[d]=f});else return(i=w(e))?"pageXOffset"in i?i[a?"pageYOffset":"pageXOffset"]:
c.support.boxModel&&i.document.documentElement[d]||i.document.body[d]:e[d]}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?c.css(this[0],d,false,"padding"):null};c.fn["outer"+b]=function(f){return this[0]?c.css(this[0],d,false,f?"margin":"border"):null};c.fn[d]=function(f){var e=this[0];if(!e)return f==null?null:this;if(c.isFunction(f))return this.each(function(i){var j=c(this);j[d](f.call(this,i,j[d]()))});return"scrollTo"in e&&e.document?
e.document.compatMode==="CSS1Compat"&&e.document.documentElement["client"+b]||e.document.body["client"+b]:e.nodeType===9?Math.max(e.documentElement["client"+b],e.body["scroll"+b],e.documentElement["scroll"+b],e.body["offset"+b],e.documentElement["offset"+b]):f===u?c.css(e,d):this.css(d,typeof f==="string"?f:f+"px")}});if(na){var Xa=S.callReady;S.callReady=function(){Xa&&Xa();c.callReady()};S.def("jquery",function(){return c});S.def("jQuery",function(){return c})}})(window);S(["bibliobird/Embed"],
function(k){k.start()})})();
