<?php

include_once('bbcom_misc.features.inc');

// set the include_path to include our PEAR stuff
ini_set("include_path", 'sites/all/libraries/pear:' . (strtoupper(substr(PHP_OS, 0, 3)) ? ';' : ':') . ini_get("include_path"));

/*
 * Implementation of hook_menu().
 */
function bbcom_misc_menu() {
  return array(
    'admin/settings/bbcom' => array(
      'title' => 'BiblioBird.com',
      'description' => 'Settings for BiblioBird.com',
      'access arguments' => array('administer site configuration'),
      'page callback' => 'system_admin_menu_block_page',
      'file' => 'system.admin.inc',
      'file path' => drupal_get_path('module', 'system'),
    ),
    'myaccount' => array(
      'title' => 'My Account',
      'access callback' => 'user_is_logged_in',
      'access arguments' => array(),
      'page callback' => 'bbcom_misc_myaccount_page',
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
* Implementation of hook_theme_registry_alter().
*
* Make i18nmenu's page preprocess function run *before* everything else's,
* in case they want to alter the primary links (like context does!).
*/
function bbcom_misc_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['page'])) {
    if (count($theme_registry['page']['preprocess functions']) > 0) {
      // If i18nmenu's preprocess function is there already, remove it.
      if ($key = array_search('i18nmenu_preprocess_page', $theme_registry['page']['preprocess functions'])) {
        unset($theme_registry['page']['preprocess functions'][$key]);
      }
    }
    // Now tack it on at the beginning so it runs before everything else.
    $theme_registry['page']['preprocess functions'] = array_merge(array('i18nmenu_preprocess_page'), $theme_registry['page']['preprocess functions']);
  }
}

/*
 * Implementation of hook_misc_mail_alter().
 */
function bbcom_misc_mail_alter(&$message) {
  // Our SMTP server requires that From is an e-mail address that we control
  // so we always put the 'From' into 'Reply-To' instead and make the 'From'
  // always be the default.
  $default_from = variable_get('site_mail', ini_get('sendmail_from'));
  $message['headers']['Reply-To'] = $message['headers']['From'];
  $message['headers']['From'] = $message['from'] = $default_from;
}

// NOTE: Drupal's format_date() doesn't correctly deal with daylight savings time, nor does it
// translate the date parts.  This should be put in the theme as well, to handle all dates, particularly
// the node submitted ones.
function bbcom_misc_format_date($date, $type='medium', $format='') {
  return date_format_date(date_make_date($date, NULL, DATE_UNIX), $type, $format);
}

/*
 * Implementation of hook_link_alter().
 */
function bbcom_misc_link_alter(&$links, $node, $comment=NULL) {
  if (is_null($comment)) {
    // I hate this particular link...
    // TODO: Seems to contradict docs, this should be $links['comment']['comment_forbidden'] ...
    unset($links['comment_forbidden']);
  }
}

function bbcom_misc_myaccount_page() {
  global $user;

  $parts = explode('/', $_GET['q']);
  array_shift($parts);

  $url = 'user/' . $user->uid;
  if (count($parts) > 0) {
    $url .= '/' . implode('/', $parts);
  }

  return drupal_goto($url);
}

