<?php
/**
 * @file
 * Code pertaining to Facebook's extended permissions.
 * see http://wiki.developers.facebook.com/index.php/Extended_permissions
 */

function fb_permission_perm() {
  return array('edit own extended permissions');
}

/**
 * Helper function for menu item access check.
 */
function fb_permission_access_own($account, $perm) {
  if (fb_facebook_user())
    return ($GLOBALS['user']->uid == $account->uid && user_access($perm));
}

/**
 * Which permissions can we prompt for?
 *
 * @TODO - update this list and/or make it customizable.
 */
function fb_permission_map() {
  static $perms;
  if (!isset($perms)) {
    // http://developers.facebook.com/docs/authentication/permissions
    $perms = array(
      'email' => 'Allow %application to send you email',
      'offline_access' => 'Grant %application access to your Facebook account when you are not logged in.',
      'status_update' => 'Allow %application to set your status.',
      'photo_upload' => 'Allow %application to upload photos.',
      'user_photos' => 'Allow %application to view photos.',
      'create_event' => 'Allow %application to create events on your behalf.',
      'rsvp_event' => 'Allow %application to RSVP to events on your behalf',
      'sms' => 'Allow %application to send you SMS text messages.',
      'read_stream' => 'Allow %application to display your stream.',
      'publish_stream' => 'Allow %application to publish to your stream.',
    );
  }
  return $perms;
}

/**
 * Implements hook_fb_required_perms_alter().
 *
 * fb_connect.module can calls this to learn when perms to add to login-button.
 */
function fb_permission_fb_required_perms_alter(&$perms) {
  global $_fb, $_fb_app;
  $fb_app_data = fb_get_app_data($_fb_app);
  if (isset($fb_app_data['fb_permission'])) {
    $fb_permission_data = $fb_app_data['fb_permission'];

    foreach ($fb_permission_data['prompt'] as $key => $value) {
      if ($value) {
        $perms[$key] = $key;
      }
    }
  }
}

/**
 * Implementation of hook_user.
 */
function fb_permission_user($op, &$edit, &$account, $category = NULL) {
  global $user;
  if ($op == 'categories') {
    $items = array();
    // A tab for each application
    foreach (fb_get_all_apps() as $fb_app) {
      // TODO: limit only to apps which can be added to a user's account.
      $items[] = array(
        'name' => $fb_app->label,
        'title' => $fb_app->title,
        'access callback' => 'fb_permission_access_own',
        'access arguments' => array(1, 'edit own extended permissions'),
        'weight' => 2);
    }
    return $items;
  }
  elseif ($op == 'form') {
    // See if the category corresponds to a facebook app.
    $fb_app = fb_get_app(array('label' => $category));

    if ($fb_app) {
      $fb = fb_api_init($fb_app);
      $map = fb_permission_map(); // All known permissions.
      // Show only permissions we've configured for this app.
      $fb_app_data = fb_get_app_data($fb_app);
      $fb_permission_data = $fb_app_data['fb_permission'];
      if (is_array($fb_permission_data['map'])) {
        foreach ($fb_permission_data['map'] as $key => $value) {
          if (!$value)
            unset($map[$key]);
        }
      }

      /* Should not be necessary to wrap in serverfbml, as prompt-permission is documented as XFBML.
      $form = array(
        'perms' => array(
          '#prefix' => '<fb:serverfbml><script type="text/fbml><fb:fbml>',
          '#suffix' => '</fb:fbml></script></fb:serverfbml>',
        ),
      );
      */

      $t_args = array('%application' => $fb_app->title);
      $weight = 0;
      foreach ($map as $key => $text) {
        $has_perm = FALSE;
        try {
          $has_perm = fb_call_method($fb, 'users.hasAppPermission', array(
                                       'ext_perm' => $key,
                                       'uid' => fb_get_fbu($account->uid, $fb_app),
                                     ));
        } catch (Exception $e) {
          fb_log_exception($e, t('Call to users.hasAppPermission(%key) failed.', array('%key' => $key)));
        }
        if (!$has_perm) {
          if ('facebook has fixed fb:prompt-permission bugs' == FALSE) {
            // Ideally, fb:prompt-permission would work.  But it doesn't.
            $form['perms'][$key] = array(
              '#type' => 'markup',
              '#value' => '<fb:prompt-permission perms="' . $key . '">' . t($text, $t_args) . '</fb:prompt-permission>',
              '#weight' => $weight++,
              '#suffix' => "<br/>\n",
            );
          }
          else {
            // Send user to facebook's extended permission page.
            // This is weak.  Would be better to use javascript or fb:prompt-permission.
            $url = url($_GET['q'], array('absolute' => TRUE));
            $form['perms'][$key] = array(
              '#type' => 'markup',
              '#value' => l(t($text, $t_args), "http://www.facebook.com/authorize.php", array(
                              'html' => TRUE,
                              'query' => "api_key={$fb_app->apikey}&v=1.0&ext_perm={$key}&next={$url}&next_cancel={$url}",
                            )),
              '#prefix' => '<p>',
              '#suffix' => '</p>',
              '#weight' => $weight++,
            );
          }
        }
      }
      $form['description'] = array(
        '#type' => 'markup',
        '#value' => l(t('All settings for %application (and other Facebook Applications).', array('%application' => $fb_app->title)),
                      'http://www.facebook.com/editapps.php',
                      array('html' => TRUE)),
        '#prefix' => '<p>',
        '#suffix' => "</p>\n",
        '#weight' => $weight++,
      );
      // A value for hook_form_alter to find.
      $form['_fb_permission'] = array('#type' => 'value',
                                      '#value' => TRUE);
      return $form;
    }

  }

}

function fb_permission_form_alter(&$form, $state, $id) {
  //dpm(func_get_args(), 'fb_permission_form_alter');
  if ($id == 'user_profile_form' && isset($form['_fb_permission'])) {
    unset($form['submit']);
    unset($form['delete']);
  }

  // Add settings to fb_app form
  if (isset($form['fb_app_data'])) {
    $fb_app = $form['#fb_app'];
    $fb_app_data = fb_get_app_data($fb_app);
    $fb_permission_data = isset($fb_app_data['fb_permission']) ? $fb_app_data['fb_permission'] : NULL;
    $form['fb_app_data']['fb_permission'] = array(
      '#type' => 'fieldset',
      '#title' => t('Facebook extended permissions'),
      '#tree' => TRUE,
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );

    foreach (fb_permission_map() as $key => $desc) {
      $options[$key] = $key;
    }

    // defaults
    if (!isset($fb_permission_data['map'])) {
      $fb_permission_data['map'] = array();
    }

    $form['fb_app_data']['fb_permission']['map'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Extended permissions'),
      '#options' => $options,
      '#default_value' => $fb_permission_data['map'],
      '#description' => t('Which extended permissions does this application use?  Users will be able to grant these permissions on their user edit pages.'),
    );

    if (!isset($fb_permission_data['prompt'])) {
      $fb_permission_data['prompt'] = array();
    }
    $form['fb_app_data']['fb_permission']['prompt'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Prompt new users for permission'),
      '#options' => $options,
      '#default_value' => $fb_permission_data['prompt'],
      '#description' => t('Prompt users when they first authorize the application.  Select only the most important features.'),
    );

  }
}

/**
 * Implementation of hook_fb().  Here we customize the behavior of
 * Drupal for Facebook.
 *
 * Prompts user for extended permission when they have authorized the
 * application.
 *
 * Currently supporting only connect pages, not canvas pages.
 */
function fb_permission_fb($op, $data, &$return) {
  if ($op == FB_APP_OP_EVENT) {
    if ($data['event_type'] == FB_APP_EVENT_POST_AUTHORIZE) {
      // User has authorized the application.
      $fb_app = isset($data['fb_app']) ? $data['fb_app'] : NULL;
      $fb_app_data = fb_get_app_data($fb_app);
      $fb_permission_data = $fb_app_data['fb_permission'];

      if (is_array($fb_permission_data['prompt'])) {
        $perms = array();
        foreach ($fb_permission_data['prompt'] as $key => $value) {
          if ($value) {
            $perms[] = $key;
          }
        }
        if (count($perms)) {
          // http://wiki.developers.facebook.com/index.php/JS_API_M_FB.Connect.ShowPermissionDialog
          $js = "FB.Connect.showPermissionDialog('" . implode(',', $perms) . "')";
          fb_connect_init_js($js); // Add javascript to the next page.
        }
      }
    }
  }
}
