(function(){var l;(function(){function c(b){var a=k[b];if(a)return a;if(!f[b])throw new Error("Module "+b+" not found");for(var d=f[b],e=d.deps||(d.length?["require","exports","module"]:[]),g=k[b]={},j=0;j<e.length;j++){var h=e[j];switch(h){case "require":h=function(i){if(i.charAt(0)==="."){for(i=b.substring(0,b.lastIndexOf("/")+1)+i;m!==i;){var m=i;i=i.replace(/\/[^\/]*\/\.\.\//,"/")}i=i.replace(/\/\.\//g,"/")}return c(i)};break;case "exports":h=g;break;case "module":a=h={exports:g};break;default:h=
c(h)}e[j]=h}g=d.apply(this,e);if(a&&a.exports!=k[b])g=a.exports;if(g)return k[b]=g;return k[b]}var f={},k={};l=function(b,a){for(var d=[],e=0;e<b.length;e++)d.push(c(b[e]));a.apply(c,d)};l.def=function(b,a,d){if(typeof a=="function")f[b]=a;else(f[b]=d).deps=a}})();l.def("jquery",[],function(){return window.jQuery});l.def("jQuery",[],function(){return window.jQuery});l.def(["jquery","lingwo_dictionary/annotation/Reader2"],function(c,f){function k(a,d,e){var g;for(g in d)if(!e||typeof a[g]=="undefined")a[g]=
d[g]}var b={};if(typeof window.BiblioBird!="undefined")b=window.BiblioBird;k(b,{url:"http://www.bibliobird.com",lang:"en",showLinks:true,ga:true},true);k(b,{initialized:false,contentAreas:[],embedWindow:null,embedIframe:null,embedWindowShown:false,username:null,start:function(){var a=this;c(".bibliobird-content").each(function(){a.contentAreas.push(new ContentArea(this))})},initialize:function(a){function d(){var j=(c(window).width()-400)/2,h=(c(window).height()-200)/2;e.css({top:h,left:j})}if(!this.initialized){var e=
c('<div class="clear-block"><div class="bibliobird-embed-titlebar"><span class="bibliobird-embed-title">BiblioBird</span> <a href="#" class="bibliobird-embed-close">close</a></div></div>'),g=c('<iframe height="100%" width="100%" border="0" id="bibliobirdEmbedIframe" name="bibliobirdEmbedIframe"></iframe>').appendTo(e);e.css({width:400,height:200,position:"fixed",border:"1px solid black",background:"white",display:"none"}).appendTo(c("body"));c(".bibliobird-embed-close",e).click(function(){b.hideEmbedWindow();
return false});c(window).resize(d);setTimeout(d,0);f.setup({layout:"popup",skipHoverEvents:true});c("body").click(function(j){b.hideEmbedWindow();return f.handleClick(j.target)});k(this,{embedWindow:e,embedIframe:g,username:a,initialized:true})}},receiveMessage:function(a){if(a.indexOf("#login-successful")==0){a=a.split(":");if(a[1])this.username=a[1];this.hideEmbedWindow()}},openEmbedWindow:function(a){if(this.embedWindow!==null&&!this.embedWindowShown){this.embedIframe.attr("src",a);this.embedWindow.show();
this.embedWindowShown=true}},hideEmbedWindow:function(){if(this.embedWindow!==null&&this.embedWindowShown){this.embedWindow.hide();this.embedWindowShown=false;this.refreshAll()}},logout:function(){var a=this;c.ajax({url:b.url+"/remote/logout",dataType:"jsonp",success:function(){a.username=null;a.refreshAll()}})},refreshAll:function(){c.each(this.contentAreas,function(){this.refresh()})}});f.onLoad=function(a){a=(a.attr("data-entry")||"").split("#");var d=a[0],e=a[1];f.setBubbleLoading();c.ajax({url:b.url+
"/embed-reader/lookup_entry",dataType:"jsonp",data:{hash:d,lang:b.lang},success:function(g){f.setBubbleContent(g.content);b.ga&&typeof window._gaq!="undefined"&&_gaq.push(["_trackEvent","BiblioBird","Anonymous Lookup",b.lang]);c(".node",f.contentNode).removeClass("clear-block").removeAttr("id");c("ul.links.inline",f.contentNode).remove();e&&c(".lingwo-sense-id-"+e,f.contentNode).addClass("selected");c("a",f.contentNode).each(function(j,h){j=h.href;var i;if(j){i=window.location.protocol+"//"+window.location.host;
h.href=j.replace(i,b.url);h.target="_blank"}})}})};ContentArea=function(a){this.node=a;this.url=c(a).attr("data-url")||(""+window.location.href).split("#")[0];this.teaser=c(a).attr("data-teaser")=="true";this.links=c('<div class="bibliobird-links"></div>').insertBefore(a);this.data={};this.lookupContent()};k(ContentArea.prototype,{lookupContent:function(){var a=this;c.ajax({url:b.url+"/embed-reader/lookup_content",dataType:"jsonp",data:{url:this.url},success:function(d){b.initialize(d.username);a.data=
d;a.rebuildLinks();if(d.content){a.node.innerHTML=d.content;f.setupHoverEvents()}}})},rebuildLinks:function(){if(b.showLinks){var a=this.links,d=this.data;a.html("");if(b.username){a.append("Logged into BiblioBird as "+b.username+" ");a.append(c("<a></a>").html("Logout").attr("href",b.url+"/logout").click(function(){b.logout();return false}))}else{a.append("Not logged into BiblioBird ");a.append(c("<a></a>").html("Login").attr("href",b.url+"/remote/login"+(b.localRelayUrl?"?relay="+b.localRelayUrl:
"")).click(function(e){b.openEmbedWindow(e.target.href);return false}));a.append(" ");a.append(c("<a></a>").html("Join BiblioBird").attr({href:b.url+"/user/register",target:"_blank"}))}a.append(" ");d.not_found&&a.append(c("<a></a>").html("Add to Bibliobird").attr({href:b.url+"/node/add/content?remote_url="+escape(this.url),target:"_blank"}))}},refresh:function(){this.rebuildLinks()}});return window.BiblioBird=b});l(["lingwo_dictionary/annotation/Embed"],function(c){c.start()})})();
