(function(){var n,m;(function(){function c(h){var d=e[h];if(d)return d;if(!f[h])throw new Error("Module "+h+" not found");for(var g=f[h],b=g.deps||(g.length?["require","exports","module"]:[]),i=e[h]={},k=0;k<b.length;k++){var a=b[k];switch(a){case "require":a=function(j){if(j.charAt(0)==="."){for(j=h.substring(0,h.lastIndexOf("/")+1)+j;l!==j;){var l=j;j=j.replace(/\/[^\/]*\/\.\.\//,"/")}j=j.replace(/\/\.\//g,"/")}return c(j)};break;case "exports":a=i;break;case "module":d=a={exports:i};break;default:a=
c(a)}b[k]=a}i=g.apply(this,b);if(d&&d.exports!=e[h])i=d.exports;if(i)return e[h]=i;return e[h]}var f={},e={};n=function(h,d){for(var g=[],b=0;b<h.length;b++)g.push(c(h[b]));d.apply(c,g)};m=n.def=function(h,d,g){if(typeof d=="function")f[h]=d;else(f[h]=g).deps=d}})();m("lingwo_dictionary/util/extendPrototype",["require","exports","module"],function(){return function(c,f){for(var e in f)c.prototype[e]=f[e]}});m("lingwo_dictionary/util/declare",["lingwo_dictionary/util/extendPrototype"],function(c){return function(f){var e=
f._constructor;delete f._constructor;c(e,f);return e}});m("lingwo_dictionary/layout/Popup",["jquery","lingwo_dictionary/util/declare"],function(c,f){return f({_constructor:function(e){this.popup=e.node},shutdown:function(){},layout:function(e){e=c(e);var h=c(this.popup),d=h.width(),g=e.offset(),b=g.left+e.width()/2-d/2;e=g.top+e.height()+40;g=c(document).width();if(b+d>g)b=g-d;if(b<0)b=0;h.show().css({left:b,top:e})}})});m("lingwo_dictionary/util/clobber",["require","exports","module"],function(){return function(c,
f,e){old_fn=c[f];c[f]=function(){old_fn.apply(this,arguments);e()}}});m("lingwo_dictionary/util/clone",["require","exports","module"],function(){return function(c){var f={},e;for(e in c)f[e]=c[e];return f}});m("lingwo_dictionary/util/proxy",["require","exports","module"],function(){return function(c,f){return function(){return c.apply(f,arguments)}}});n.def("lingwo_dictionary/annotation/Reader2",["jquery","lingwo_dictionary/layout/Popup","lingwo_dictionary/util/clobber","lingwo_dictionary/util/clone",
"lingwo_dictionary/util/proxy"],function(c,f,e,h,d){var g,b,i=/MSIE 6/i.test(navigator.userAgent),k={layout:"docked"};b={popup:{setup:function(){g.bubbleNode.addClass("popup");this._layout=new f({node:g.bubbleNode})},shutdown:function(){g.bubbleNode.removeClass("popup");this._layout.shutdown()},show:function(){var a=g.bubbleNode;this._layout.layout(g.selectedNode);a.css("height","");if(i||a.height()>200)a.css({height:200})},hide:function(){g.bubbleNode.hide()}},docked:{_dock:null,_footer:null,_footerId:null,
_footerMargin:null,_positionBubble:function(){g.bubbleNode.show();var a=g.bubbleNode,j=this._dock.offset(),l=this._footer.offset().top;a.outerWidth();a.innerWidth();var o=a.outerHeight()-a.innerHeight(),p=Math.max(j.top-c(window).scrollTop()+1,0);l=Math.min(l-c(window).scrollTop()-p-this._footerMargin+1,c(window).height()-p)-o;a.css({left:j.left-c(window).scrollLeft(),top:p,height:l})},_drupalHack:false,setup:function(){g.bubbleNode.addClass("docked");this._dock=c("#lingwo-korpus-dock");this._footerId=
this._dock.attr("data-footer-id");this._footerMargin=this._dock.attr("data-footer-margin");this._footer=c("#"+this._footerId);var a=d(this._positionBubble,this);c(window).bind("scroll.lingwoReaderDocked",a);c(window).bind("resize.lingwoReaderDocked",a);if(!this._drupalHack){typeof window.Drupal!="undefined"&&Drupal.adminToolbar&&e(Drupal.adminToolbar,"setState",function(){if(g.layout===b.docked){g.bubbleNode.hide();setTimeout(a,500)}});this._drupalHack=true}g.setBubbleContent("<em>Click a work in the text to look it up in the dictionary.</em>");
setTimeout(a,0)},shutdown:function(){g.bubbleNode.removeClass("docked");this._dock=this._footerId=this._footerMargin=this._footer=null;c(window).unbind(".lingwoReaderDocked")},show:function(){},hide:function(){}}};return g={defaultLayouts:b,onLoad:function(){},config:null,bubbleNode:null,contentNode:null,selectedNode:null,shown:false,isSetup:false,layout:null,setup:function(a){if(typeof a=="undefined")a=h(k);this.config=a;if(this.config.layout=="docked"&&i)this.config.layout="popup";if(this.isSetup){this.layout.shutdown();
this.layout=null;this.isSetup=false}if(!this.bubbleNode)this.bubbleNode=c("<div></div>").attr("id","lingwo-korpus-entry-view-wrapper").appendTo(c("body")).hide();if(!this.contentNode)this.contentNode=c("<div></div>").attr("id","lingwo-korpus-entry-view").appendTo(this.bubbleNode);a=typeof this.config.layout=="string"?b[this.config.layout]:this.config.layout;a.setup();this.config.skipHoverEvents||this.setupHoverEvents();this.layout=a;this.isSetup=false},setupHoverEvents:function(){c(".anno, .anno-anchor").unbind("mouseenter mouseleave").bind("mouseenter",
function(a){a=c(a.target);a.addClass("hover");if(a=g._getAnnoText(a))a.addClass("hover")}).bind("mouseleave",function(a){a=c(a.target);a.removeClass("hover");if(a=g._getAnnoText(a))a.removeClass("hover")})},_getAnnoText:function(a){if(a.hasClass("anno-anchor"))if(a=a.attr("data-anno"))return c("#"+a);return null},setSelection:function(a){var j;if(this.selectedNode){this.selectedNode.removeClass("selected");if(j=this._getAnnoText(this.selectedNode))j.removeClass("selected");this.selectedNode=null}if(a){a=
c(a);a.addClass("selected");this.selectedNode=a;if(j=this._getAnnoText(this.selectedNode))j.addClass("selected")}},clearSelection:function(){this.setSelection(null)},isInsideBubble:function(a){for(;a=a.parentNode;)if(a.id=="lingwo-korpus-entry-view")return true;return false},showBubble:function(){this.layout.show();this.shown=true},hideBubble:function(){this.layout.hide();this.shown=false},setBubbleContent:function(a){this.contentNode.html(a)},setBubbleLoading:function(){this.setBubbleContent("Loading...")},
isWordNode:function(a){return c(a).hasClass("anno")||c(a).hasClass("anno-anchor")},handleClick:function(a){if(this.isWordNode(a)){if(this.isInsideBubble(a))this.onLoad(c(a));else{this.setSelection(a);this.onLoad(this.selectedNode);this.showBubble()}return false}this.clearSelection();this.hideBubble()}}});m("bibliobird/Embed",["jquery","lingwo_dictionary/annotation/Reader2"],function(c,f){function e(b,i,k){var a;for(a in i)if(!k||typeof b[a]=="undefined")b[a]=i[a]}function h(b){var i=d.url.replace("<lang>",
d.lang);if(b)return i+"/"+b;return i}var d={},g={url:"http://<lang>.bibliobird.com",lang:"en",showLinks:true,ga:true,pageUrlRemove:"#",getPageUrl:function(){var b=""+window.self.location.href;switch(d.pageUrlRemove){case "?":b=b.split("?")[0];case "#":b=b.split("#")[0]}return b}};if(typeof window.BiblioBird!="undefined")d=window.BiblioBird;e(d,g,true);e(d,{initialized:false,contentAreas:[],embedWindow:null,embedIframe:null,embedWindowShown:false,username:null,start:function(){var b=this;c(".bibliobird-content").each(function(){b.contentAreas.push(new ContentArea(this))})},
initialize:function(b){function i(){var j=(c(window).width()-400)/2,l=(c(window).height()-200)/2;k.css({top:l,left:j})}if(!this.initialized){var k=c('<div class="clear-block"><div class="bibliobird-embed-titlebar"><span class="bibliobird-embed-title">BiblioBird</span> <a href="#" class="bibliobird-embed-close">close</a></div></div>'),a=c('<iframe height="100%" width="100%" border="0" id="bibliobirdEmbedIframe" name="bibliobirdEmbedIframe"></iframe>').appendTo(k);k.css({width:400,height:200,position:"fixed",
border:"1px solid black",background:"white",display:"none"}).appendTo(c("body"));c(".bibliobird-embed-close",k).click(function(){d.hideEmbedWindow();return false});c(window).resize(i);setTimeout(i,0);f.setup({layout:"popup",skipHoverEvents:true});c("body").click(function(j){d.hideEmbedWindow();return f.handleClick(j.target)});e(this,{embedWindow:k,embedIframe:a,username:b,initialized:true})}},receiveMessage:function(b){if(b.indexOf("#login-successful")==0){b=b.split(":");if(b[1])this.username=b[1];
this.hideEmbedWindow()}},openEmbedWindow:function(b){if(this.embedWindow!==null&&!this.embedWindowShown){this.embedIframe.attr("src",b);this.embedWindow.show();this.embedWindowShown=true}},hideEmbedWindow:function(){if(this.embedWindow!==null&&this.embedWindowShown){this.embedWindow.hide();this.embedWindowShown=false;this.refreshAll()}},logout:function(){var b=this;c.ajax({url:h("remote/logout"),dataType:"jsonp",success:function(){b.username=null;b.refreshAll()}})},refreshAll:function(){c.each(this.contentAreas,
function(){this.refresh()})}});f.onLoad=function(b){b=(b.attr("data-entry")||"").split("#");var i=b[0],k=b[1];f.setBubbleLoading();c.ajax({url:h("embed-reader/lookup_entry"),dataType:"jsonp",data:{hash:i,lang:d.lang},success:function(a){f.setBubbleContent(a.content);d.ga&&typeof window._gaq!="undefined"&&_gaq.push(["_trackEvent","BiblioBird","Anonymous Lookup",d.lang]);c(".node",f.contentNode).removeClass("clear-block").removeAttr("id");c("ul.links.inline",f.contentNode).remove();k&&c(".lingwo-sense-id-"+
k,f.contentNode).addClass("selected");c("a",f.contentNode).each(function(j,l){j=l.href;var o;if(j){o=window.self.location.protocol+"//"+window.self.location.host;l.href=j.replace(o,h());l.target="_blank"}})}})};ContentArea=function(b){this.node=b;this.url=c(b).attr("data-url")||d.getPageUrl();this.teaser=c(b).attr("data-teaser")=="true";this.links=c('<div class="bibliobird-links"></div>').insertBefore(b);this.data={};this.lookupContent()};e(ContentArea.prototype,{lookupContent:function(){var b=this;
c.ajax({url:h("embed-reader/lookup_content"),dataType:"jsonp",data:{url:this.url},success:function(i){d.initialize(i.username);b.data=i;b.rebuildLinks();if(i.content){b.node.innerHTML=i.content;f.setupHoverEvents()}}})},rebuildLinks:function(){if(d.showLinks){var b=this.links,i=this.data;b.html("");if(d.username){b.append("Logged into BiblioBird as "+d.username+" ");b.append(c("<a></a>").html("Logout").attr("href",h("logout")).click(function(){d.logout();return false}))}else{b.append("Not logged into BiblioBird ");
b.append(c("<a></a>").html("Login").attr("href",h("remote/login")+(d.localRelayUrl?"?relay="+d.localRelayUrl:"")).click(function(k){d.openEmbedWindow(k.target.href);return false}));b.append(" ");b.append(c("<a></a>").html("Join BiblioBird").attr({href:h("user/register"),target:"_blank"}))}b.append(" ");i.not_found&&b.append(c("<a></a>").html("Add to Bibliobird").attr({href:h("node/add/content?remote_url="+escape(this.url)),target:"_blank"}))}},refresh:function(){this.rebuildLinks()}});return window.BiblioBird=
d});n.def("jquery",[],function(){return window.jQuery});n.def("jQuery",[],function(){return window.jQuery});n(["bibliobird/Embed"],function(c){c.start()})})();
