/*

 jQuery JavaScript Library v1.4.2
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Sat Feb 13 22:33:48 2010 -0500
*/
(function(){var Q,R;(function(){function p(G){var A=D[G];if(A)return A;if(!s[G])throw new Error("Module "+G+" not found");for(var C=s[G],w=C.deps||(C.length?["require","exports","module"]:[]),H=D[G]={},L=0;L<w.length;L++){var t=w[L];switch(t){case "require":t=function(I){if(I.charAt(0)==="."){for(I=G.substring(0,G.lastIndexOf("/")+1)+I;M!==I;){var M=I;I=I.replace(/\/[^\/]*\/\.\.\//,"/")}I=I.replace(/\/\.\//g,"/")}return p(I)};break;case "exports":t=H;break;case "module":A=t={exports:H};break;default:t=
p(t)}w[L]=t}H=C.apply(this,w);if(A&&A.exports!=D[G])H=A.exports;if(H)return D[G]=H;return D[G]}var s={},D={};Q=function(G,A){for(var C=[],w=0;w<G.length;w++)C.push(p(G[w]));A.apply(p,C)};R=Q.def=function(G,A,C){if(typeof A=="function")s[G]=A;else(s[G]=C).deps=A}})();R("lingwo_dictionary/util/extendPrototype",["require","exports","module"],function(){return function(p,s){for(var D in s)p.prototype[D]=s[D]}});R("lingwo_dictionary/util/declare",["lingwo_dictionary/util/extendPrototype"],function(p){return function(s){var D=
s._constructor;delete s._constructor;p(D,s);return D}});R("lingwo_dictionary/layout/Popup",["jquery","lingwo_dictionary/util/declare"],function(p,s){return s({_constructor:function(D){this.popup=D.node},shutdown:function(){},layout:function(D){D=p(D);var G=p(this.popup),A=G.width(),C=D.offset(),w=C.left+D.width()/2-A/2;D=C.top+D.height()+40;C=p(document).width();if(w+A>C)w=C-A;if(w<0)w=0;G.show().css({left:w,top:D})}})});R("lingwo_dictionary/util/clobber",["require","exports","module"],function(){return function(p,
s,D){old_fn=p[s];p[s]=function(){old_fn.apply(this,arguments);D()}}});R("lingwo_dictionary/util/clone",["require","exports","module"],function(){return function(p){var s={},D;for(D in p)s[D]=p[D];return s}});R("lingwo_dictionary/util/proxy",["require","exports","module"],function(){return function(p,s){return function(){return p.apply(s,arguments)}}});Q.def("lingwo_dictionary/annotation/Reader2",["jquery","lingwo_dictionary/layout/Popup","lingwo_dictionary/util/clobber","lingwo_dictionary/util/clone",
"lingwo_dictionary/util/proxy"],function(p,s,D,G,A){var C,w,H=/MSIE 6/i.test(navigator.userAgent),L={layout:"docked"};w={popup:{setup:function(){C.bubbleNode.addClass("popup");this._layout=new s({node:C.bubbleNode})},shutdown:function(){C.bubbleNode.removeClass("popup");this._layout.shutdown()},show:function(){var t=C.bubbleNode;this._layout.layout(C.selectedNode);t.css("height","");if(H||t.height()>200)t.css({height:200})},hide:function(){C.bubbleNode.hide()}},docked:{_dock:null,_footer:null,_footerId:null,
_footerMargin:null,_positionBubble:function(){C.bubbleNode.show();var t=C.bubbleNode,I=this._dock.offset(),M=this._footer.offset().top;t.outerWidth();t.innerWidth();var V=t.outerHeight()-t.innerHeight(),W=Math.max(I.top-p(window).scrollTop()+1,0);M=Math.min(M-p(window).scrollTop()-W-this._footerMargin+1,p(window).height()-W)-V;t.css({left:I.left-p(window).scrollLeft(),top:W,height:M})},_drupalHack:false,setup:function(){C.bubbleNode.addClass("docked");this._dock=p("#lingwo-korpus-dock");this._footerId=
this._dock.attr("data-footer-id");this._footerMargin=this._dock.attr("data-footer-margin");this._footer=p("#"+this._footerId);var t=A(this._positionBubble,this);p(window).bind("scroll.lingwoReaderDocked",t);p(window).bind("resize.lingwoReaderDocked",t);if(!this._drupalHack){typeof window.Drupal!="undefined"&&Drupal.adminToolbar&&D(Drupal.adminToolbar,"setState",function(){if(C.layout===w.docked){C.bubbleNode.hide();setTimeout(t,500)}});this._drupalHack=true}C.setBubbleContent("<em>Click a work in the text to look it up in the dictionary.</em>");
setTimeout(t,0)},shutdown:function(){C.bubbleNode.removeClass("docked");this._dock=this._footerId=this._footerMargin=this._footer=null;p(window).unbind(".lingwoReaderDocked")},show:function(){},hide:function(){}}};return C={defaultLayouts:w,onLoad:function(){},config:null,bubbleNode:null,contentNode:null,selectedNode:null,shown:false,isSetup:false,layout:null,setup:function(t){if(typeof t=="undefined")t=G(L);this.config=t;if(this.config.layout=="docked"&&H)this.config.layout="popup";if(this.isSetup){this.layout.shutdown();
this.layout=null;this.isSetup=false}if(!this.bubbleNode)this.bubbleNode=p("<div></div>").attr("id","lingwo-korpus-entry-view-wrapper").appendTo(p("body")).hide();if(!this.contentNode)this.contentNode=p("<div></div>").attr("id","lingwo-korpus-entry-view").appendTo(this.bubbleNode);t=typeof this.config.layout=="string"?w[this.config.layout]:this.config.layout;t.setup();this.config.skipHoverEvents||this.setupHoverEvents();this.layout=t;this.isSetup=false},setupHoverEvents:function(){p(".anno, .anno-anchor").unbind("mouseenter mouseleave").bind("mouseenter",
function(t){t=p(t.target);t.addClass("hover");if(t=C._getAnnoText(t))t.addClass("hover")}).bind("mouseleave",function(t){t=p(t.target);t.removeClass("hover");if(t=C._getAnnoText(t))t.removeClass("hover")})},_getAnnoText:function(t){if(t.hasClass("anno-anchor"))if(t=t.attr("data-anno"))return p("#"+t);return null},setSelection:function(t){var I;if(this.selectedNode){this.selectedNode.removeClass("selected");if(I=this._getAnnoText(this.selectedNode))I.removeClass("selected");this.selectedNode=null}if(t){t=
p(t);t.addClass("selected");this.selectedNode=t;if(I=this._getAnnoText(this.selectedNode))I.addClass("selected")}},clearSelection:function(){this.setSelection(null)},isInsideBubble:function(t){for(;t=t.parentNode;)if(t.id=="lingwo-korpus-entry-view")return true;return false},showBubble:function(){this.layout.show();this.shown=true},hideBubble:function(){this.layout.hide();this.shown=false},setBubbleContent:function(t){this.contentNode.html(t)},setBubbleLoading:function(){this.setBubbleContent("Loading...")},
isWordNode:function(t){return p(t).hasClass("anno")||p(t).hasClass("anno-anchor")},handleClick:function(t){if(this.isWordNode(t)){if(this.isInsideBubble(t))this.onLoad(p(t));else{this.setSelection(t);this.onLoad(this.selectedNode);this.showBubble()}return false}this.clearSelection();this.hideBubble()}}});R("bibliobird/Embed",["jquery","lingwo_dictionary/annotation/Reader2"],function(p,s){function D(w,H,L){var t;for(t in H)if(!L||typeof w[t]=="undefined")w[t]=H[t]}function G(w){var H=A.url.replace("<lang>",
A.lang);if(w)return H+"/"+w;return H}var A={},C={url:"http://<lang>.bibliobird.com",lang:"en",showLinks:true,ga:true,pageUrlRemove:"#",getPageUrl:function(){var w=""+window.self.location.href;switch(A.pageUrlRemove){case "?":w=w.split("?")[0];case "#":w=w.split("#")[0]}return w}};if(typeof window.BiblioBird!="undefined")A=window.BiblioBird;D(A,C,true);D(A,{initialized:false,contentAreas:[],embedWindow:null,embedIframe:null,embedWindowShown:false,username:null,start:function(){var w=this;p(".bibliobird-content").each(function(){w.contentAreas.push(new ContentArea(this))})},
initialize:function(w){function H(){var I=(p(window).width()-400)/2,M=(p(window).height()-200)/2;L.css({top:M,left:I})}if(!this.initialized){var L=p('<div class="clear-block"><div class="bibliobird-embed-titlebar"><span class="bibliobird-embed-title">BiblioBird</span> <a href="#" class="bibliobird-embed-close">close</a></div></div>'),t=p('<iframe height="100%" width="100%" border="0" id="bibliobirdEmbedIframe" name="bibliobirdEmbedIframe"></iframe>').appendTo(L);L.css({width:400,height:200,position:"fixed",
border:"1px solid black",background:"white",display:"none"}).appendTo(p("body"));p(".bibliobird-embed-close",L).click(function(){A.hideEmbedWindow();return false});p(window).resize(H);setTimeout(H,0);s.setup({layout:"popup",skipHoverEvents:true});p("body").click(function(I){A.hideEmbedWindow();return s.handleClick(I.target)});D(this,{embedWindow:L,embedIframe:t,username:w,initialized:true})}},receiveMessage:function(w){if(w.indexOf("#login-successful")==0){w=w.split(":");if(w[1])this.username=w[1];
this.hideEmbedWindow()}},openEmbedWindow:function(w){if(this.embedWindow!==null&&!this.embedWindowShown){this.embedIframe.attr("src",w);this.embedWindow.show();this.embedWindowShown=true}},hideEmbedWindow:function(){if(this.embedWindow!==null&&this.embedWindowShown){this.embedWindow.hide();this.embedWindowShown=false;this.refreshAll()}},logout:function(){var w=this;p.ajax({url:G("remote/logout"),dataType:"jsonp",success:function(){w.username=null;w.refreshAll()}})},refreshAll:function(){p.each(this.contentAreas,
function(){this.refresh()})}});s.onLoad=function(w){w=(w.attr("data-entry")||"").split("#");var H=w[0],L=w[1];s.setBubbleLoading();p.ajax({url:G("embed-reader/lookup_entry"),dataType:"jsonp",data:{hash:H,lang:A.lang},success:function(t){s.setBubbleContent(t.content);A.ga&&typeof window._gaq!="undefined"&&_gaq.push(["_trackEvent","BiblioBird","Anonymous Lookup",A.lang]);p(".node",s.contentNode).removeClass("clear-block").removeAttr("id");p("ul.links.inline",s.contentNode).remove();L&&p(".lingwo-sense-id-"+
L,s.contentNode).addClass("selected");p("a",s.contentNode).each(function(I,M){I=M.href;var V;if(I){V=window.self.location.protocol+"//"+window.self.location.host;M.href=I.replace(V,G());M.target="_blank"}})}})};ContentArea=function(w){this.node=w;this.url=p(w).attr("data-url")||A.getPageUrl();this.teaser=p(w).attr("data-teaser")=="true";this.links=p('<div class="bibliobird-links"></div>').insertBefore(w);this.data={};this.lookupContent()};D(ContentArea.prototype,{lookupContent:function(){var w=this;
p.ajax({url:G("embed-reader/lookup_content"),dataType:"jsonp",data:{url:this.url},success:function(H){A.initialize(H.username);w.data=H;w.rebuildLinks();if(H.content){w.node.innerHTML=H.content;s.setupHoverEvents()}}})},rebuildLinks:function(){if(A.showLinks){var w=this.links,H=this.data;w.html("");if(A.username){w.append("Logged into BiblioBird as "+A.username+" ");w.append(p("<a></a>").html("Logout").attr("href",G("logout")).click(function(){A.logout();return false}))}else{w.append("Not logged into BiblioBird ");
w.append(p("<a></a>").html("Login").attr("href",G("remote/login")+(A.localRelayUrl?"?relay="+A.localRelayUrl:"")).click(function(L){A.openEmbedWindow(L.target.href);return false}));w.append(" ");w.append(p("<a></a>").html("Join BiblioBird").attr({href:G("user/register"),target:"_blank"}))}w.append(" ");H.not_found&&w.append(p("<a></a>").html("Add to Bibliobird").attr({href:G("node/add/content?remote_url="+escape(this.url)),target:"_blank"}))}},refresh:function(){this.rebuildLinks()}});return window.BiblioBird=
A});(function(p,s){function D(){if(!c.isReady){try{v.documentElement.doScroll("left")}catch(a){setTimeout(D,1);return}c.ready()}}function G(a,b){b.src?c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}function A(a,b,d,f,e,i){var j=a.length;if(typeof b==="object"){for(var o in b)A(a,o,b[o],f,e,d);return a}if(d!==s){f=!i&&f&&c.isFunction(d);for(o=0;o<j;o++)e(a[o],b,f?d.call(a[o],o,e(a[o],b)):d,i);return a}return j?
e(a[0],b):s}function C(){return(new Date).getTime()}function w(){return false}function H(){return true}function L(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function t(a){var b,d=[],f=[],e=arguments,i,j,o,k,n,u;j=c.data(this,"events");if(!(a.liveFired===this||!j||!j.live||a.button&&a.type==="click")){a.liveFired=this;var y=j.live.slice(0);for(k=0;k<y.length;k++){j=y[k];j.origType.replace(ba,"")===a.type?f.push(j.selector):y.splice(k--,1)}i=c(a.target).closest(f,a.currentTarget);n=0;for(u=
i.length;n<u;n++)for(k=0;k<y.length;k++){j=y[k];if(i[n].selector===j.selector){o=i[n].elem;f=null;if(j.preType==="mouseenter"||j.preType==="mouseleave")f=c(a.relatedTarget).closest(j.selector)[0];if(!f||f!==o)d.push({elem:o,handleObj:j})}}n=0;for(u=d.length;n<u;n++){i=d[n];a.currentTarget=i.elem;a.data=i.handleObj.data;a.handleObj=i.handleObj;if(i.handleObj.origHandler.apply(i.elem,e)===false){b=false;break}}return b}}function I(a,b){return"live."+(a&&a!=="*"?a+".":"")+b.replace(/\./g,"`").replace(/ /g,
"&")}function M(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function V(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var f=c.data(a[d++]),e=c.data(this,f);if(f=f&&f.events){delete e.handle;e.events={};for(var i in f)for(var j in f[i])c.event.add(this,i,f[i][j],f[i][j].data)}}})}function W(a,b,d){var f,e,i;b=b&&b[0]?b[0].ownerDocument||b[0]:v;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===v&&!xa.test(a[0])&&(c.support.checkClone||!ya.test(a[0]))){e=
true;if(i=c.fragments[a[0]])if(i!==1)f=i}if(!f){f=b.createDocumentFragment();c.clean(a,b,f,d)}if(e)c.fragments[a[0]]=i?f:1;return{fragment:f,cacheable:e}}function X(a,b){var d={};c.each(za.concat.apply([],za.slice(0,b)),function(){d[this]=a});return d}function Aa(a){return"scrollTo"in a&&a.document?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var c=function(a,b){return new c.fn.init(a,b)},Va=p.jQuery,Wa=p.$,v=p.document,fa,Xa=/^[^<]*(<[\w\W]+>)[^>]*$|^#([\w-]+)$/,Ya=/^.[^:#\[\.,]*$/,Za=/\S/,
$a=/^(\s|\u00A0)+|(\s|\u00A0)+$/g,ab=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,ca=navigator.userAgent,Ba=false,Y=[],ja=!!(typeof Q!=="undefined"&&Q.def),Z,ka=Object.prototype.toString,la=Object.prototype.hasOwnProperty,ma=Array.prototype.push,da=Array.prototype.slice,Ca=Array.prototype.indexOf;c.fn=c.prototype={init:function(a,b){var d,f;if(!a)return this;if(a.nodeType){this.context=this[0]=a;this.length=1;return this}if(a==="body"&&!b){this.context=v;this[0]=v.body;this.selector="body";this.length=1;return this}if(typeof a===
"string")if((d=Xa.exec(a))&&(d[1]||!b))if(d[1]){f=b?b.ownerDocument||b:v;if(a=ab.exec(a))if(c.isPlainObject(b)){a=[v.createElement(a[1])];c.fn.attr.call(a,b,true)}else a=[f.createElement(a[1])];else{a=W([d[1]],[f]);a=(a.cacheable?a.fragment.cloneNode(true):a.fragment).childNodes}return c.merge(this,a)}else{if(b=v.getElementById(d[2])){if(b.id!==d[2])return fa.find(a);this.length=1;this[0]=b}this.context=v;this.selector=a;return this}else if(!b&&/^\w+$/.test(a)){this.selector=a;this.context=v;a=v.getElementsByTagName(a);
return c.merge(this,a)}else return!b||b.jquery?(b||fa).find(a):c(b).find(a);else if(c.isFunction(a))return fa.ready(a);if(a.selector!==s){this.selector=a.selector;this.context=a.context}return c.makeArray(a,this)},selector:"",jquery:"1.4.2",length:0,size:function(){return this.length},toArray:function(){return da.call(this,0)},get:function(a){return a==null?this.toArray():a<0?this.slice(a)[0]:this[a]},pushStack:function(a,b,d){var f=c();c.isArray(a)?ma.apply(f,a):c.merge(f,a);f.prevObject=this;f.context=
this.context;if(b==="find")f.selector=this.selector+(this.selector?" ":"")+d;else if(b)f.selector=this.selector+"."+b+"("+d+")";return f},each:function(a,b){return c.each(this,a,b)},ready:function(a){c.bindReady();if(c.isReady&&(!ja||Q.s.isDone))a.call(v,c);else{Y||(Y=[]);Y.push(a)}return this},eq:function(a){return a===-1?this.slice(a):this.slice(a,+a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(da.apply(this,arguments),"slice",
da.call(arguments).join(","))},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},end:function(){return this.prevObject||c(null)},push:ma,sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a=arguments[0]||{},b=1,d=arguments.length,f=false,e,i,j,o;if(typeof a==="boolean"){f=a;a=arguments[1]||{};b=2}if(typeof a!=="object"&&!c.isFunction(a))a={};if(d===b){a=this;--b}for(;b<d;b++)if((e=arguments[b])!=null)for(i in e){j=a[i];
o=e[i];if(a!==o)if(f&&o&&(c.isPlainObject(o)||c.isArray(o))){j=j&&(c.isPlainObject(j)||c.isArray(j))?j:c.isArray(o)?[]:{};a[i]=c.extend(f,j,o)}else if(o!==s)a[i]=o}return a};c.extend({noConflict:function(a){p.$=Wa;if(a)p.jQuery=Va;return c},isReady:false,ready:function(){if(!c.isReady){if(!v.body)return setTimeout(c.ready,13);c.isReady=true;c.callReady()}},callReady:function(){if(c.isReady&&(!ja||Q.s.isDone)){if(Y){for(var a,b=0;a=Y[b++];)a.call(v,c);Y=null}c.fn.triggerHandler&&c(v).triggerHandler("ready")}},
bindReady:function(){if(!Ba){Ba=true;if(v.readyState==="complete")return c.ready();if(v.addEventListener){v.addEventListener("DOMContentLoaded",Z,false);p.addEventListener("load",c.ready,false)}else if(v.attachEvent){v.attachEvent("onreadystatechange",Z);p.attachEvent("onload",c.ready);var a=false;try{a=p.frameElement==null}catch(b){}v.documentElement.doScroll&&a&&D()}}},isFunction:function(a){return ka.call(a)==="[object Function]"},isArray:function(a){return ka.call(a)==="[object Array]"},isPlainObject:function(a){if(!a||
ka.call(a)!=="[object Object]"||a.nodeType||a.setInterval)return false;if(a.constructor&&!la.call(a,"constructor")&&!la.call(a.constructor.prototype,"isPrototypeOf"))return false;var b;for(b in a);return b===s||la.call(a,b)},isEmptyObject:function(a){for(var b in a)return false;return true},error:function(a){throw a;},parseJSON:function(a){if(typeof a!=="string"||!a)return null;a=c.trim(a);if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return p.JSON&&p.JSON.parse?p.JSON.parse(a):(new Function("return "+a))();else c.error("Invalid JSON: "+a)},noop:function(){},globalEval:function(a){if(a&&Za.test(a)){var b=v.getElementsByTagName("head")[0]||v.documentElement,d=v.createElement("script");d.type="text/javascript";if(c.support.scriptEval)d.appendChild(v.createTextNode(a));else d.text=a;b.insertBefore(d,b.firstChild);b.removeChild(d)}},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===
b.toUpperCase()},each:function(a,b,d){var f,e=0,i=a.length,j=i===s||c.isFunction(a);if(d)if(j)for(f in a){if(b.apply(a[f],d)===false)break}else for(;e<i;){if(b.apply(a[e++],d)===false)break}else if(j)for(f in a){if(b.call(a[f],f,a[f])===false)break}else for(d=a[0];e<i&&b.call(d,e,d)!==false;d=a[++e]);return a},trim:function(a){return(a||"").replace($a,"")},makeArray:function(a,b){b=b||[];if(a!=null)a.length==null||typeof a==="string"||c.isFunction(a)||typeof a!=="function"&&a.setInterval?ma.call(b,
a):c.merge(b,a);return b},inArray:function(a,b){if(b.indexOf)return b.indexOf(a);for(var d=0,f=b.length;d<f;d++)if(b[d]===a)return d;return-1},merge:function(a,b){var d=a.length,f=0;if(typeof b.length==="number")for(var e=b.length;f<e;f++)a[d++]=b[f];else for(;b[f]!==s;)a[d++]=b[f++];a.length=d;return a},grep:function(a,b,d){for(var f=[],e=0,i=a.length;e<i;e++)!d!==!b(a[e],e)&&f.push(a[e]);return f},map:function(a,b,d){for(var f=[],e,i=0,j=a.length;i<j;i++){e=b(a[i],i,d);if(e!=null)f[f.length]=e}return f.concat.apply([],
f)},guid:1,proxy:function(a,b,d){if(arguments.length===2)if(typeof b==="string"){d=a;a=d[b];b=s}else if(b&&!c.isFunction(b)){d=b;b=s}if(!b&&a)b=function(){return a.apply(d||this,arguments)};if(a)b.guid=a.guid=a.guid||b.guid||c.guid++;return b},uaMatch:function(a){a=a.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||!/compatible/.test(a)&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},
browser:{}});ca=c.uaMatch(ca);if(ca.browser){c.browser[ca.browser]=true;c.browser.version=ca.version}if(c.browser.webkit)c.browser.safari=true;if(Ca)c.inArray=function(a,b){return Ca.call(b,a)};fa=c(v);if(v.addEventListener)Z=function(){v.removeEventListener("DOMContentLoaded",Z,false);c.ready()};else if(v.attachEvent)Z=function(){if(v.readyState==="complete"){v.detachEvent("onreadystatechange",Z);c.ready()}};(function(){c.support={};var a=v.documentElement,b=v.createElement("script"),d=v.createElement("div"),
f="script"+C();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var e=d.getElementsByTagName("*"),i=d.getElementsByTagName("a")[0];if(!(!e||!e.length||!i)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(i.getAttribute("style")),hrefNormalized:i.getAttribute("href")==="/a",opacity:/^0.55$/.test(i.style.opacity),
cssFloat:!!i.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:v.createElement("select").appendChild(v.createElement("option")).selected,parentNode:d.removeChild(d.appendChild(v.createElement("div"))).parentNode===null,deleteExpando:true,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null};b.type="text/javascript";try{b.appendChild(v.createTextNode("window."+f+"=1;"))}catch(j){}a.insertBefore(b,a.firstChild);if(p[f]){c.support.scriptEval=true;delete p[f]}try{delete b.test}catch(o){c.support.deleteExpando=
false}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function k(){c.support.noCloneEvent=false;d.detachEvent("onclick",k)});d.cloneNode(true).fireEvent("onclick")}d=v.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";a=v.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var k=v.createElement("div");k.style.width=k.style.paddingLeft="1px";v.body.appendChild(k);
c.boxModel=c.support.boxModel=k.offsetWidth===2;v.body.removeChild(k).style.display="none"});a=function(k){var n=v.createElement("div");k="on"+k;var u=k in n;if(!u){n.setAttribute(k,"return;");u=typeof n[k]==="function"}return u};c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=e=i=null}})();c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",
frameborder:"frameBorder"};var S="jQuery"+C(),bb=0,Da={};c.extend({cache:{},expando:S,noData:{embed:true,object:true,applet:true},data:function(a,b,d){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=a==p?Da:a;var f=a[S],e=c.cache;if(!f&&typeof b==="string"&&d===s)return null;f||(f=++bb);if(typeof b==="object"){a[S]=f;e[f]=c.extend(true,{},b)}else if(!e[f]){a[S]=f;e[f]={}}a=e[f];if(d!==s)a[b]=d;return typeof b==="string"?a[b]:a}},removeData:function(a,b){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=
a==p?Da:a;var d=a[S],f=c.cache,e=f[d];if(b){if(e){delete e[b];c.isEmptyObject(e)&&c.removeData(a)}}else{if(c.support.deleteExpando)delete a[c.expando];else a.removeAttribute&&a.removeAttribute(c.expando);delete f[d]}}}});c.fn.extend({data:function(a,b){if(typeof a==="undefined"&&this.length)return c.data(this[0]);else if(typeof a==="object")return this.each(function(){c.data(this,a)});var d=a.split(".");d[1]=d[1]?"."+d[1]:"";if(b===s){var f=this.triggerHandler("getData"+d[1]+"!",[d[0]]);if(f===s&&
this.length)f=c.data(this[0],a);return f===s&&d[1]?this.data(d[0]):f}else return this.trigger("setData"+d[1]+"!",[d[0],b]).each(function(){c.data(this,a,b)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var f=c.data(a,b);if(!d)return f||[];if(!f||c.isArray(d))f=c.data(a,b,c.makeArray(d));else f.push(d);return f}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),f=d.shift();if(f==="inprogress")f=d.shift();
if(f){b==="fx"&&d.unshift("inprogress");f.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===s)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||
"fx",[])}});var Ea=/[\n\t]/g,na=/\s+/,cb=/\r/g,db=/href|src|style/,eb=/(button|input)/i,fb=/(button|input|object|select|textarea)/i,gb=/^(a|area)$/i,Fa=/radio|checkbox/;c.fn.extend({attr:function(a,b){return A(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(n){var u=c(this);u.addClass(a.call(this,n,u.attr("class")))});if(a&&typeof a==="string")for(var b=
(a||"").split(na),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===1)if(e.className){for(var i=" "+e.className+" ",j=e.className,o=0,k=b.length;o<k;o++)if(i.indexOf(" "+b[o]+" ")<0)j+=" "+b[o];e.className=c.trim(j)}else e.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(k){var n=c(this);n.removeClass(a.call(this,k,n.attr("class")))});if(a&&typeof a==="string"||a===s)for(var b=(a||"").split(na),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===
1&&e.className)if(a){for(var i=(" "+e.className+" ").replace(Ea," "),j=0,o=b.length;j<o;j++)i=i.replace(" "+b[j]+" "," ");e.className=c.trim(i)}else e.className=""}return this},toggleClass:function(a,b){var d=typeof a,f=typeof b==="boolean";if(c.isFunction(a))return this.each(function(e){var i=c(this);i.toggleClass(a.call(this,e,i.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var e,i=0,j=c(this),o=b,k=a.split(na);e=k[i++];){o=f?o:!j.hasClass(e);j[o?"addClass":"removeClass"](e)}else if(d===
"undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=this.className||a===false?"":c.data(this,"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(Ea," ").indexOf(a)>-1)return true;return false},val:function(a){if(a===s){var b=this[0];if(b){if(c.nodeName(b,"option"))return(b.attributes.value||{}).specified?b.value:b.text;if(c.nodeName(b,"select")){var d=b.selectedIndex,f=
[],e=b.options;b=b.type==="select-one";if(d<0)return null;var i=b?d:0;for(d=b?d+1:e.length;i<d;i++){var j=e[i];if(j.selected){a=c(j).val();if(b)return a;f.push(a)}}return f}if(Fa.test(b.type)&&!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace(cb,"")}return s}var o=c.isFunction(a);return this.each(function(k){var n=c(this),u=a;if(this.nodeType===1){if(o)u=a.call(this,k,n.val());if(typeof u==="number")u+="";if(c.isArray(u)&&Fa.test(this.type))this.checked=
c.inArray(n.val(),u)>=0;else if(c.nodeName(this,"select")){var y=c.makeArray(u);c("option",this).each(function(){this.selected=c.inArray(c(this).val(),y)>=0});if(!y.length)this.selectedIndex=-1}else this.value=u}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,f){if(!a||a.nodeType===3||a.nodeType===8)return s;if(f&&b in c.attrFn)return c(a)[b](d);f=a.nodeType!==1||!c.isXMLDoc(a);var e=d!==s;b=f&&c.props[b]||b;if(a.nodeType===
1){var i=db.test(b);if(b in a&&f&&!i){if(e){b==="type"&&eb.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:fb.test(a.nodeName)||gb.test(a.nodeName)&&a.href?0:s;return a[b]}if(!c.support.style&&f&&b==="style"){if(e)a.style.cssText=""+d;return a.style.cssText}e&&a.setAttribute(b,""+d);a=!c.support.hrefNormalized&&
f&&i?a.getAttribute(b,2):a.getAttribute(b);return a===null?s:a}return c.style(a,b,d)}});var ba=/\.(.*)$/,hb=function(a){return a.replace(/[^\w\s\.\|`]/g,function(b){return"\\"+b})};c.event={add:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){if(a.setInterval&&a!==p&&!a.frameElement)a=p;var e,i;if(d.handler){e=d;d=e.handler}if(!d.guid)d.guid=c.guid++;if(i=c.data(a)){var j=i.events=i.events||{},o=i.handle;if(!o)i.handle=o=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(o.elem,
arguments):s};o.elem=a;b=b.split(" ");for(var k,n=0,u;k=b[n++];){i=e?c.extend({},e):{handler:d,data:f};if(k.indexOf(".")>-1){u=k.split(".");k=u.shift();i.namespace=u.slice(0).sort().join(".")}else{u=[];i.namespace=""}i.type=k;i.guid=d.guid;var y=j[k],F=c.event.special[k]||{};if(!y){y=j[k]=[];if(!F.setup||F.setup.call(a,f,u,o)===false)if(a.addEventListener)a.addEventListener(k,o,false);else a.attachEvent&&a.attachEvent("on"+k,o)}if(F.add){F.add.call(a,i);if(!i.handler.guid)i.handler.guid=d.guid}y.push(i);
c.event.global[k]=true}a=null}}},global:{},remove:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){var e,i=0,j,o,k,n,u,y,F=c.data(a),K=F&&F.events;if(F&&K){if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charAt(0)==="."){b=b||"";for(e in K)c.event.remove(a,e+b)}else{for(b=b.split(" ");e=b[i++];){n=e;j=e.indexOf(".")<0;o=[];if(!j){o=e.split(".");e=o.shift();k=new RegExp("(^|\\.)"+c.map(o.slice(0).sort(),hb).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(u=K[e])if(d){n=c.event.special[e]||
{};for(J=f||0;J<u.length;J++){y=u[J];if(d.guid===y.guid){if(j||k.test(y.namespace)){f==null&&u.splice(J--,1);n.remove&&n.remove.call(a,y)}if(f!=null)break}}if(u.length===0||f!=null&&u.length===1){if(!n.teardown||n.teardown.call(a,o)===false)Ga(a,e,F.handle);delete K[e]}}else for(var J=0;J<u.length;J++){y=u[J];if(j||k.test(y.namespace)){c.event.remove(a,n,y.handler,J);u.splice(J--,1)}}}if(c.isEmptyObject(K)){if(b=F.handle)b.elem=null;delete F.events;delete F.handle;c.isEmptyObject(F)&&c.removeData(a)}}}}},
trigger:function(a,b,d,f){var e=a.type||a;if(!f){a=typeof a==="object"?a[S]?a:c.extend(c.Event(e),a):c.Event(e);if(e.indexOf("!")>=0){a.type=e=e.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[e]&&c.each(c.cache,function(){this.events&&this.events[e]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return s;a.result=s;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(f=c.data(d,"handle"))&&f.apply(d,b);f=d.parentNode||d.ownerDocument;
try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+e]&&d["on"+e].apply(d,b)===false)a.result=false}catch(i){}if(!a.isPropagationStopped()&&f)c.event.trigger(a,b,f,true);else if(!a.isDefaultPrevented()){f=a.target;var j,o=c.nodeName(f,"a")&&e==="click",k=c.event.special[e]||{};if((!k._default||k._default.call(d,a)===false)&&!o&&!(f&&f.nodeName&&c.noData[f.nodeName.toLowerCase()])){try{if(f[e]){if(j=f["on"+e])f["on"+e]=null;c.event.triggered=true;f[e]()}}catch(n){}if(j)f["on"+e]=
j;c.event.triggered=false}}},handle:function(a){var b,d,f,e;a=arguments[0]=c.event.fix(a||p.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;if(!b){d=a.type.split(".");a.type=d.shift();f=new RegExp("(^|\\.)"+d.slice(0).sort().join("\\.(?:.*\\.)?")+"(\\.|$)")}e=c.data(this,"events");d=e[a.type];if(e&&d){d=d.slice(0);e=0;for(var i=d.length;e<i;e++){var j=d[e];if(b||f.test(j.namespace)){a.handler=j.handler;a.data=j.data;a.handleObj=j;j=j.handler.apply(this,arguments);if(j!==s){a.result=
j;if(j===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY originalTarget pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),fix:function(a){if(a[S])return a;
var b=a;a=c.Event(b);for(var d=this.props.length,f;d;){f=this.props[--d];a[f]=b[f]}if(!a.target)a.target=a.srcElement||v;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=v.documentElement;d=v.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||d&&d.scrollTop||0)-(b&&b.clientTop||
d&&d.clientTop||0)}if(!a.which&&(a.charCode||a.charCode===0?a.charCode:a.keyCode))a.which=a.charCode||a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==s)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,a.origType,c.extend({},a,{handler:t}))},remove:function(a){var b=true,d=a.origType.replace(ba,"");c.each(c.data(this,"events").live||[],function(){if(d===
this.origType.replace(ba,""))return b=false});b&&c.event.remove(this,a.origType,t)}},beforeunload:{setup:function(a,b,d){if(this.setInterval)this.onbeforeunload=d;return false},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};var Ga=v.removeEventListener?function(a,b,d){a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=a;this.type=a.type}else this.type=
a;this.timeStamp=C();this[S]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=H;var a=this.originalEvent;if(a){a.preventDefault&&a.preventDefault();a.returnValue=false}},stopPropagation:function(){this.isPropagationStopped=H;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=H;this.stopPropagation()},isDefaultPrevented:w,isPropagationStopped:w,isImmediatePropagationStopped:w};
var Ha=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},Ia=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?Ia:Ha,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?Ia:Ha)}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(this.nodeName.toLowerCase()!==
"form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length)return L("submit",this,arguments)});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13)return L("submit",this,arguments)})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var oa=/textarea|input|select/i,
pa,Ja=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(f){return f.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},qa=function(a,b){var d=a.target,f,e;if(!(!oa.test(d.nodeName)||d.readOnly)){f=c.data(d,"_change_data");e=Ja(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",e);if(!(f===s||e===f))if(f!=null||e){a.type="change";return c.event.trigger(a,
b,d)}}};c.event.special.change={filters:{focusout:qa,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return qa.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return qa.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",Ja(a))}},setup:function(){if(this.type==="file")return false;
for(var a in pa)c.event.add(this,a+".specialChange",pa[a]);return oa.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return oa.test(this.nodeName)}};pa=c.event.special.change.filters}v.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(f){f=c.event.fix(f);f.type=b;return c.event.handle.call(this,f)}c.event.special[b]={setup:function(){this.addEventListener(a,d,true)},teardown:function(){this.removeEventListener(a,d,true)}}});c.each(["bind",
"one"],function(a,b){c.fn[b]=function(d,f,e){if(typeof d==="object"){for(var i in d)this[b](i,f,d[i],e);return this}if(c.isFunction(f)){e=f;f=s}var j=b==="one"?c.proxy(e,function(k){c(this).unbind(k,j);return e.apply(this,arguments)}):e;if(d==="unload"&&b!=="one")this.one(d,f,e);else{i=0;for(var o=this.length;i<o;i++)c.event.add(this[i],d,j,f)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,a[d]);else{d=0;for(var f=this.length;d<
f;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,f){return this.live(b,d,f,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<b.length;)c.proxy(a,b[d++]);return this.click(c.proxy(a,
function(f){var e=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,e+1);f.preventDefault();return b[e].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var Ka={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,f,e,i){var j,o=0,k,n,u=i||this.selector,y=i?this:c(this.context);if(c.isFunction(f)){e=f;f=s}for(d=(d||"").split(" ");(j=d[o++])!=null;){i=
ba.exec(j);k="";if(i){k=i[0];j=j.replace(ba,"")}if(j==="hover")d.push("mouseenter"+k,"mouseleave"+k);else{n=j;if(j==="focus"||j==="blur"){d.push(Ka[j]+k);j+=k}else j=(Ka[j]||j)+k;b==="live"?y.each(function(){c.event.add(this,I(j,u),{data:f,selector:u,handler:e,origType:j,origHandler:e,preType:n})}):y.unbind(I(j,u),e)}}return this}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),
function(a,b){c.fn[b]=function(d){return d?this.bind(b,d):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});p.attachEvent&&!p.addEventListener&&p.attachEvent("onunload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});(function(){function a(g){for(var h="",l,m=0;g[m];m++){l=g[m];if(l.nodeType===3||l.nodeType===4)h+=l.nodeValue;else if(l.nodeType!==8)h+=a(l.childNodes)}return h}function b(g,h,l,m,r,q){r=0;for(var z=m.length;r<z;r++){var x=m[r];
if(x){x=x[g];for(var E=false;x;){if(x.sizcache===l){E=m[x.sizset];break}if(x.nodeType===1&&!q){x.sizcache=l;x.sizset=r}if(x.nodeName.toLowerCase()===h){E=x;break}x=x[g]}m[r]=E}}}function d(g,h,l,m,r,q){r=0;for(var z=m.length;r<z;r++){var x=m[r];if(x){x=x[g];for(var E=false;x;){if(x.sizcache===l){E=m[x.sizset];break}if(x.nodeType===1){if(!q){x.sizcache=l;x.sizset=r}if(typeof h!=="string"){if(x===h){E=true;break}}else if(k.filter(h,[x]).length>0){E=x;break}}x=x[g]}m[r]=E}}}var f=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^[\]]*\]|['"][^'"]*['"]|[^[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,
e=0,i=Object.prototype.toString,j=false,o=true;[0,0].sort(function(){o=false;return 0});var k=function(g,h,l,m){l=l||[];var r=h=h||v;if(h.nodeType!==1&&h.nodeType!==9)return[];if(!g||typeof g!=="string")return l;for(var q=[],z,x,E,ea,T=true,$=B(h),U=g;(f.exec(""),z=f.exec(U))!==null;){U=z[3];q.push(z[1]);if(z[2]){ea=z[3];break}}if(q.length>1&&u.exec(g))if(q.length===2&&n.relative[q[0]])x=ra(q[0]+q[1],h);else for(x=n.relative[q[0]]?[h]:k(q.shift(),h);q.length;){g=q.shift();if(n.relative[g])g+=q.shift();
x=ra(g,x)}else{if(!m&&q.length>1&&h.nodeType===9&&!$&&n.match.ID.test(q[0])&&!n.match.ID.test(q[q.length-1])){z=k.find(q.shift(),h,$);h=z.expr?k.filter(z.expr,z.set)[0]:z.set[0]}if(h){z=m?{expr:q.pop(),set:F(m)}:k.find(q.pop(),q.length===1&&(q[0]==="~"||q[0]==="+")&&h.parentNode?h.parentNode:h,$);x=z.expr?k.filter(z.expr,z.set):z.set;if(q.length>0)E=F(x);else T=false;for(;q.length;){var N=q.pop();z=N;if(n.relative[N])z=q.pop();else N="";if(z==null)z=h;n.relative[N](E,z,$)}}else E=[]}E||(E=x);E||k.error(N||
g);if(i.call(E)==="[object Array]")if(T)if(h&&h.nodeType===1)for(g=0;E[g]!=null;g++){if(E[g]&&(E[g]===true||E[g].nodeType===1&&O(h,E[g])))l.push(x[g])}else for(g=0;E[g]!=null;g++)E[g]&&E[g].nodeType===1&&l.push(x[g]);else l.push.apply(l,E);else F(E,l);if(ea){k(ea,r,l,m);k.uniqueSort(l)}return l};k.uniqueSort=function(g){if(J){j=o;g.sort(J);if(j)for(var h=1;h<g.length;h++)g[h]===g[h-1]&&g.splice(h--,1)}return g};k.matches=function(g,h){return k(g,null,null,h)};k.find=function(g,h,l){var m,r;if(!g)return[];
for(var q=0,z=n.order.length;q<z;q++){var x=n.order[q];if(r=n.leftMatch[x].exec(g)){var E=r[1];r.splice(1,1);if(E.substr(E.length-1)!=="\\"){r[1]=(r[1]||"").replace(/\\/g,"");m=n.find[x](r,h,l);if(m!=null){g=g.replace(n.match[x],"");break}}}}m||(m=h.getElementsByTagName("*"));return{set:m,expr:g}};k.filter=function(g,h,l,m){for(var r=g,q=[],z=h,x,E,ea=h&&h[0]&&B(h[0]);g&&h.length;){for(var T in n.filter)if((x=n.leftMatch[T].exec(g))!=null&&x[2]){var $=n.filter[T],U,N;N=x[1];E=false;x.splice(1,1);
if(N.substr(N.length-1)!=="\\"){if(z===q)q=[];if(n.preFilter[T])if(x=n.preFilter[T](x,z,l,q,m,ea)){if(x===true)continue}else E=U=true;if(x)for(var ga=0;(N=z[ga])!=null;ga++)if(N){U=$(N,x,ga,z);var La=m^!!U;if(l&&U!=null)if(La)E=true;else z[ga]=false;else if(La){q.push(N);E=true}}if(U!==s){l||(z=q);g=g.replace(n.match[T],"");if(!E)return[];break}}}if(g===r)if(E==null)k.error(g);else break;r=g}return z};k.error=function(g){throw"Syntax error, unrecognized expression: "+g;};var n=k.selectors={order:["ID",
"NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className",
"for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")}},relative:{"+":function(g,h){var l=typeof h==="string",m=l&&!/\W/.test(h);l=l&&!m;if(m)h=h.toLowerCase();m=0;for(var r=g.length,q;m<r;m++)if(q=g[m]){for(;(q=q.previousSibling)&&q.nodeType!==1;);g[m]=l||q&&q.nodeName.toLowerCase()===h?q||false:q===h}l&&k.filter(h,g,true)},">":function(g,h){var l=typeof h==="string";if(l&&!/\W/.test(h)){h=h.toLowerCase();for(var m=0,r=g.length;m<r;m++){var q=g[m];if(q){l=q.parentNode;g[m]=
l.nodeName.toLowerCase()===h?l:false}}}else{m=0;for(r=g.length;m<r;m++)if(q=g[m])g[m]=l?q.parentNode:q.parentNode===h;l&&k.filter(h,g,true)}},"":function(g,h,l){var m=e++,r=d;if(typeof h==="string"&&!/\W/.test(h)){var q=h=h.toLowerCase();r=b}r("parentNode",h,m,g,q,l)},"~":function(g,h,l){var m=e++,r=d;if(typeof h==="string"&&!/\W/.test(h)){var q=h=h.toLowerCase();r=b}r("previousSibling",h,m,g,q,l)}},find:{ID:function(g,h,l){if(typeof h.getElementById!=="undefined"&&!l)return(g=h.getElementById(g[1]))?
[g]:[]},NAME:function(g,h){if(typeof h.getElementsByName!=="undefined"){var l=[];h=h.getElementsByName(g[1]);for(var m=0,r=h.length;m<r;m++)h[m].getAttribute("name")===g[1]&&l.push(h[m]);return l.length===0?null:l}},TAG:function(g,h){return h.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,h,l,m,r,q){g=" "+g[1].replace(/\\/g,"")+" ";if(q)return g;q=0;for(var z;(z=h[q])!=null;q++)if(z)if(r^(z.className&&(" "+z.className+" ").replace(/[\t\n]/g," ").indexOf(g)>=0))l||m.push(z);else if(l)h[q]=
false;return false},ID:function(g){return g[1].replace(/\\/g,"")},TAG:function(g){return g[1].toLowerCase()},CHILD:function(g){if(g[1]==="nth"){var h=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&"0n+"+g[2]||g[2]);g[2]=h[1]+(h[2]||1)-0;g[3]=h[3]-0}g[0]=e++;return g},ATTR:function(g,h,l,m,r,q){h=g[1].replace(/\\/g,"");if(!q&&n.attrMap[h])g[1]=n.attrMap[h];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,h,l,m,r){if(g[1]==="not")if((f.exec(g[3])||
"").length>1||/^\w/.test(g[3]))g[3]=k(g[3],null,null,h);else{g=k.filter(g[3],h,l,true^r);l||m.push.apply(m,g);return false}else if(n.match.POS.test(g[0])||n.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},empty:function(g){return!g.firstChild},
has:function(g,h,l){return!!k(l[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===g.type||g.nodeName.toLowerCase()===
"button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)}},setFilters:{first:function(g,h){return h===0},last:function(g,h,l,m){return h===m.length-1},even:function(g,h){return h%2===0},odd:function(g,h){return h%2===1},lt:function(g,h,l){return h<l[3]-0},gt:function(g,h,l){return h>l[3]-0},nth:function(g,h,l){return l[3]-0===h},eq:function(g,h,l){return l[3]-0===h}},filter:{PSEUDO:function(g,h,l,m){var r=h[1],q=n.filters[r];if(q)return q(g,l,h,m);else if(r==="contains")return(g.textContent||
g.innerText||a([g])||"").indexOf(h[3])>=0;else if(r==="not"){h=h[3];l=0;for(m=h.length;l<m;l++)if(h[l]===g)return false;return true}else k.error("Syntax error, unrecognized expression: "+r)},CHILD:function(g,h){var l=h[1],m=g;switch(l){case "only":case "first":for(;m=m.previousSibling;)if(m.nodeType===1)return false;if(l==="first")return true;m=g;case "last":for(;m=m.nextSibling;)if(m.nodeType===1)return false;return true;case "nth":l=h[2];var r=h[3];if(l===1&&r===0)return true;h=h[0];var q=g.parentNode;
if(q&&(q.sizcache!==h||!g.nodeIndex)){var z=0;for(m=q.firstChild;m;m=m.nextSibling)if(m.nodeType===1)m.nodeIndex=++z;q.sizcache=h}g=g.nodeIndex-r;return l===0?g===0:g%l===0&&g/l>=0}},ID:function(g,h){return g.nodeType===1&&g.getAttribute("id")===h},TAG:function(g,h){return h==="*"&&g.nodeType===1||g.nodeName.toLowerCase()===h},CLASS:function(g,h){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(h)>-1},ATTR:function(g,h){var l=h[1];g=n.attrHandle[l]?n.attrHandle[l](g):g[l]!=null?g[l]:
g.getAttribute(l);l=g+"";var m=h[2];h=h[4];return g==null?m==="!=":m==="="?l===h:m==="*="?l.indexOf(h)>=0:m==="~="?(" "+l+" ").indexOf(h)>=0:!h?l&&g!==false:m==="!="?l!==h:m==="^="?l.indexOf(h)===0:m==="$="?l.substr(l.length-h.length)===h:m==="|="?l===h||l.substr(0,h.length+1)===h+"-":false},POS:function(g,h,l,m){var r=n.setFilters[h[2]];if(r)return r(g,l,h,m)}}},u=n.match.POS;for(var y in n.match){n.match[y]=new RegExp(n.match[y].source+/(?![^\[]*\])(?![^\(]*\))/.source);n.leftMatch[y]=new RegExp(/(^(?:.|\r|\n)*?)/.source+
n.match[y].source.replace(/\\(\d+)/g,function(g,h){return"\\"+(h-0+1)}))}var F=function(g,h){g=Array.prototype.slice.call(g,0);if(h){h.push.apply(h,g);return h}return g};try{Array.prototype.slice.call(v.documentElement.childNodes,0)}catch(K){F=function(g,h){h=h||[];if(i.call(g)==="[object Array]")Array.prototype.push.apply(h,g);else if(typeof g.length==="number")for(var l=0,m=g.length;l<m;l++)h.push(g[l]);else for(l=0;g[l];l++)h.push(g[l]);return h}}var J;if(v.documentElement.compareDocumentPosition)J=
function(g,h){if(!g.compareDocumentPosition||!h.compareDocumentPosition){if(g==h)j=true;return g.compareDocumentPosition?-1:1}g=g.compareDocumentPosition(h)&4?-1:g===h?0:1;if(g===0)j=true;return g};else if("sourceIndex"in v.documentElement)J=function(g,h){if(!g.sourceIndex||!h.sourceIndex){if(g==h)j=true;return g.sourceIndex?-1:1}g=g.sourceIndex-h.sourceIndex;if(g===0)j=true;return g};else if(v.createRange)J=function(g,h){if(!g.ownerDocument||!h.ownerDocument){if(g==h)j=true;return g.ownerDocument?
-1:1}var l=g.ownerDocument.createRange(),m=h.ownerDocument.createRange();l.setStart(g,0);l.setEnd(g,0);m.setStart(h,0);m.setEnd(h,0);g=l.compareBoundaryPoints(Range.START_TO_END,m);if(g===0)j=true;return g};(function(){var g=v.createElement("div"),h="script"+(new Date).getTime();g.innerHTML="<a name='"+h+"'/>";var l=v.documentElement;l.insertBefore(g,l.firstChild);if(v.getElementById(h)){n.find.ID=function(m,r,q){if(typeof r.getElementById!=="undefined"&&!q)return(r=r.getElementById(m[1]))?r.id===
m[1]||typeof r.getAttributeNode!=="undefined"&&r.getAttributeNode("id").nodeValue===m[1]?[r]:s:[]};n.filter.ID=function(m,r){var q=typeof m.getAttributeNode!=="undefined"&&m.getAttributeNode("id");return m.nodeType===1&&q&&q.nodeValue===r}}l.removeChild(g);l=g=null})();(function(){var g=v.createElement("div");g.appendChild(v.createComment(""));if(g.getElementsByTagName("*").length>0)n.find.TAG=function(h,l){l=l.getElementsByTagName(h[1]);if(h[1]==="*"){h=[];for(var m=0;l[m];m++)l[m].nodeType===1&&
h.push(l[m]);l=h}return l};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!=="undefined"&&g.firstChild.getAttribute("href")!=="#")n.attrHandle.href=function(h){return h.getAttribute("href",2)};g=null})();v.querySelectorAll&&function(){var g=k,h=v.createElement("div");h.innerHTML="<p class='TEST'></p>";if(!(h.querySelectorAll&&h.querySelectorAll(".TEST").length===0)){k=function(m,r,q,z){r=r||v;if(!z&&r.nodeType===9&&!B(r))try{return F(r.querySelectorAll(m),q)}catch(x){}return g(m,
r,q,z)};for(var l in g)k[l]=g[l];h=null}}();(function(){var g=v.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){n.order.splice(1,0,"CLASS");n.find.CLASS=function(h,l,m){if(typeof l.getElementsByClassName!=="undefined"&&!m)return l.getElementsByClassName(h[1])};g=null}}})();var O=v.compareDocumentPosition?function(g,
h){return!!(g.compareDocumentPosition(h)&16)}:function(g,h){return g!==h&&(g.contains?g.contains(h):true)},B=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false},ra=function(g,h){var l=[],m="",r;for(h=h.nodeType?[h]:h;r=n.match.PSEUDO.exec(g);){m+=r[0];g=g.replace(n.match.PSEUDO,"")}g=n.relative[g]?g+"*":g;r=0;for(var q=h.length;r<q;r++)k(g,h[r],l);return k.filter(m,l)};c.find=k;c.expr=k.selectors;c.expr[":"]=c.expr.filters;c.unique=k.uniqueSort;c.text=a;c.isXMLDoc=
B;c.contains=O})();var ib=/Until$/,jb=/^(?:parents|prevUntil|prevAll)/,kb=/,/;da=Array.prototype.slice;var Ma=function(a,b,d){if(c.isFunction(b))return c.grep(a,function(e,i){return!!b.call(e,i,e)===d});else if(b.nodeType)return c.grep(a,function(e){return e===b===d});else if(typeof b==="string"){var f=c.grep(a,function(e){return e.nodeType===1});if(Ya.test(b))return c.filter(b,f,!d);else b=c.filter(b,f)}return c.grep(a,function(e){return c.inArray(e,b)>=0===d})};c.fn.extend({find:function(a){for(var b=
this.pushStack("","find",a),d=0,f=0,e=this.length;f<e;f++){d=b.length;c.find(a,this[f],b);if(f>0)for(var i=d;i<b.length;i++)for(var j=0;j<d;j++)if(b[j]===b[i]){b.splice(i--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,f=b.length;d<f;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(Ma(this,a,false),"not",a)},filter:function(a){return this.pushStack(Ma(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>
0},closest:function(a,b){if(c.isArray(a)){var d=[],f=this[0],e,i={},j;if(f&&a.length){e=0;for(var o=a.length;e<o;e++){j=a[e];i[j]||(i[j]=c.expr.match.POS.test(j)?c(j,b||this.context):j)}for(;f&&f.ownerDocument&&f!==b;){for(j in i){e=i[j];if(e.jquery?e.index(f)>-1:c(f).is(e)){d.push({selector:j,elem:f});delete i[j]}}f=f.parentNode}}return d}var k=c.expr.match.POS.test(a)?c(a,b||this.context):null;return this.map(function(n,u){for(;u&&u.ownerDocument&&u!==b;){if(k?k.index(u)>-1:c(u).is(a))return u;
u=u.parentNode}return null})},index:function(a){if(!a||typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(M(a[0])||M(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},
parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},
contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,f){var e=c.map(this,b,d);ib.test(a)||(f=d);if(f&&typeof f==="string")e=c.filter(f,e);e=this.length>1?c.unique(e):e;if((this.length>1||kb.test(f))&&jb.test(a))e=e.reverse();return this.pushStack(e,a,da.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return c.find.matches(a,b)},dir:function(a,b,d){var f=[];for(a=
a[b];a&&a.nodeType!==9&&(d===s||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&f.push(a);a=a[b]}return f},nth:function(a,b,d){b=b||1;for(var f=0;a;a=a[d])if(a.nodeType===1&&++f===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Na=/ jQuery\d+="(?:\d+|null)"/g,ha=/^\s+/,Oa=/(<([\w:]+)[^>]*?)\/>/g,lb=/^(?:area|br|col|embed|hr|img|input|link|meta|param)$/i,Pa=/<([\w:]+)/,mb=/<tbody/i,nb=/<|&#?\w+;/,xa=/<script|<object|<embed|<option|<style/i,
ya=/checked\s*(?:[^=]|=\s*.checked.)/i,Qa=function(a,b,d){return lb.test(d)?a:b+"></"+d+">"},P={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};P.optgroup=P.option;P.tbody=P.tfoot=P.colgroup=P.caption=P.thead;P.th=P.td;if(!c.support.htmlSerialize)P._default=
[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==s)return this.empty().append((this[0]&&this[0].ownerDocument||v).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=
this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,
true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,
false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,f;(f=this[d])!=null;d++)if(!a||c.filter(a,[f]).length){if(!b&&f.nodeType===1){c.cleanData(f.getElementsByTagName("*"));c.cleanData([f])}f.parentNode&&f.parentNode.removeChild(f)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);
return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,f=this.ownerDocument;if(!d){d=f.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(Na,"").replace(/=([^="'>\s]+\/)>/g,'="$1">').replace(ha,"")],f)[0]}else return this.cloneNode(true)});if(a===true){V(this,b);V(this.find("*"),b.find("*"))}return b},html:function(a){if(a===s)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(Na,
""):null;else if(typeof a==="string"&&!xa.test(a)&&(c.support.leadingWhitespace||!ha.test(a))&&!P[(Pa.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Oa,Qa);try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(f){this.empty().append(a)}}else c.isFunction(a)?this.each(function(e){var i=c(this),j=i.html();i.empty().append(function(){return a.call(this,e,j)})}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&
this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),f=d.html();d.replaceWith(a.call(this,b,f))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){function f(y){return c.nodeName(y,"table")?y.getElementsByTagName("tbody")[0]||
y.appendChild(y.ownerDocument.createElement("tbody")):y}var e,i,j=a[0],o=[],k;if(!c.support.checkClone&&arguments.length===3&&typeof j==="string"&&ya.test(j))return this.each(function(){c(this).domManip(a,b,d,true)});if(c.isFunction(j))return this.each(function(y){var F=c(this);a[0]=j.call(this,y,b?F.html():s);F.domManip(a,b,d)});if(this[0]){e=j&&j.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:W(a,this,o);k=e.fragment;if(i=k.childNodes.length===
1?(k=k.firstChild):k.firstChild){b=b&&c.nodeName(i,"tr");for(var n=0,u=this.length;n<u;n++)d.call(b?f(this[n],i):this[n],n>0||e.cacheable||this.length>1?k.cloneNode(true):k)}o.length&&c.each(o,G)}return this}});c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var f=[];d=c(d);var e=this.length===1&&this[0].parentNode;if(e&&e.nodeType===11&&e.childNodes.length===1&&d.length===1){d[b](this[0]);
return this}else{e=0;for(var i=d.length;e<i;e++){var j=(e>0?this.clone(true):this).get();c.fn[b].apply(c(d[e]),j);f=f.concat(j)}return this.pushStack(f,a,d.selector)}}});c.extend({clean:function(a,b,d,f){b=b||v;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||v;for(var e=[],i=0,j;(j=a[i])!=null;i++){if(typeof j==="number")j+="";if(j){if(typeof j==="string"&&!nb.test(j))j=b.createTextNode(j);else if(typeof j==="string"){j=j.replace(Oa,Qa);var o=(Pa.exec(j)||["",
""])[1].toLowerCase(),k=P[o]||P._default,n=k[0],u=b.createElement("div");for(u.innerHTML=k[1]+j+k[2];n--;)u=u.lastChild;if(!c.support.tbody){n=mb.test(j);o=o==="table"&&!n?u.firstChild&&u.firstChild.childNodes:k[1]==="<table>"&&!n?u.childNodes:[];for(k=o.length-1;k>=0;--k)c.nodeName(o[k],"tbody")&&!o[k].childNodes.length&&o[k].parentNode.removeChild(o[k])}!c.support.leadingWhitespace&&ha.test(j)&&u.insertBefore(b.createTextNode(ha.exec(j)[0]),u.firstChild);j=u.childNodes}if(j.nodeType)e.push(j);else e=
c.merge(e,j)}}if(d)for(i=0;e[i];i++)if(f&&c.nodeName(e[i],"script")&&(!e[i].type||e[i].type.toLowerCase()==="text/javascript"))f.push(e[i].parentNode?e[i].parentNode.removeChild(e[i]):e[i]);else{e[i].nodeType===1&&e.splice.apply(e,[i+1,0].concat(c.makeArray(e[i].getElementsByTagName("script"))));d.appendChild(e[i])}return e},cleanData:function(a){for(var b,d,f=c.cache,e=c.event.special,i=c.support.deleteExpando,j=0,o;(o=a[j])!=null;j++)if(d=o[c.expando]){b=f[d];if(b.events)for(var k in b.events)e[k]?
c.event.remove(o,k):Ga(o,k,b.handle);if(i)delete o[c.expando];else o.removeAttribute&&o.removeAttribute(c.expando);delete f[d]}}});var ob=/z-?index|font-?weight|opacity|zoom|line-?height/i,Ra=/alpha\([^)]*\)/,Sa=/opacity=([^)]*)/,sa=/float/i,ta=/-([a-z])/ig,pb=/([A-Z])/g,qb=/^-?\d+(?:px)?$/i,rb=/^-?\d/,sb={position:"absolute",visibility:"hidden",display:"block"},tb=["Left","Right"],ub=["Top","Bottom"],vb=v.defaultView&&v.defaultView.getComputedStyle,Ta=c.support.cssFloat?"cssFloat":"styleFloat",ua=
function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){return A(this,a,b,true,function(d,f,e){if(e===s)return c.curCSS(d,f);if(typeof e==="number"&&!ob.test(f))e+="px";c.style(d,f,e)})};c.extend({style:function(a,b,d){if(!a||a.nodeType===3||a.nodeType===8)return s;if((b==="width"||b==="height")&&parseFloat(d)<0)d=s;var f=a.style||a,e=d!==s;if(!c.support.opacity&&b==="opacity"){if(e){f.zoom=1;b=parseInt(d,10)+""==="NaN"?"":"alpha(opacity="+d*100+")";a=f.filter||c.curCSS(a,"filter")||"";f.filter=
Ra.test(a)?a.replace(Ra,b):b}return f.filter&&f.filter.indexOf("opacity=")>=0?parseFloat(Sa.exec(f.filter)[1])/100+"":""}if(sa.test(b))b=Ta;b=b.replace(ta,ua);if(e)f[b]=d;return f[b]},css:function(a,b,d,f){if(b==="width"||b==="height"){var e,i=b==="width"?tb:ub;d=function(){e=b==="width"?a.offsetWidth:a.offsetHeight;f!=="border"&&c.each(i,function(){f||(e-=parseFloat(c.curCSS(a,"padding"+this,true))||0);if(f==="margin")e+=parseFloat(c.curCSS(a,"margin"+this,true))||0;else e-=parseFloat(c.curCSS(a,
"border"+this+"Width",true))||0})};a.offsetWidth!==0?d():c.swap(a,sb,d);return Math.max(0,Math.round(e))}return c.curCSS(a,b,d)},curCSS:function(a,b,d){var f,e=a.style;if(!c.support.opacity&&b==="opacity"&&a.currentStyle){f=Sa.test(a.currentStyle.filter||"")?parseFloat(RegExp.$1)/100+"":"";return f===""?"1":f}if(sa.test(b))b=Ta;if(!d&&e&&e[b])f=e[b];else if(vb){if(sa.test(b))b="float";b=b.replace(pb,"-$1").toLowerCase();e=a.ownerDocument.defaultView;if(!e)return null;if(a=e.getComputedStyle(a,null))f=
a.getPropertyValue(b);if(b==="opacity"&&f==="")f="1"}else if(a.currentStyle){d=b.replace(ta,ua);f=a.currentStyle[b]||a.currentStyle[d];if(!qb.test(f)&&rb.test(f)){b=e.left;var i=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;e.left=d==="fontSize"?"1em":f||0;f=e.pixelLeft+"px";e.left=b;a.runtimeStyle.left=i}}return f},swap:function(a,b,d){var f={};for(var e in b){f[e]=a.style[e];a.style[e]=b[e]}d.call(a);for(e in b)a.style[e]=f[e]}});if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=
a.offsetWidth,d=a.offsetHeight,f=a.nodeName.toLowerCase()==="tr";return b===0&&d===0&&!f?true:b>0&&d>0&&!f?false:c.curCSS(a,"display")==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var wb=C(),xb=/<script(.|\s)*?\/script>/gi,yb=/select|textarea/i,zb=/color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week/i,aa=/=\?(&|$)/,va=/\?/,Ab=/(\?|&)_=.*?(&|$)/,Bb=/^(\w+:)?\/\/([^\/?#]+)/,Cb=/%20/g,Db=c.fn.load;c.fn.extend({load:function(a,b,
d){if(typeof a!=="string")return Db.call(this,a);else if(!this.length)return this;var f=a.indexOf(" ");if(f>=0){var e=a.slice(f,a.length);a=a.slice(0,f)}f="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);f="POST"}var i=this;c.ajax({url:a,type:f,dataType:"html",data:b,complete:function(j,o){if(o==="success"||o==="notmodified")i.html(e?c("<div />").append(j.responseText.replace(xb,"")).find(e):j.responseText);d&&i.each(d,[j.responseText,
o,j])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||yb.test(this.nodeName)||zb.test(this.type))}).map(function(a,b){a=c(this).val();return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),
function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:f})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b={}}return c.ajax({type:"POST",url:a,data:b,success:d,dataType:f})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,
global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:p.XMLHttpRequest&&(p.location.protocol!=="file:"||!p.ActiveXObject)?function(){return new p.XMLHttpRequest}:function(){try{return new p.ActiveXObject("Microsoft.XMLHTTP")}catch(a){}},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},lastModified:{},etag:{},ajax:function(a){function b(){e.success&&
e.success.call(k,o,j,B);e.global&&f("ajaxSuccess",[B,e])}function d(){e.complete&&e.complete.call(k,B,j);e.global&&f("ajaxComplete",[B,e]);e.global&&!--c.active&&c.event.trigger("ajaxStop")}function f(r,q){(e.context?c(e.context):c.event).trigger(r,q)}var e=c.extend(true,{},c.ajaxSettings,a),i,j,o,k=a&&a.context||e,n=e.type.toUpperCase();if(e.data&&e.processData&&typeof e.data!=="string")e.data=c.param(e.data,e.traditional);if(e.dataType==="jsonp"){if(n==="GET")aa.test(e.url)||(e.url+=(va.test(e.url)?
"&":"?")+(e.jsonp||"callback")+"=?");else if(!e.data||!aa.test(e.data))e.data=(e.data?e.data+"&":"")+(e.jsonp||"callback")+"=?";e.dataType="json"}if(e.dataType==="json"&&(e.data&&aa.test(e.data)||aa.test(e.url))){i=e.jsonpCallback||"jsonp"+wb++;if(e.data)e.data=(e.data+"").replace(aa,"="+i+"$1");e.url=e.url.replace(aa,"="+i+"$1");e.dataType="script";p[i]=p[i]||function(r){o=r;b();d();p[i]=s;try{delete p[i]}catch(q){}F&&F.removeChild(K)}}if(e.dataType==="script"&&e.cache===null)e.cache=false;if(e.cache===
false&&n==="GET"){var u=C(),y=e.url.replace(Ab,"$1_="+u+"$2");e.url=y+(y===e.url?(va.test(e.url)?"&":"?")+"_="+u:"")}if(e.data&&n==="GET")e.url+=(va.test(e.url)?"&":"?")+e.data;e.global&&!c.active++&&c.event.trigger("ajaxStart");u=(u=Bb.exec(e.url))&&(u[1]&&u[1]!==location.protocol||u[2]!==location.host);if(e.dataType==="script"&&n==="GET"&&u){var F=v.getElementsByTagName("head")[0]||v.documentElement,K=v.createElement("script");K.src=e.url;if(e.scriptCharset)K.charset=e.scriptCharset;if(!i){var J=
false;K.onload=K.onreadystatechange=function(){if(!J&&(!this.readyState||this.readyState==="loaded"||this.readyState==="complete")){J=true;b();d();K.onload=K.onreadystatechange=null;F&&K.parentNode&&F.removeChild(K)}}}F.insertBefore(K,F.firstChild);return s}var O=false,B=e.xhr();if(B){e.username?B.open(n,e.url,e.async,e.username,e.password):B.open(n,e.url,e.async);try{if(e.data||a&&a.contentType)B.setRequestHeader("Content-Type",e.contentType);if(e.ifModified){c.lastModified[e.url]&&B.setRequestHeader("If-Modified-Since",
c.lastModified[e.url]);c.etag[e.url]&&B.setRequestHeader("If-None-Match",c.etag[e.url])}u||B.setRequestHeader("X-Requested-With","XMLHttpRequest");B.setRequestHeader("Accept",e.dataType&&e.accepts[e.dataType]?e.accepts[e.dataType]+", */*":e.accepts._default)}catch(ra){}if(e.beforeSend&&e.beforeSend.call(k,B,e)===false){e.global&&!--c.active&&c.event.trigger("ajaxStop");B.abort();return false}e.global&&f("ajaxSend",[B,e]);var g=B.onreadystatechange=function(r){if(!B||B.readyState===0||r==="abort"){O||
d();O=true;if(B)B.onreadystatechange=c.noop}else if(!O&&B&&(B.readyState===4||r==="timeout")){O=true;B.onreadystatechange=c.noop;j=r==="timeout"?"timeout":!c.httpSuccess(B)?"error":e.ifModified&&c.httpNotModified(B,e.url)?"notmodified":"success";var q;if(j==="success")try{o=c.httpData(B,e.dataType,e)}catch(z){j="parsererror";q=z}if(j==="success"||j==="notmodified")i||b();else c.handleError(e,B,j,q);d();r==="timeout"&&B.abort();if(e.async)B=null}};try{var h=B.abort;B.abort=function(){B&&h.call(B);
g("abort")}}catch(l){}e.async&&e.timeout>0&&setTimeout(function(){B&&!O&&g("timeout")},e.timeout);try{B.send(n==="POST"||n==="PUT"||n==="DELETE"?e.data:null)}catch(m){c.handleError(e,B,null,m);d()}e.async||g();return B}},handleError:function(a,b,d,f){if(a.error)a.error.call(a.context||a,b,d,f);if(a.global)(a.context?c(a.context):c.event).trigger("ajaxError",[b,a,f])},active:0,httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===
1223||a.status===0}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),f=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(f)c.etag[b]=f;return a.status===304||a.status===0},httpData:function(a,b,d){var f=a.getResponseHeader("content-type")||"",e=b==="xml"||!b&&f.indexOf("xml")>=0;a=e?a.responseXML:a.responseText;e&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b===
"json"||!b&&f.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&f.indexOf("javascript")>=0)c.globalEval(a);return a},param:function(a,b){function d(j,o){if(c.isArray(o))c.each(o,function(k,n){b||/\[\]$/.test(j)?f(j,n):d(j+"["+(typeof n==="object"||c.isArray(n)?k:"")+"]",n)});else!b&&o!=null&&typeof o==="object"?c.each(o,function(k,n){d(j+"["+k+"]",n)}):f(j,o)}function f(j,o){o=c.isFunction(o)?o():o;e[e.length]=encodeURIComponent(j)+"="+encodeURIComponent(o)}var e=[];if(b===s)b=c.ajaxSettings.traditional;
if(c.isArray(a)||a.jquery)c.each(a,function(){f(this.name,this.value)});else for(var i in a)d(i,a[i]);return e.join("&").replace(Cb,"+")}});var wa={},Eb=/toggle|show|hide/,Fb=/^([+-]=)?([\d+-.]+)(.*)$/,ia,za=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]];c.fn.extend({show:function(a,b){if(a||a===0)return this.animate(X("show",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");
this[a].style.display=d||"";if(c.css(this[a],"display")==="none"){d=this[a].nodeName;var f;if(wa[d])f=wa[d];else{var e=c("<"+d+" />").appendTo("body");f=e.css("display");if(f==="none")f="block";e.remove();wa[d]=f}c.data(this[a],"olddisplay",f)}}a=0;for(b=this.length;a<b;a++)this[a].style.display=c.data(this[a],"olddisplay")||"";return this}},hide:function(a,b){if(a||a===0)return this.animate(X("hide",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");!d&&d!=="none"&&c.data(this[a],
"olddisplay",c.css(this[a],"display"))}a=0;for(b=this.length;a<b;a++)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b){var d=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,arguments);else a==null||d?this.each(function(){var f=d?a:c(this).is(":hidden");c(this)[f?"show":"hide"]()}):this.animate(X("toggle",3),a,b);return this},fadeTo:function(a,b,d){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d)},
animate:function(a,b,d,f){var e=c.speed(b,d,f);if(c.isEmptyObject(a))return this.each(e.complete);return this[e.queue===false?"each":"queue"](function(){var i=c.extend({},e),j,o=this.nodeType===1&&c(this).is(":hidden"),k=this;for(j in a){var n=j.replace(ta,ua);if(j!==n){a[n]=a[j];delete a[j];j=n}if(a[j]==="hide"&&o||a[j]==="show"&&!o)return i.complete.call(this);if((j==="height"||j==="width")&&this.style){i.display=c.css(this,"display");i.overflow=this.style.overflow}if(c.isArray(a[j])){(i.specialEasing=
i.specialEasing||{})[j]=a[j][1];a[j]=a[j][0]}}if(i.overflow!=null)this.style.overflow="hidden";i.curAnim=c.extend({},a);c.each(a,function(u,y){var F=new c.fx(k,i,u);if(Eb.test(y))F[y==="toggle"?o?"show":"hide":y](a);else{var K=Fb.exec(y),J=F.cur(true)||0;if(K){y=parseFloat(K[2]);var O=K[3]||"px";if(O!=="px"){k.style[u]=(y||1)+O;J=(y||1)/F.cur(true)*J;k.style[u]=J+O}if(K[1])y=(K[1]==="-="?-1:1)*y+J;F.custom(J,y,O)}else F.custom(J,y,"")}});return true})},stop:function(a,b){var d=c.timers;a&&this.queue([]);
this.each(function(){for(var f=d.length-1;f>=0;f--)if(d[f].elem===this){b&&d[f](true);d.splice(f,1)}});b||this.dequeue();return this}});c.each({slideDown:X("show",1),slideUp:X("hide",1),slideToggle:X("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"}},function(a,b){c.fn[a]=function(d,f){return this.animate(b,d,f)}});c.extend({speed:function(a,b,d){var f=a&&typeof a==="object"?a:{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};f.duration=c.fx.off?0:typeof f.duration===
"number"?f.duration:c.fx.speeds[f.duration]||c.fx.speeds._default;f.old=f.complete;f.complete=function(){f.queue!==false&&c(this).dequeue();c.isFunction(f.old)&&f.old.call(this)};return f},easing:{linear:function(a,b,d,f){return d+f*a},swing:function(a,b,d,f){return(-Math.cos(a*Math.PI)/2+0.5)*f+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||
c.fx.step._default)(this);if((this.prop==="height"||this.prop==="width")&&this.elem.style)this.elem.style.display="block"},cur:function(a){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];return(a=parseFloat(c.css(this.elem,this.prop,a)))&&a>-10000?a:parseFloat(c.curCSS(this.elem,this.prop))||0},custom:function(a,b,d){function f(i){return e.step(i)}this.startTime=C();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;
this.pos=this.state=0;var e=this;f.elem=this.elem;if(f()&&c.timers.push(f)&&!ia)ia=setInterval(c.fx.tick,13)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=C(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=
this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=true;for(var f in this.options.curAnim)if(this.options.curAnim[f]!==true)d=false;if(d){if(this.options.display!=null){this.elem.style.overflow=this.options.overflow;a=c.data(this.elem,"olddisplay");this.elem.style.display=a?a:this.options.display;if(c.css(this.elem,"display")==="none")this.elem.style.display="block"}this.options.hide&&c(this.elem).hide();if(this.options.hide||this.options.show)for(var e in this.options.curAnim)c.style(this.elem,
e,this.options.orig[e]);this.options.complete.call(this.elem)}return false}else{e=b-this.startTime;this.state=e/this.options.duration;a=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||a](this.state,e,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||
c.fx.stop()},stop:function(){clearInterval(ia);ia=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};c.fn.offset="getBoundingClientRect"in
v.documentElement?function(a){var b=this[0];if(a)return this.each(function(e){c.offset.setOffset(this,a,e)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);var d=b.getBoundingClientRect(),f=b.ownerDocument;b=f.body;f=f.documentElement;return{top:d.top+(self.pageYOffset||c.support.boxModel&&f.scrollTop||b.scrollTop)-(f.clientTop||b.clientTop||0),left:d.left+(self.pageXOffset||c.support.boxModel&&f.scrollLeft||b.scrollLeft)-(f.clientLeft||b.clientLeft||
0)}}:function(a){var b=this[0];if(a)return this.each(function(u){c.offset.setOffset(this,a,u)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d=b.offsetParent,f=b,e=b.ownerDocument,i,j=e.documentElement,o=e.body;f=(e=e.defaultView)?e.getComputedStyle(b,null):b.currentStyle;for(var k=b.offsetTop,n=b.offsetLeft;(b=b.parentNode)&&b!==o&&b!==j;){if(c.offset.supportsFixedPosition&&f.position==="fixed")break;i=e?e.getComputedStyle(b,
null):b.currentStyle;k-=b.scrollTop;n-=b.scrollLeft;if(b===d){k+=b.offsetTop;n+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&/^t(able|d|h)$/i.test(b.nodeName))){k+=parseFloat(i.borderTopWidth)||0;n+=parseFloat(i.borderLeftWidth)||0}f=d;d=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&i.overflow!=="visible"){k+=parseFloat(i.borderTopWidth)||0;n+=parseFloat(i.borderLeftWidth)||0}f=i}if(f.position==="relative"||f.position==="static"){k+=o.offsetTop;
n+=o.offsetLeft}if(c.offset.supportsFixedPosition&&f.position==="fixed"){k+=Math.max(j.scrollTop,o.scrollTop);n+=Math.max(j.scrollLeft,o.scrollLeft)}return{top:k,left:n}};c.offset={initialize:function(){var a=v.body,b=v.createElement("div"),d,f,e,i=parseFloat(c.curCSS(a,"marginTop",true))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
a.insertBefore(b,a.firstChild);d=b.firstChild;f=d.firstChild;e=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=f.offsetTop!==5;this.doesAddBorderForTableAndCells=e.offsetTop===5;f.style.position="fixed";f.style.top="20px";this.supportsFixedPosition=f.offsetTop===20||f.offsetTop===15;f.style.position=f.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=f.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==i;a.removeChild(b);
c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=parseFloat(c.curCSS(a,"marginTop",true))||0;d+=parseFloat(c.curCSS(a,"marginLeft",true))||0}return{top:b,left:d}},setOffset:function(a,b,d){if(/static/.test(c.curCSS(a,"position")))a.style.position="relative";var f=c(a),e=f.offset(),i=parseInt(c.curCSS(a,"top",true),10)||0,j=parseInt(c.curCSS(a,"left",true),10)||0;if(c.isFunction(b))b=b.call(a,
d,e);d={top:b.top-e.top+i,left:b.left-e.left+j};"using"in b?b.using.call(a,d):f.css(d)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),f=/^body|html$/i.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.curCSS(a,"marginTop",true))||0;d.left-=parseFloat(c.curCSS(a,"marginLeft",true))||0;f.top+=parseFloat(c.curCSS(b[0],"borderTopWidth",true))||0;f.left+=parseFloat(c.curCSS(b[0],"borderLeftWidth",true))||0;return{top:d.top-
f.top,left:d.left-f.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||v.body;a&&!/^body|html$/i.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(f){var e=this[0],i;if(!e)return null;if(f!==s)return this.each(function(){if(i=Aa(this))i.scrollTo(!a?f:c(i).scrollLeft(),a?f:c(i).scrollTop());else this[d]=f});else return(i=Aa(e))?"pageXOffset"in i?i[a?"pageYOffset":
"pageXOffset"]:c.support.boxModel&&i.document.documentElement[d]||i.document.body[d]:e[d]}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?c.css(this[0],d,false,"padding"):null};c.fn["outer"+b]=function(f){return this[0]?c.css(this[0],d,false,f?"margin":"border"):null};c.fn[d]=function(f){var e=this[0];if(!e)return f==null?null:this;if(c.isFunction(f))return this.each(function(i){var j=c(this);j[d](f.call(this,i,j[d]()))});return"scrollTo"in
e&&e.document?e.document.compatMode==="CSS1Compat"&&e.document.documentElement["client"+b]||e.document.body["client"+b]:e.nodeType===9?Math.max(e.documentElement["client"+b],e.body["scroll"+b],e.documentElement["scroll"+b],e.body["offset"+b],e.documentElement["offset"+b]):f===s?c.css(e,d):this.css(d,typeof f==="string"?f:f+"px")}});if(ja){var Ua=Q.callReady;Q.callReady=function(){Ua&&Ua();c.callReady()};Q.def("jquery",function(){return c});Q.def("jQuery",function(){return c})}})(window);Q(["bibliobird/Embed"],
function(p){p.start()})})();
