/*

 jQuery JavaScript Library v1.4.2
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Sat Feb 13 22:33:48 2010 -0500
*/
(function(){var S,U;(function(){function m(K){var I=F[K];if(I)return I;if(!s[K])throw new Error("Module "+K+" not found");for(var z=s[K],C=z.deps||(z.length?["require","exports","module"]:[]),J=F[K]={},B=0;B<C.length;B++){var v=C[B];switch(v){case "require":v=function(M){if(M.charAt(0)==="."){for(M=K.substring(0,K.lastIndexOf("/")+1)+M;T!==M;){var T=M;M=M.replace(/\/[^\/]*\/\.\.\//,"/")}M=M.replace(/\/\.\//g,"/")}return m(M)};break;case "exports":v=J;break;case "module":I=v={exports:J};break;default:v=
m(v)}C[B]=v}J=z.apply(this,C);if(I&&I.exports!=F[K])J=I.exports;if(J)return F[K]=J;return F[K]}var s={},F={};S=function(K,I){for(var z=[],C=0;C<K.length;C++)z.push(m(K[C]));I.apply(m,z)};U=S.def=function(K,I,z){if(typeof I=="function")s[K]=I;else(s[K]=z).deps=I}})();U("lingwo_dictionary/util/extendPrototype",[],function(){return function(m,s){for(var F in s)m.prototype[F]=s[F]}});U("lingwo_dictionary/util/declare",["lingwo_dictionary/util/extendPrototype"],function(m){return function(s){var F=s._constructor;
delete s._constructor;m(F,s);return F}});U("lingwo_dictionary/layout/Popup",["jquery","lingwo_dictionary/util/declare"],function(m,s){return s({_constructor:function(F){this.popup=F.node},shutdown:function(){},layout:function(F){F=m(F);var K=m(this.popup),I=K.width(),z=F.offset(),C=z.left+F.width()/2-I/2;F=z.top+F.height()+40;z=m(document).width();if(C+I>z)C=z-I;if(C<0)C=0;K.show().css({left:C,top:F})}})});U("lingwo_dictionary/util/clobber",[],function(){return function(m,s,F){old_fn=m[s];m[s]=function(){old_fn.apply(this,
arguments);F()}}});U("lingwo_dictionary/util/clone",[],function(){return function(m){var s={},F;for(F in m)s[F]=m[F];return s}});U("lingwo_dictionary/util/proxy",[],function(){return function(m,s){return function(){return m.apply(s,arguments)}}});S.def("lingwo_dictionary/annotation/Reader2",["jquery","lingwo_dictionary/layout/Popup","lingwo_dictionary/util/clobber","lingwo_dictionary/util/clone","lingwo_dictionary/util/proxy"],function(m,s,F,K,I){var z,C,J=/MSIE 6/i.test(navigator.userAgent),B={layout:"docked"};
C={popup:{setup:function(){z.bubbleNode.addClass("popup");this._layout=new s({node:z.bubbleNode})},shutdown:function(){z.bubbleNode.removeClass("popup");this._layout.shutdown()},show:function(){var v=z.bubbleNode;this._layout.layout(z.selectedNode);v.css("height","");if(J||v.height()>200)v.css({height:200})},hide:function(){z.bubbleNode.hide()}},docked:{_dock:null,_footer:null,_footerId:null,_footerMargin:null,_positionBubble:function(){z.bubbleNode.show();var v=z.bubbleNode,M=this._dock.offset(),
T=this._footer.offset().top;v.outerWidth();v.innerWidth();var Z=v.outerHeight()-v.innerHeight(),w=Math.max(M.top-m(window).scrollTop()+1,0);T=Math.min(T-m(window).scrollTop()-w-this._footerMargin+1,m(window).height()-w)-Z;v.css({left:M.left-m(window).scrollLeft(),top:w,height:T})},_drupalHack:false,setup:function(){z.bubbleNode.addClass("docked");this._dock=m("#lingwo-korpus-dock");this._footerId=this._dock.attr("data-footer-id");this._footerMargin=this._dock.attr("data-footer-margin");this._footer=
m("#"+this._footerId);var v=I(this._positionBubble,this);m(window).bind("scroll.lingwoReaderDocked",v);m(window).bind("resize.lingwoReaderDocked",v);if(!this._drupalHack){typeof window.Drupal!="undefined"&&Drupal.adminToolbar&&F(Drupal.adminToolbar,"setState",function(){if(z.layout===C.docked){z.bubbleNode.hide();setTimeout(v,500)}});this._drupalHack=true}z.setBubbleContent("<em>Click a work in the text to look it up in the dictionary.</em>");setTimeout(v,0)},shutdown:function(){z.bubbleNode.removeClass("docked");
this._dock=this._footerId=this._footerMargin=this._footer=null;m(window).unbind(".lingwoReaderDocked")},show:function(){},hide:function(){}}};return z={defaultLayouts:C,onLoad:function(){},config:null,bubbleNode:null,contentNode:null,selectedNode:null,shown:false,isSetup:false,layout:null,setup:function(v){if(typeof v=="undefined")v=K(B);this.config=v;if(this.config.layout=="docked"&&J)this.config.layout="popup";if(this.isSetup){this.layout.shutdown();this.layout=null;this.isSetup=false}if(!this.bubbleNode)this.bubbleNode=
m("<div></div>").attr("id","lingwo-korpus-entry-view-wrapper").appendTo(m("body")).hide();if(!this.contentNode)this.contentNode=m("<div></div>").attr("id","lingwo-korpus-entry-view").appendTo(this.bubbleNode);v=typeof this.config.layout=="string"?C[this.config.layout]:this.config.layout;v.setup();this.config.skipHoverEvents||this.setupHoverEvents();this.layout=v;this.isSetup=false},setupHoverEvents:function(){m(".anno, .anno-anchor").unbind("mouseenter mouseleave").bind("mouseenter",function(v){v=
m(v.target);v.addClass("hover");if(v=z._getAnnoText(v))v.addClass("hover")}).bind("mouseleave",function(v){v=m(v.target);v.removeClass("hover");if(v=z._getAnnoText(v))v.removeClass("hover")})},_getAnnoText:function(v){if(v.hasClass("anno-anchor"))if(v=v.attr("data-anno"))return m("#"+v);return null},setSelection:function(v){var M;if(this.selectedNode){this.selectedNode.removeClass("selected");if(M=this._getAnnoText(this.selectedNode))M.removeClass("selected");this.selectedNode=null}if(v){v=m(v);v.addClass("selected");
this.selectedNode=v;if(M=this._getAnnoText(this.selectedNode))M.addClass("selected")}},clearSelection:function(){this.setSelection(null)},isInsideBubble:function(v){for(;v=v.parentNode;)if(v.id=="lingwo-korpus-entry-view")return true;return false},showBubble:function(){this.layout.show();this.shown=true},hideBubble:function(){this.layout.hide();this.shown=false},setBubbleContent:function(v){this.contentNode.html(v)},setBubbleLoading:function(){this.setBubbleContent("Loading...")},isWordNode:function(v){return m(v).hasClass("anno")||
m(v).hasClass("anno-anchor")},handleClick:function(v){if(this.isWordNode(v)){if(this.isInsideBubble(v))this.onLoad(m(v));else{this.setSelection(v);this.onLoad(this.selectedNode);this.showBubble()}return false}this.clearSelection();this.hideBubble()}}});U("lingwo_dictionary/layout/BottomDock",["jquery","lingwo_dictionary/util/declare","lingwo_dictionary/util/proxy"],function(m,s,F){function K(){var C=null;if(document.createElement){var J=document.createElement("div");if(J&&J.style){J.style.position=
"fixed";J.style.top="10px";var B=document.body;if(B&&B.appendChild&&B.removeChild){B.appendChild(J);C=J.offsetTop===10;B.removeChild(J)}}}return C}var I=navigator.userAgent.toLowerCase(),z=K()&&!/iphone|ipod|android/.exec(I);return s({_constructor:function(C){this.node=C.node;this.size=C.size;this.spacerNode=m("<div></div>").appendTo(m("body")).css("height",this.size).get(0);m(this.node).css({position:z?"fixed":"absolute",overflow:"hidden"}).appendTo(m("body"));this._layoutProxy=F(this.layout,this);
m(window).bind("resize",this._layoutProxy);z||m(window).bind("scroll",this._layoutProxy)},shutdown:function(){m(window).unbind("resize",this._layoutProxy);z||m(window).unbind("scroll",this._layoutProxy);m(this.node).remove();m(this.spacer).remove()},onlayout:function(){},layout:function(){var C=Math.min(m(window).width(),m(document).width()),J=m(window).height(),B=m(document).height();J=J-this.size;var v=0;if(!z){J+=m(window).scrollTop();v+=m(window).scrollLeft()}if(J+this.size>B)J=B-this.size;m(this.spacerNode).css("height",
this.size);m(this.node).css({top:J,left:v,width:C,height:this.size});this.onlayout(J,v,C,this.size)}})});U("bibliobird/Embed",["jquery","lingwo_dictionary/annotation/Reader2","lingwo_dictionary/layout/BottomDock","lingwo_dictionary/util/declare"],function(m,s,F,K){function I(w){var E=T[B.lang][w];return E?E:w}function z(w,E,O){var c;for(c in E)if(!O||typeof w[c]=="undefined")w[c]=E[c]}function C(w){var E=B.url.replace("<lang>",B.lang);if(w)return E+"/"+w;return E}function J(w){this.node=w;this.url=
m(w).attr("data-url")||B.getPageUrl();this.teaser=m(w).attr("data-teaser")=="true";this.links=m('<div class="bibliobird-links"></div>').insertBefore(w);this.data={};this.lookupContent()}var B={},v={url:"http://<lang>.bibliobird.com",lang:"en",showLinks:true,ga:true,pageUrlRemove:"#",getPageUrl:function(){var w=""+window.self.location.href;switch(B.pageUrlRemove){case "?":w=w.split("?")[0];case "#":w=w.split("#")[0]}return w}},M={en:"English",pl:"Polski"},T={en:{}},Z;T.pl={"Translate to":"T\u0142umacz na",
"Words I Am Learning":"M\u00f3j osobisty s\u0142owniczek",Hello:"Cze\u015b\u0107",Login:"Zaloguj si\u0119",or:"lub",register:"utw\u00f3rz konto","on BiblioBird":"w systemie BiblioBird","not me!":"to nie ja!"};Z=K({_constructor:function(){this.innerNode=m('<div id="bibliobird-dock" class="clear-block"></div>').get(0);this.node=m("<div></div>").css("zIndex","101").append(this.innerNode).get(0);this.userNode=m("<div></div>").css({"float":"left","padding-left":10}).get(0);this._rebuild();this._layout=
new F({node:this.node,size:35});this._layout.layout()},_rebuild:function(){var w,E,O,c=this;this.innerNode.innerHTML="";E=m('<select id="bibliobird-language-switcher"></select>').get(0);for(w in M){O=m("<option>"+M[w]+"</option>");O.attr("value",w);w==B.lang&&O.attr("selected","selected");m(E).append(O)}m(E).bind("change",function(){B.lang=m("option:selected",E).val();c._rebuild()});w=m('<a id="bibliobird-wial-button"></a>').css({display:"block","float":"right",background:"transparent url('http://en.bibliobird.com/sites/all/themes/lingwoorg_theme/images/join-btn-left.png') left no-repeat",
"padding-left":11,height:27,"margin-left":10,"margin-top":2,color:"white","font-size":"12px","font-weight":"bold","text-decoration":"none",cursor:"pointer"}).attr({href:C("wial"),target:"_blank"}).append(m("<span></span>").css({display:"block","float":"left",background:"transparent url('http://en.bibliobird.com/sites/all/themes/lingwoorg_theme/images/join-btn-right.png') right no-repeat","padding-right":14,height:27,cursor:"pointer"}).append(m("<span></span>").css({display:"block","float":"left",
background:"transparent url('http://en.bibliobird.com/sites/all/themes/lingwoorg_theme/images/join-btn-middle.png') center repeat-x","padding-top":4,height:23,cursor:"pointer"}).text(I("Words I Am Learning"))));m(this.innerNode).css({height:"100%",background:"#e5e5f9","border-top":"1px solid black","font-size":"14pt"}).append(m("<div>BiblioBird</div>").css({"float":"left",background:"#07104C","font-weight":"bold",height:"100%",color:"white","font-size":"16pt",padding:"0 10px","border-right":"1px solid white"})).append(this.userNode).append(m("<div></div>").css({"float":"right",
"padding-right":"10px"}).append('<label for="bibliobird-language-switcher">'+I("Translate to")+": </label>").append(E).append(w));this.rebuildLinks()},rebuildLinks:function(){var w=m(this.userNode);m("#bibliobird-wial-button",this.node)[B.username?"show":"hide"]();w.html("");if(B.username){w.append(I("Hello")+", "+B.username+"!  (");w.append(m("<a></a>").html(I("not me!")).attr("href",C("logout")).click(function(){B.logout();return false}));w.append(")")}else{w.append(I("Hello")+"!  ");w.append(m("<a></a>").html(I("Login")).attr("href",
C("remote/login")+(B.localRelayUrl?"?relay="+B.localRelayUrl:"")).click(function(E){B.openEmbedWindow(E.target.href);return false}));w.append(" "+I("or")+" ");w.append(m("<a></a>").html(I("register")).attr({href:C("user/register"),target:"_blank"}));w.append(" "+I("on BiblioBird")+".")}}});if(typeof window.BiblioBird!="undefined")B=window.BiblioBird;z(B,v,true);z(B,{initialized:false,contentAreas:[],embedWindow:null,embedIframe:null,embedWindowShown:false,username:null,isRemoteIframe:false,bottomDock:null,
hasContent:false,start:function(){window.self!==window.top&&window.self.location.hash&&this._readHashOptions();m(".bibliobird-content").each(function(){B.contentAreas.push(new J(this))})},_readHashOptions:function(){var w=(""+window.self.location.hash).split("&"),E={},O,c;for(O=0;O<w.length;O++){c=w[O].split("=");E[c[0]]=c[1]}if(E["#iam"]=="bibliobird")this.isRemoteIframe=true},initialize:function(w,E){function O(){var V=(m(window).width()-400)/2,$=(m(window).height()-200)/2;c.css({top:$,left:V})}
if(!this.hasContent&&E){if(!this.isRemoteIframe)this.bottomDock=new Z;this.hasContent=E}if(!this.initialized){var c=m('<div class="clear-block"><div class="bibliobird-embed-titlebar"><span class="bibliobird-embed-title">BiblioBird</span> <a href="#" class="bibliobird-embed-close">close</a></div></div>');E=m('<iframe height="100%" width="100%" border="0" id="bibliobirdEmbedIframe" name="bibliobirdEmbedIframe"></iframe>').appendTo(c);c.css({width:400,height:200,position:"fixed",border:"1px solid black",
background:"white",display:"none"}).appendTo(m("body"));m(".bibliobird-embed-close",c).click(function(){B.hideEmbedWindow();return false});m(window).resize(O);setTimeout(O,0);s.setup({layout:"popup",skipHoverEvents:true});m("body").click(function(V){B.hideEmbedWindow();return s.handleClick(V.target)});z(this,{embedWindow:c,embedIframe:E,username:w,initialized:true})}},receiveMessage:function(w){if(w.indexOf("#login-successful")==0){w=w.split(":");if(w[1])this.username=w[1];this.hideEmbedWindow()}},
openEmbedWindow:function(w){if(this.embedWindow!==null&&!this.embedWindowShown){this.embedIframe.attr("src",w);this.embedWindow.show();this.embedWindowShown=true}},hideEmbedWindow:function(){if(this.embedWindow!==null&&this.embedWindowShown){this.embedWindow.hide();this.embedWindowShown=false;this.refreshAll()}},logout:function(){var w=this;m.ajax({url:C("remote/logout"),dataType:"jsonp",success:function(){w.username=null;w.refreshAll()}})},refreshAll:function(){m.each(this.contentAreas,function(){this.refresh()});
this.bottomDock&&this.bottomDock.rebuildLinks()}});s.onLoad=function(w){w=(w.attr("data-entry")||"").split("#");var E=w[0],O=w[1];s.setBubbleLoading();m.ajax({url:C("embed-reader/lookup_entry"),dataType:"jsonp",data:{hash:E,lang:B.lang},success:function(c){s.setBubbleContent(c.content);B.ga&&typeof window._gaq!="undefined"&&_gaq.push(["_trackEvent","BiblioBird","Anonymous Lookup",B.lang]);m(".node",s.contentNode).removeClass("clear-block").removeAttr("id");m("ul.links.inline",s.contentNode).remove();
O&&m(".lingwo-sense-id-"+O,s.contentNode).addClass("selected");m("a",s.contentNode).each(function(V,$){V=$.href;var t;if(V){t=window.self.location.protocol+"//"+window.self.location.host;$.href=V.replace(t,C());$.target="_blank"}})}})};z(J.prototype,{lookupContent:function(){var w=this;m.ajax({url:C("embed-reader/lookup_content"),dataType:"jsonp",data:{url:this.url},success:function(E){B.initialize(E.username,!!E.content);w.data=E;w.rebuildLinks();if(E.content){w.node.innerHTML=E.content;s.setupHoverEvents()}}})},
rebuildLinks:function(){if(B.showLinks){var w=this.links,E=this.data;w.html("");E.not_found&&w.append(m("<a></a>").html("Add to Bibliobird").attr({href:C("node/add/content?remote_url="+escape(this.url)),target:"_blank"}))}},refresh:function(){this.rebuildLinks()}});return window.BiblioBird=B});(function(m,s){function F(){if(!c.isReady){try{t.documentElement.doScroll("left")}catch(a){setTimeout(F,1);return}c.ready()}}function K(a,b){b.src?c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||
b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}function I(a,b,d,f,e,i){var j=a.length;if(typeof b==="object"){for(var p in b)I(a,p,b[p],f,e,d);return a}if(d!==s){f=!i&&f&&c.isFunction(d);for(p=0;p<j;p++)e(a[p],b,f?d.call(a[p],p,e(a[p],b)):d,i);return a}return j?e(a[0],b):s}function z(){return(new Date).getTime()}function C(){return false}function J(){return true}function B(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function v(a){var b,d=[],f=[],e=arguments,i,j,
p,k,o,u;j=c.data(this,"events");if(!(a.liveFired===this||!j||!j.live||a.button&&a.type==="click")){a.liveFired=this;var y=j.live.slice(0);for(k=0;k<y.length;k++){j=y[k];j.origType.replace(ea,"")===a.type?f.push(j.selector):y.splice(k--,1)}i=c(a.target).closest(f,a.currentTarget);o=0;for(u=i.length;o<u;o++)for(k=0;k<y.length;k++){j=y[k];if(i[o].selector===j.selector){p=i[o].elem;f=null;if(j.preType==="mouseenter"||j.preType==="mouseleave")f=c(a.relatedTarget).closest(j.selector)[0];if(!f||f!==p)d.push({elem:p,
handleObj:j})}}o=0;for(u=d.length;o<u;o++){i=d[o];a.currentTarget=i.elem;a.data=i.handleObj.data;a.handleObj=i.handleObj;if(i.handleObj.origHandler.apply(i.elem,e)===false){b=false;break}}return b}}function M(a,b){return"live."+(a&&a!=="*"?a+".":"")+b.replace(/\./g,"`").replace(/ /g,"&")}function T(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function Z(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var f=c.data(a[d++]),e=c.data(this,f);if(f=f&&f.events){delete e.handle;
e.events={};for(var i in f)for(var j in f[i])c.event.add(this,i,f[i][j],f[i][j].data)}}})}function w(a,b,d){var f,e,i;b=b&&b[0]?b[0].ownerDocument||b[0]:t;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===t&&!Aa.test(a[0])&&(c.support.checkClone||!Ba.test(a[0]))){e=true;if(i=c.fragments[a[0]])if(i!==1)f=i}if(!f){f=b.createDocumentFragment();c.clean(a,b,f,d)}if(e)c.fragments[a[0]]=i?f:1;return{fragment:f,cacheable:e}}function E(a,b){var d={};c.each(Ca.concat.apply([],Ca.slice(0,b)),function(){d[this]=
a});return d}function O(a){return"scrollTo"in a&&a.document?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var c=function(a,b){return new c.fn.init(a,b)},V=m.jQuery,$=m.$,t=m.document,ia,Xa=/^[^<]*(<[\w\W]+>)[^>]*$|^#([\w-]+)$/,Ya=/^.[^:#\[\.,]*$/,Za=/\S/,$a=/^(\s|\u00A0)+|(\s|\u00A0)+$/g,ab=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,fa=navigator.userAgent,Da=false,aa=[],ma=!!(typeof S!=="undefined"&&S.def),ba,na=Object.prototype.toString,oa=Object.prototype.hasOwnProperty,pa=Array.prototype.push,ga=Array.prototype.slice,
Ea=Array.prototype.indexOf;c.fn=c.prototype={init:function(a,b){var d,f;if(!a)return this;if(a.nodeType){this.context=this[0]=a;this.length=1;return this}if(a==="body"&&!b){this.context=t;this[0]=t.body;this.selector="body";this.length=1;return this}if(typeof a==="string")if((d=Xa.exec(a))&&(d[1]||!b))if(d[1]){f=b?b.ownerDocument||b:t;if(a=ab.exec(a))if(c.isPlainObject(b)){a=[t.createElement(a[1])];c.fn.attr.call(a,b,true)}else a=[f.createElement(a[1])];else{a=w([d[1]],[f]);a=(a.cacheable?a.fragment.cloneNode(true):
a.fragment).childNodes}return c.merge(this,a)}else{if(b=t.getElementById(d[2])){if(b.id!==d[2])return ia.find(a);this.length=1;this[0]=b}this.context=t;this.selector=a;return this}else if(!b&&/^\w+$/.test(a)){this.selector=a;this.context=t;a=t.getElementsByTagName(a);return c.merge(this,a)}else return!b||b.jquery?(b||ia).find(a):c(b).find(a);else if(c.isFunction(a))return ia.ready(a);if(a.selector!==s){this.selector=a.selector;this.context=a.context}return c.makeArray(a,this)},selector:"",jquery:"1.4.2",
length:0,size:function(){return this.length},toArray:function(){return ga.call(this,0)},get:function(a){return a==null?this.toArray():a<0?this.slice(a)[0]:this[a]},pushStack:function(a,b,d){var f=c();c.isArray(a)?pa.apply(f,a):c.merge(f,a);f.prevObject=this;f.context=this.context;if(b==="find")f.selector=this.selector+(this.selector?" ":"")+d;else if(b)f.selector=this.selector+"."+b+"("+d+")";return f},each:function(a,b){return c.each(this,a,b)},ready:function(a){c.bindReady();if(c.isReady&&(!ma||
S.s.isDone))a.call(t,c);else{aa||(aa=[]);aa.push(a)}return this},eq:function(a){return a===-1?this.slice(a):this.slice(a,+a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(ga.apply(this,arguments),"slice",ga.call(arguments).join(","))},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},end:function(){return this.prevObject||c(null)},push:pa,sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;
c.extend=c.fn.extend=function(){var a=arguments[0]||{},b=1,d=arguments.length,f=false,e,i,j,p;if(typeof a==="boolean"){f=a;a=arguments[1]||{};b=2}if(typeof a!=="object"&&!c.isFunction(a))a={};if(d===b){a=this;--b}for(;b<d;b++)if((e=arguments[b])!=null)for(i in e){j=a[i];p=e[i];if(a!==p)if(f&&p&&(c.isPlainObject(p)||c.isArray(p))){j=j&&(c.isPlainObject(j)||c.isArray(j))?j:c.isArray(p)?[]:{};a[i]=c.extend(f,j,p)}else if(p!==s)a[i]=p}return a};c.extend({noConflict:function(a){m.$=$;if(a)m.jQuery=V;return c},
isReady:false,ready:function(){if(!c.isReady){if(!t.body)return setTimeout(c.ready,13);c.isReady=true;c.callReady()}},callReady:function(){if(c.isReady&&(!ma||S.s.isDone)){if(aa){for(var a,b=0;a=aa[b++];)a.call(t,c);aa=null}c.fn.triggerHandler&&c(t).triggerHandler("ready")}},bindReady:function(){if(!Da){Da=true;if(t.readyState==="complete")return c.ready();if(t.addEventListener){t.addEventListener("DOMContentLoaded",ba,false);m.addEventListener("load",c.ready,false)}else if(t.attachEvent){t.attachEvent("onreadystatechange",
ba);m.attachEvent("onload",c.ready);var a=false;try{a=m.frameElement==null}catch(b){}t.documentElement.doScroll&&a&&F()}}},isFunction:function(a){return na.call(a)==="[object Function]"},isArray:function(a){return na.call(a)==="[object Array]"},isPlainObject:function(a){if(!a||na.call(a)!=="[object Object]"||a.nodeType||a.setInterval)return false;if(a.constructor&&!oa.call(a,"constructor")&&!oa.call(a.constructor.prototype,"isPrototypeOf"))return false;var b;for(b in a);return b===s||oa.call(a,b)},
isEmptyObject:function(a){for(var b in a)return false;return true},error:function(a){throw a;},parseJSON:function(a){if(typeof a!=="string"||!a)return null;a=c.trim(a);if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return m.JSON&&m.JSON.parse?m.JSON.parse(a):(new Function("return "+a))();else c.error("Invalid JSON: "+a)},noop:function(){},globalEval:function(a){if(a&&
Za.test(a)){var b=t.getElementsByTagName("head")[0]||t.documentElement,d=t.createElement("script");d.type="text/javascript";if(c.support.scriptEval)d.appendChild(t.createTextNode(a));else d.text=a;b.insertBefore(d,b.firstChild);b.removeChild(d)}},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===b.toUpperCase()},each:function(a,b,d){var f,e=0,i=a.length,j=i===s||c.isFunction(a);if(d)if(j)for(f in a){if(b.apply(a[f],d)===false)break}else for(;e<i;){if(b.apply(a[e++],d)===false)break}else if(j)for(f in a){if(b.call(a[f],
f,a[f])===false)break}else for(d=a[0];e<i&&b.call(d,e,d)!==false;d=a[++e]);return a},trim:function(a){return(a||"").replace($a,"")},makeArray:function(a,b){b=b||[];if(a!=null)a.length==null||typeof a==="string"||c.isFunction(a)||typeof a!=="function"&&a.setInterval?pa.call(b,a):c.merge(b,a);return b},inArray:function(a,b){if(b.indexOf)return b.indexOf(a);for(var d=0,f=b.length;d<f;d++)if(b[d]===a)return d;return-1},merge:function(a,b){var d=a.length,f=0;if(typeof b.length==="number")for(var e=b.length;f<
e;f++)a[d++]=b[f];else for(;b[f]!==s;)a[d++]=b[f++];a.length=d;return a},grep:function(a,b,d){for(var f=[],e=0,i=a.length;e<i;e++)!d!==!b(a[e],e)&&f.push(a[e]);return f},map:function(a,b,d){for(var f=[],e,i=0,j=a.length;i<j;i++){e=b(a[i],i,d);if(e!=null)f[f.length]=e}return f.concat.apply([],f)},guid:1,proxy:function(a,b,d){if(arguments.length===2)if(typeof b==="string"){d=a;a=d[b];b=s}else if(b&&!c.isFunction(b)){d=b;b=s}if(!b&&a)b=function(){return a.apply(d||this,arguments)};if(a)b.guid=a.guid=
a.guid||b.guid||c.guid++;return b},uaMatch:function(a){a=a.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||!/compatible/.test(a)&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},browser:{}});fa=c.uaMatch(fa);if(fa.browser){c.browser[fa.browser]=true;c.browser.version=fa.version}if(c.browser.webkit)c.browser.safari=true;if(Ea)c.inArray=function(a,b){return Ea.call(b,a)};ia=c(t);if(t.addEventListener)ba=
function(){t.removeEventListener("DOMContentLoaded",ba,false);c.ready()};else if(t.attachEvent)ba=function(){if(t.readyState==="complete"){t.detachEvent("onreadystatechange",ba);c.ready()}};(function(){c.support={};var a=t.documentElement,b=t.createElement("script"),d=t.createElement("div"),f="script"+z();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var e=d.getElementsByTagName("*"),i=d.getElementsByTagName("a")[0];
if(!(!e||!e.length||!i)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(i.getAttribute("style")),hrefNormalized:i.getAttribute("href")==="/a",opacity:/^0.55$/.test(i.style.opacity),cssFloat:!!i.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:t.createElement("select").appendChild(t.createElement("option")).selected,parentNode:d.removeChild(d.appendChild(t.createElement("div"))).parentNode===
null,deleteExpando:true,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null};b.type="text/javascript";try{b.appendChild(t.createTextNode("window."+f+"=1;"))}catch(j){}a.insertBefore(b,a.firstChild);if(m[f]){c.support.scriptEval=true;delete m[f]}try{delete b.test}catch(p){c.support.deleteExpando=false}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function k(){c.support.noCloneEvent=false;d.detachEvent("onclick",k)});d.cloneNode(true).fireEvent("onclick")}d=t.createElement("div");
d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";a=t.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var k=t.createElement("div");k.style.width=k.style.paddingLeft="1px";t.body.appendChild(k);c.boxModel=c.support.boxModel=k.offsetWidth===2;t.body.removeChild(k).style.display="none"});a=function(k){var o=t.createElement("div");k="on"+k;var u=k in o;if(!u){o.setAttribute(k,"return;");u=typeof o[k]===
"function"}return u};c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=e=i=null}})();c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",frameborder:"frameBorder"};var W="jQuery"+z(),bb=0,Fa={};c.extend({cache:{},expando:W,noData:{embed:true,object:true,applet:true},data:function(a,b,d){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=
a==m?Fa:a;var f=a[W],e=c.cache;if(!f&&typeof b==="string"&&d===s)return null;f||(f=++bb);if(typeof b==="object"){a[W]=f;e[f]=c.extend(true,{},b)}else if(!e[f]){a[W]=f;e[f]={}}a=e[f];if(d!==s)a[b]=d;return typeof b==="string"?a[b]:a}},removeData:function(a,b){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=a==m?Fa:a;var d=a[W],f=c.cache,e=f[d];if(b){if(e){delete e[b];c.isEmptyObject(e)&&c.removeData(a)}}else{if(c.support.deleteExpando)delete a[c.expando];else a.removeAttribute&&a.removeAttribute(c.expando);
delete f[d]}}}});c.fn.extend({data:function(a,b){if(typeof a==="undefined"&&this.length)return c.data(this[0]);else if(typeof a==="object")return this.each(function(){c.data(this,a)});var d=a.split(".");d[1]=d[1]?"."+d[1]:"";if(b===s){var f=this.triggerHandler("getData"+d[1]+"!",[d[0]]);if(f===s&&this.length)f=c.data(this[0],a);return f===s&&d[1]?this.data(d[0]):f}else return this.trigger("setData"+d[1]+"!",[d[0],b]).each(function(){c.data(this,a,b)})},removeData:function(a){return this.each(function(){c.removeData(this,
a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var f=c.data(a,b);if(!d)return f||[];if(!f||c.isArray(d))f=c.data(a,b,c.makeArray(d));else f.push(d);return f}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),f=d.shift();if(f==="inprogress")f=d.shift();if(f){b==="fx"&&d.unshift("inprogress");f.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===s)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,
a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||"fx",[])}});var Ga=/[\n\t]/g,qa=/\s+/,cb=/\r/g,db=/href|src|style/,eb=/(button|input)/i,fb=/(button|input|object|select|textarea)/i,gb=/^(a|area)$/i,Ha=/radio|checkbox/;c.fn.extend({attr:function(a,
b){return I(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(o){var u=c(this);u.addClass(a.call(this,o,u.attr("class")))});if(a&&typeof a==="string")for(var b=(a||"").split(qa),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===1)if(e.className){for(var i=" "+e.className+" ",j=e.className,p=0,k=b.length;p<k;p++)if(i.indexOf(" "+b[p]+" ")<
0)j+=" "+b[p];e.className=c.trim(j)}else e.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(k){var o=c(this);o.removeClass(a.call(this,k,o.attr("class")))});if(a&&typeof a==="string"||a===s)for(var b=(a||"").split(qa),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===1&&e.className)if(a){for(var i=(" "+e.className+" ").replace(Ga," "),j=0,p=b.length;j<p;j++)i=i.replace(" "+b[j]+" "," ");e.className=c.trim(i)}else e.className=""}return this},toggleClass:function(a,
b){var d=typeof a,f=typeof b==="boolean";if(c.isFunction(a))return this.each(function(e){var i=c(this);i.toggleClass(a.call(this,e,i.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var e,i=0,j=c(this),p=b,k=a.split(qa);e=k[i++];){p=f?p:!j.hasClass(e);j[p?"addClass":"removeClass"](e)}else if(d==="undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=this.className||a===false?"":c.data(this,"__className__")||""}})},hasClass:function(a){a=
" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(Ga," ").indexOf(a)>-1)return true;return false},val:function(a){if(a===s){var b=this[0];if(b){if(c.nodeName(b,"option"))return(b.attributes.value||{}).specified?b.value:b.text;if(c.nodeName(b,"select")){var d=b.selectedIndex,f=[],e=b.options;b=b.type==="select-one";if(d<0)return null;var i=b?d:0;for(d=b?d+1:e.length;i<d;i++){var j=e[i];if(j.selected){a=c(j).val();if(b)return a;f.push(a)}}return f}if(Ha.test(b.type)&&
!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace(cb,"")}return s}var p=c.isFunction(a);return this.each(function(k){var o=c(this),u=a;if(this.nodeType===1){if(p)u=a.call(this,k,o.val());if(typeof u==="number")u+="";if(c.isArray(u)&&Ha.test(this.type))this.checked=c.inArray(o.val(),u)>=0;else if(c.nodeName(this,"select")){var y=c.makeArray(u);c("option",this).each(function(){this.selected=c.inArray(c(this).val(),y)>=0});if(!y.length)this.selectedIndex=
-1}else this.value=u}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,f){if(!a||a.nodeType===3||a.nodeType===8)return s;if(f&&b in c.attrFn)return c(a)[b](d);f=a.nodeType!==1||!c.isXMLDoc(a);var e=d!==s;b=f&&c.props[b]||b;if(a.nodeType===1){var i=db.test(b);if(b in a&&f&&!i){if(e){b==="type"&&eb.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;
if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:fb.test(a.nodeName)||gb.test(a.nodeName)&&a.href?0:s;return a[b]}if(!c.support.style&&f&&b==="style"){if(e)a.style.cssText=""+d;return a.style.cssText}e&&a.setAttribute(b,""+d);a=!c.support.hrefNormalized&&f&&i?a.getAttribute(b,2):a.getAttribute(b);return a===null?s:a}return c.style(a,b,d)}});var ea=/\.(.*)$/,hb=function(a){return a.replace(/[^\w\s\.\|`]/g,function(b){return"\\"+b})};c.event={add:function(a,b,d,f){if(!(a.nodeType===
3||a.nodeType===8)){if(a.setInterval&&a!==m&&!a.frameElement)a=m;var e,i;if(d.handler){e=d;d=e.handler}if(!d.guid)d.guid=c.guid++;if(i=c.data(a)){var j=i.events=i.events||{},p=i.handle;if(!p)i.handle=p=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(p.elem,arguments):s};p.elem=a;b=b.split(" ");for(var k,o=0,u;k=b[o++];){i=e?c.extend({},e):{handler:d,data:f};if(k.indexOf(".")>-1){u=k.split(".");k=u.shift();i.namespace=u.slice(0).sort().join(".")}else{u=[];i.namespace=
""}i.type=k;i.guid=d.guid;var y=j[k],H=c.event.special[k]||{};if(!y){y=j[k]=[];if(!H.setup||H.setup.call(a,f,u,p)===false)if(a.addEventListener)a.addEventListener(k,p,false);else a.attachEvent&&a.attachEvent("on"+k,p)}if(H.add){H.add.call(a,i);if(!i.handler.guid)i.handler.guid=d.guid}y.push(i);c.event.global[k]=true}a=null}}},global:{},remove:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){var e,i=0,j,p,k,o,u,y,H=c.data(a),N=H&&H.events;if(H&&N){if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b===
"string"&&b.charAt(0)==="."){b=b||"";for(e in N)c.event.remove(a,e+b)}else{for(b=b.split(" ");e=b[i++];){o=e;j=e.indexOf(".")<0;p=[];if(!j){p=e.split(".");e=p.shift();k=new RegExp("(^|\\.)"+c.map(p.slice(0).sort(),hb).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(u=N[e])if(d){o=c.event.special[e]||{};for(L=f||0;L<u.length;L++){y=u[L];if(d.guid===y.guid){if(j||k.test(y.namespace)){f==null&&u.splice(L--,1);o.remove&&o.remove.call(a,y)}if(f!=null)break}}if(u.length===0||f!=null&&u.length===1){if(!o.teardown||
o.teardown.call(a,p)===false)Ia(a,e,H.handle);delete N[e]}}else for(var L=0;L<u.length;L++){y=u[L];if(j||k.test(y.namespace)){c.event.remove(a,o,y.handler,L);u.splice(L--,1)}}}if(c.isEmptyObject(N)){if(b=H.handle)b.elem=null;delete H.events;delete H.handle;c.isEmptyObject(H)&&c.removeData(a)}}}}},trigger:function(a,b,d,f){var e=a.type||a;if(!f){a=typeof a==="object"?a[W]?a:c.extend(c.Event(e),a):c.Event(e);if(e.indexOf("!")>=0){a.type=e=e.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[e]&&
c.each(c.cache,function(){this.events&&this.events[e]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return s;a.result=s;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(f=c.data(d,"handle"))&&f.apply(d,b);f=d.parentNode||d.ownerDocument;try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+e]&&d["on"+e].apply(d,b)===false)a.result=false}catch(i){}if(!a.isPropagationStopped()&&f)c.event.trigger(a,b,f,true);else if(!a.isDefaultPrevented()){f=
a.target;var j,p=c.nodeName(f,"a")&&e==="click",k=c.event.special[e]||{};if((!k._default||k._default.call(d,a)===false)&&!p&&!(f&&f.nodeName&&c.noData[f.nodeName.toLowerCase()])){try{if(f[e]){if(j=f["on"+e])f["on"+e]=null;c.event.triggered=true;f[e]()}}catch(o){}if(j)f["on"+e]=j;c.event.triggered=false}}},handle:function(a){var b,d,f,e;a=arguments[0]=c.event.fix(a||m.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;if(!b){d=a.type.split(".");a.type=d.shift();f=new RegExp("(^|\\.)"+
d.slice(0).sort().join("\\.(?:.*\\.)?")+"(\\.|$)")}e=c.data(this,"events");d=e[a.type];if(e&&d){d=d.slice(0);e=0;for(var i=d.length;e<i;e++){var j=d[e];if(b||f.test(j.namespace)){a.handler=j.handler;a.data=j.data;a.handleObj=j;j=j.handler.apply(this,arguments);if(j!==s){a.result=j;if(j===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY originalTarget pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),
fix:function(a){if(a[W])return a;var b=a;a=c.Event(b);for(var d=this.props.length,f;d;){f=this.props[--d];a[f]=b[f]}if(!a.target)a.target=a.srcElement||t;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=t.documentElement;d=t.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||
d&&d.scrollTop||0)-(b&&b.clientTop||d&&d.clientTop||0)}if(!a.which&&(a.charCode||a.charCode===0?a.charCode:a.keyCode))a.which=a.charCode||a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==s)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,a.origType,c.extend({},a,{handler:v}))},remove:function(a){var b=true,d=a.origType.replace(ea,"");c.each(c.data(this,
"events").live||[],function(){if(d===this.origType.replace(ea,""))return b=false});b&&c.event.remove(this,a.origType,v)}},beforeunload:{setup:function(a,b,d){if(this.setInterval)this.onbeforeunload=d;return false},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};var Ia=t.removeEventListener?function(a,b,d){a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=
a;this.type=a.type}else this.type=a;this.timeStamp=z();this[W]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=J;var a=this.originalEvent;if(a){a.preventDefault&&a.preventDefault();a.returnValue=false}},stopPropagation:function(){this.isPropagationStopped=J;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=J;this.stopPropagation()},isDefaultPrevented:C,isPropagationStopped:C,
isImmediatePropagationStopped:C};var Ja=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},Ka=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?Ka:Ja,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?Ka:Ja)}}});if(!c.support.submitBubbles)c.event.special.submit=
{setup:function(){if(this.nodeName.toLowerCase()!=="form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length)return B("submit",this,arguments)});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13)return B("submit",this,arguments)})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var ra=
/textarea|input|select/i,sa,La=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(f){return f.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},ta=function(a,b){var d=a.target,f,e;if(!(!ra.test(d.nodeName)||d.readOnly)){f=c.data(d,"_change_data");e=La(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",e);if(!(f===s||e===f))if(f!=null||
e){a.type="change";return c.event.trigger(a,b,d)}}};c.event.special.change={filters:{focusout:ta,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return ta.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return ta.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",La(a))}},setup:function(){if(this.type===
"file")return false;for(var a in sa)c.event.add(this,a+".specialChange",sa[a]);return ra.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return ra.test(this.nodeName)}};sa=c.event.special.change.filters}t.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(f){f=c.event.fix(f);f.type=b;return c.event.handle.call(this,f)}c.event.special[b]={setup:function(){this.addEventListener(a,d,true)},teardown:function(){this.removeEventListener(a,
d,true)}}});c.each(["bind","one"],function(a,b){c.fn[b]=function(d,f,e){if(typeof d==="object"){for(var i in d)this[b](i,f,d[i],e);return this}if(c.isFunction(f)){e=f;f=s}var j=b==="one"?c.proxy(e,function(k){c(this).unbind(k,j);return e.apply(this,arguments)}):e;if(d==="unload"&&b!=="one")this.one(d,f,e);else{i=0;for(var p=this.length;i<p;i++)c.event.add(this[i],d,j,f)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,a[d]);else{d=
0;for(var f=this.length;d<f;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,f){return this.live(b,d,f,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<b.length;)c.proxy(a,
b[d++]);return this.click(c.proxy(a,function(f){var e=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,e+1);f.preventDefault();return b[e].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var Ma={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,f,e,i){var j,p=0,k,o,u=i||this.selector,y=i?this:c(this.context);if(c.isFunction(f)){e=f;f=s}for(d=
(d||"").split(" ");(j=d[p++])!=null;){i=ea.exec(j);k="";if(i){k=i[0];j=j.replace(ea,"")}if(j==="hover")d.push("mouseenter"+k,"mouseleave"+k);else{o=j;if(j==="focus"||j==="blur"){d.push(Ma[j]+k);j+=k}else j=(Ma[j]||j)+k;b==="live"?y.each(function(){c.event.add(this,M(j,u),{data:f,selector:u,handler:e,origType:j,origHandler:e,preType:o})}):y.unbind(M(j,u),e)}}return this}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),
function(a,b){c.fn[b]=function(d){return d?this.bind(b,d):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});m.attachEvent&&!m.addEventListener&&m.attachEvent("onunload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});(function(){function a(g){for(var h="",l,n=0;g[n];n++){l=g[n];if(l.nodeType===3||l.nodeType===4)h+=l.nodeValue;else if(l.nodeType!==8)h+=a(l.childNodes)}return h}function b(g,h,l,n,r,q){r=0;for(var A=n.length;r<A;r++){var x=n[r];
if(x){x=x[g];for(var G=false;x;){if(x.sizcache===l){G=n[x.sizset];break}if(x.nodeType===1&&!q){x.sizcache=l;x.sizset=r}if(x.nodeName.toLowerCase()===h){G=x;break}x=x[g]}n[r]=G}}}function d(g,h,l,n,r,q){r=0;for(var A=n.length;r<A;r++){var x=n[r];if(x){x=x[g];for(var G=false;x;){if(x.sizcache===l){G=n[x.sizset];break}if(x.nodeType===1){if(!q){x.sizcache=l;x.sizset=r}if(typeof h!=="string"){if(x===h){G=true;break}}else if(k.filter(h,[x]).length>0){G=x;break}}x=x[g]}n[r]=G}}}var f=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^[\]]*\]|['"][^'"]*['"]|[^[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,
e=0,i=Object.prototype.toString,j=false,p=true;[0,0].sort(function(){p=false;return 0});var k=function(g,h,l,n){l=l||[];var r=h=h||t;if(h.nodeType!==1&&h.nodeType!==9)return[];if(!g||typeof g!=="string")return l;for(var q=[],A,x,G,ha,X=true,ca=D(h),Y=g;(f.exec(""),A=f.exec(Y))!==null;){Y=A[3];q.push(A[1]);if(A[2]){ha=A[3];break}}if(q.length>1&&u.exec(g))if(q.length===2&&o.relative[q[0]])x=ua(q[0]+q[1],h);else for(x=o.relative[q[0]]?[h]:k(q.shift(),h);q.length;){g=q.shift();if(o.relative[g])g+=q.shift();
x=ua(g,x)}else{if(!n&&q.length>1&&h.nodeType===9&&!ca&&o.match.ID.test(q[0])&&!o.match.ID.test(q[q.length-1])){A=k.find(q.shift(),h,ca);h=A.expr?k.filter(A.expr,A.set)[0]:A.set[0]}if(h){A=n?{expr:q.pop(),set:H(n)}:k.find(q.pop(),q.length===1&&(q[0]==="~"||q[0]==="+")&&h.parentNode?h.parentNode:h,ca);x=A.expr?k.filter(A.expr,A.set):A.set;if(q.length>0)G=H(x);else X=false;for(;q.length;){var P=q.pop();A=P;if(o.relative[P])A=q.pop();else P="";if(A==null)A=h;o.relative[P](G,A,ca)}}else G=[]}G||(G=x);
G||k.error(P||g);if(i.call(G)==="[object Array]")if(X)if(h&&h.nodeType===1)for(g=0;G[g]!=null;g++){if(G[g]&&(G[g]===true||G[g].nodeType===1&&Q(h,G[g])))l.push(x[g])}else for(g=0;G[g]!=null;g++)G[g]&&G[g].nodeType===1&&l.push(x[g]);else l.push.apply(l,G);else H(G,l);if(ha){k(ha,r,l,n);k.uniqueSort(l)}return l};k.uniqueSort=function(g){if(L){j=p;g.sort(L);if(j)for(var h=1;h<g.length;h++)g[h]===g[h-1]&&g.splice(h--,1)}return g};k.matches=function(g,h){return k(g,null,null,h)};k.find=function(g,h,l){var n,
r;if(!g)return[];for(var q=0,A=o.order.length;q<A;q++){var x=o.order[q];if(r=o.leftMatch[x].exec(g)){var G=r[1];r.splice(1,1);if(G.substr(G.length-1)!=="\\"){r[1]=(r[1]||"").replace(/\\/g,"");n=o.find[x](r,h,l);if(n!=null){g=g.replace(o.match[x],"");break}}}}n||(n=h.getElementsByTagName("*"));return{set:n,expr:g}};k.filter=function(g,h,l,n){for(var r=g,q=[],A=h,x,G,ha=h&&h[0]&&D(h[0]);g&&h.length;){for(var X in o.filter)if((x=o.leftMatch[X].exec(g))!=null&&x[2]){var ca=o.filter[X],Y,P;P=x[1];G=false;
x.splice(1,1);if(P.substr(P.length-1)!=="\\"){if(A===q)q=[];if(o.preFilter[X])if(x=o.preFilter[X](x,A,l,q,n,ha)){if(x===true)continue}else G=Y=true;if(x)for(var ja=0;(P=A[ja])!=null;ja++)if(P){Y=ca(P,x,ja,A);var Na=n^!!Y;if(l&&Y!=null)if(Na)G=true;else A[ja]=false;else if(Na){q.push(P);G=true}}if(Y!==s){l||(A=q);g=g.replace(o.match[X],"");if(!G)return[];break}}}if(g===r)if(G==null)k.error(g);else break;r=g}return A};k.error=function(g){throw"Syntax error, unrecognized expression: "+g;};var o=k.selectors=
{order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},
attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")}},relative:{"+":function(g,h){var l=typeof h==="string",n=l&&!/\W/.test(h);l=l&&!n;if(n)h=h.toLowerCase();n=0;for(var r=g.length,q;n<r;n++)if(q=g[n]){for(;(q=q.previousSibling)&&q.nodeType!==1;);g[n]=l||q&&q.nodeName.toLowerCase()===h?q||false:q===h}l&&k.filter(h,g,true)},">":function(g,h){var l=typeof h==="string";if(l&&!/\W/.test(h)){h=h.toLowerCase();for(var n=0,r=g.length;n<r;n++){var q=g[n];
if(q){l=q.parentNode;g[n]=l.nodeName.toLowerCase()===h?l:false}}}else{n=0;for(r=g.length;n<r;n++)if(q=g[n])g[n]=l?q.parentNode:q.parentNode===h;l&&k.filter(h,g,true)}},"":function(g,h,l){var n=e++,r=d;if(typeof h==="string"&&!/\W/.test(h)){var q=h=h.toLowerCase();r=b}r("parentNode",h,n,g,q,l)},"~":function(g,h,l){var n=e++,r=d;if(typeof h==="string"&&!/\W/.test(h)){var q=h=h.toLowerCase();r=b}r("previousSibling",h,n,g,q,l)}},find:{ID:function(g,h,l){if(typeof h.getElementById!=="undefined"&&!l)return(g=
h.getElementById(g[1]))?[g]:[]},NAME:function(g,h){if(typeof h.getElementsByName!=="undefined"){var l=[];h=h.getElementsByName(g[1]);for(var n=0,r=h.length;n<r;n++)h[n].getAttribute("name")===g[1]&&l.push(h[n]);return l.length===0?null:l}},TAG:function(g,h){return h.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,h,l,n,r,q){g=" "+g[1].replace(/\\/g,"")+" ";if(q)return g;q=0;for(var A;(A=h[q])!=null;q++)if(A)if(r^(A.className&&(" "+A.className+" ").replace(/[\t\n]/g," ").indexOf(g)>=0))l||
n.push(A);else if(l)h[q]=false;return false},ID:function(g){return g[1].replace(/\\/g,"")},TAG:function(g){return g[1].toLowerCase()},CHILD:function(g){if(g[1]==="nth"){var h=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&"0n+"+g[2]||g[2]);g[2]=h[1]+(h[2]||1)-0;g[3]=h[3]-0}g[0]=e++;return g},ATTR:function(g,h,l,n,r,q){h=g[1].replace(/\\/g,"");if(!q&&o.attrMap[h])g[1]=o.attrMap[h];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,h,l,n,r){if(g[1]===
"not")if((f.exec(g[3])||"").length>1||/^\w/.test(g[3]))g[3]=k(g[3],null,null,h);else{g=k.filter(g[3],h,l,true^r);l||n.push.apply(n,g);return false}else if(o.match.POS.test(g[0])||o.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},
empty:function(g){return!g.firstChild},has:function(g,h,l){return!!k(l[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===
g.type||g.nodeName.toLowerCase()==="button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)}},setFilters:{first:function(g,h){return h===0},last:function(g,h,l,n){return h===n.length-1},even:function(g,h){return h%2===0},odd:function(g,h){return h%2===1},lt:function(g,h,l){return h<l[3]-0},gt:function(g,h,l){return h>l[3]-0},nth:function(g,h,l){return l[3]-0===h},eq:function(g,h,l){return l[3]-0===h}},filter:{PSEUDO:function(g,h,l,n){var r=h[1],q=o.filters[r];if(q)return q(g,
l,h,n);else if(r==="contains")return(g.textContent||g.innerText||a([g])||"").indexOf(h[3])>=0;else if(r==="not"){h=h[3];l=0;for(n=h.length;l<n;l++)if(h[l]===g)return false;return true}else k.error("Syntax error, unrecognized expression: "+r)},CHILD:function(g,h){var l=h[1],n=g;switch(l){case "only":case "first":for(;n=n.previousSibling;)if(n.nodeType===1)return false;if(l==="first")return true;n=g;case "last":for(;n=n.nextSibling;)if(n.nodeType===1)return false;return true;case "nth":l=h[2];var r=
h[3];if(l===1&&r===0)return true;h=h[0];var q=g.parentNode;if(q&&(q.sizcache!==h||!g.nodeIndex)){var A=0;for(n=q.firstChild;n;n=n.nextSibling)if(n.nodeType===1)n.nodeIndex=++A;q.sizcache=h}g=g.nodeIndex-r;return l===0?g===0:g%l===0&&g/l>=0}},ID:function(g,h){return g.nodeType===1&&g.getAttribute("id")===h},TAG:function(g,h){return h==="*"&&g.nodeType===1||g.nodeName.toLowerCase()===h},CLASS:function(g,h){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(h)>-1},ATTR:function(g,h){var l=
h[1];g=o.attrHandle[l]?o.attrHandle[l](g):g[l]!=null?g[l]:g.getAttribute(l);l=g+"";var n=h[2];h=h[4];return g==null?n==="!=":n==="="?l===h:n==="*="?l.indexOf(h)>=0:n==="~="?(" "+l+" ").indexOf(h)>=0:!h?l&&g!==false:n==="!="?l!==h:n==="^="?l.indexOf(h)===0:n==="$="?l.substr(l.length-h.length)===h:n==="|="?l===h||l.substr(0,h.length+1)===h+"-":false},POS:function(g,h,l,n){var r=o.setFilters[h[2]];if(r)return r(g,l,h,n)}}},u=o.match.POS;for(var y in o.match){o.match[y]=new RegExp(o.match[y].source+/(?![^\[]*\])(?![^\(]*\))/.source);
o.leftMatch[y]=new RegExp(/(^(?:.|\r|\n)*?)/.source+o.match[y].source.replace(/\\(\d+)/g,function(g,h){return"\\"+(h-0+1)}))}var H=function(g,h){g=Array.prototype.slice.call(g,0);if(h){h.push.apply(h,g);return h}return g};try{Array.prototype.slice.call(t.documentElement.childNodes,0)}catch(N){H=function(g,h){h=h||[];if(i.call(g)==="[object Array]")Array.prototype.push.apply(h,g);else if(typeof g.length==="number")for(var l=0,n=g.length;l<n;l++)h.push(g[l]);else for(l=0;g[l];l++)h.push(g[l]);return h}}var L;
if(t.documentElement.compareDocumentPosition)L=function(g,h){if(!g.compareDocumentPosition||!h.compareDocumentPosition){if(g==h)j=true;return g.compareDocumentPosition?-1:1}g=g.compareDocumentPosition(h)&4?-1:g===h?0:1;if(g===0)j=true;return g};else if("sourceIndex"in t.documentElement)L=function(g,h){if(!g.sourceIndex||!h.sourceIndex){if(g==h)j=true;return g.sourceIndex?-1:1}g=g.sourceIndex-h.sourceIndex;if(g===0)j=true;return g};else if(t.createRange)L=function(g,h){if(!g.ownerDocument||!h.ownerDocument){if(g==
h)j=true;return g.ownerDocument?-1:1}var l=g.ownerDocument.createRange(),n=h.ownerDocument.createRange();l.setStart(g,0);l.setEnd(g,0);n.setStart(h,0);n.setEnd(h,0);g=l.compareBoundaryPoints(Range.START_TO_END,n);if(g===0)j=true;return g};(function(){var g=t.createElement("div"),h="script"+(new Date).getTime();g.innerHTML="<a name='"+h+"'/>";var l=t.documentElement;l.insertBefore(g,l.firstChild);if(t.getElementById(h)){o.find.ID=function(n,r,q){if(typeof r.getElementById!=="undefined"&&!q)return(r=
r.getElementById(n[1]))?r.id===n[1]||typeof r.getAttributeNode!=="undefined"&&r.getAttributeNode("id").nodeValue===n[1]?[r]:s:[]};o.filter.ID=function(n,r){var q=typeof n.getAttributeNode!=="undefined"&&n.getAttributeNode("id");return n.nodeType===1&&q&&q.nodeValue===r}}l.removeChild(g);l=g=null})();(function(){var g=t.createElement("div");g.appendChild(t.createComment(""));if(g.getElementsByTagName("*").length>0)o.find.TAG=function(h,l){l=l.getElementsByTagName(h[1]);if(h[1]==="*"){h=[];for(var n=
0;l[n];n++)l[n].nodeType===1&&h.push(l[n]);l=h}return l};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!=="undefined"&&g.firstChild.getAttribute("href")!=="#")o.attrHandle.href=function(h){return h.getAttribute("href",2)};g=null})();t.querySelectorAll&&function(){var g=k,h=t.createElement("div");h.innerHTML="<p class='TEST'></p>";if(!(h.querySelectorAll&&h.querySelectorAll(".TEST").length===0)){k=function(n,r,q,A){r=r||t;if(!A&&r.nodeType===9&&!D(r))try{return H(r.querySelectorAll(n),
q)}catch(x){}return g(n,r,q,A)};for(var l in g)k[l]=g[l];h=null}}();(function(){var g=t.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){o.order.splice(1,0,"CLASS");o.find.CLASS=function(h,l,n){if(typeof l.getElementsByClassName!=="undefined"&&!n)return l.getElementsByClassName(h[1])};g=null}}})();var Q=t.compareDocumentPosition?
function(g,h){return!!(g.compareDocumentPosition(h)&16)}:function(g,h){return g!==h&&(g.contains?g.contains(h):true)},D=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false},ua=function(g,h){var l=[],n="",r;for(h=h.nodeType?[h]:h;r=o.match.PSEUDO.exec(g);){n+=r[0];g=g.replace(o.match.PSEUDO,"")}g=o.relative[g]?g+"*":g;r=0;for(var q=h.length;r<q;r++)k(g,h[r],l);return k.filter(n,l)};c.find=k;c.expr=k.selectors;c.expr[":"]=c.expr.filters;c.unique=k.uniqueSort;c.text=
a;c.isXMLDoc=D;c.contains=Q})();var ib=/Until$/,jb=/^(?:parents|prevUntil|prevAll)/,kb=/,/;ga=Array.prototype.slice;var Oa=function(a,b,d){if(c.isFunction(b))return c.grep(a,function(e,i){return!!b.call(e,i,e)===d});else if(b.nodeType)return c.grep(a,function(e){return e===b===d});else if(typeof b==="string"){var f=c.grep(a,function(e){return e.nodeType===1});if(Ya.test(b))return c.filter(b,f,!d);else b=c.filter(b,f)}return c.grep(a,function(e){return c.inArray(e,b)>=0===d})};c.fn.extend({find:function(a){for(var b=
this.pushStack("","find",a),d=0,f=0,e=this.length;f<e;f++){d=b.length;c.find(a,this[f],b);if(f>0)for(var i=d;i<b.length;i++)for(var j=0;j<d;j++)if(b[j]===b[i]){b.splice(i--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,f=b.length;d<f;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(Oa(this,a,false),"not",a)},filter:function(a){return this.pushStack(Oa(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>
0},closest:function(a,b){if(c.isArray(a)){var d=[],f=this[0],e,i={},j;if(f&&a.length){e=0;for(var p=a.length;e<p;e++){j=a[e];i[j]||(i[j]=c.expr.match.POS.test(j)?c(j,b||this.context):j)}for(;f&&f.ownerDocument&&f!==b;){for(j in i){e=i[j];if(e.jquery?e.index(f)>-1:c(f).is(e)){d.push({selector:j,elem:f});delete i[j]}}f=f.parentNode}}return d}var k=c.expr.match.POS.test(a)?c(a,b||this.context):null;return this.map(function(o,u){for(;u&&u.ownerDocument&&u!==b;){if(k?k.index(u)>-1:c(u).is(a))return u;
u=u.parentNode}return null})},index:function(a){if(!a||typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(T(a[0])||T(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},
parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},
contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,f){var e=c.map(this,b,d);ib.test(a)||(f=d);if(f&&typeof f==="string")e=c.filter(f,e);e=this.length>1?c.unique(e):e;if((this.length>1||kb.test(f))&&jb.test(a))e=e.reverse();return this.pushStack(e,a,ga.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return c.find.matches(a,b)},dir:function(a,b,d){var f=[];for(a=
a[b];a&&a.nodeType!==9&&(d===s||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&f.push(a);a=a[b]}return f},nth:function(a,b,d){b=b||1;for(var f=0;a;a=a[d])if(a.nodeType===1&&++f===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Pa=/ jQuery\d+="(?:\d+|null)"/g,ka=/^\s+/,Qa=/(<([\w:]+)[^>]*?)\/>/g,lb=/^(?:area|br|col|embed|hr|img|input|link|meta|param)$/i,Ra=/<([\w:]+)/,mb=/<tbody/i,nb=/<|&#?\w+;/,Aa=/<script|<object|<embed|<option|<style/i,
Ba=/checked\s*(?:[^=]|=\s*.checked.)/i,Sa=function(a,b,d){return lb.test(d)?a:b+"></"+d+">"},R={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};R.optgroup=R.option;R.tbody=R.tfoot=R.colgroup=R.caption=R.thead;R.th=R.td;if(!c.support.htmlSerialize)R._default=
[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==s)return this.empty().append((this[0]&&this[0].ownerDocument||t).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=
this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,
true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,
false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,f;(f=this[d])!=null;d++)if(!a||c.filter(a,[f]).length){if(!b&&f.nodeType===1){c.cleanData(f.getElementsByTagName("*"));c.cleanData([f])}f.parentNode&&f.parentNode.removeChild(f)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);
return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,f=this.ownerDocument;if(!d){d=f.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(Pa,"").replace(/=([^="'>\s]+\/)>/g,'="$1">').replace(ka,"")],f)[0]}else return this.cloneNode(true)});if(a===true){Z(this,b);Z(this.find("*"),b.find("*"))}return b},html:function(a){if(a===s)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(Pa,
""):null;else if(typeof a==="string"&&!Aa.test(a)&&(c.support.leadingWhitespace||!ka.test(a))&&!R[(Ra.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Qa,Sa);try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(f){this.empty().append(a)}}else c.isFunction(a)?this.each(function(e){var i=c(this),j=i.html();i.empty().append(function(){return a.call(this,e,j)})}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&
this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),f=d.html();d.replaceWith(a.call(this,b,f))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){function f(y){return c.nodeName(y,"table")?y.getElementsByTagName("tbody")[0]||
y.appendChild(y.ownerDocument.createElement("tbody")):y}var e,i,j=a[0],p=[],k;if(!c.support.checkClone&&arguments.length===3&&typeof j==="string"&&Ba.test(j))return this.each(function(){c(this).domManip(a,b,d,true)});if(c.isFunction(j))return this.each(function(y){var H=c(this);a[0]=j.call(this,y,b?H.html():s);H.domManip(a,b,d)});if(this[0]){e=j&&j.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:w(a,this,p);k=e.fragment;if(i=k.childNodes.length===
1?(k=k.firstChild):k.firstChild){b=b&&c.nodeName(i,"tr");for(var o=0,u=this.length;o<u;o++)d.call(b?f(this[o],i):this[o],o>0||e.cacheable||this.length>1?k.cloneNode(true):k)}p.length&&c.each(p,K)}return this}});c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var f=[];d=c(d);var e=this.length===1&&this[0].parentNode;if(e&&e.nodeType===11&&e.childNodes.length===1&&d.length===1){d[b](this[0]);
return this}else{e=0;for(var i=d.length;e<i;e++){var j=(e>0?this.clone(true):this).get();c.fn[b].apply(c(d[e]),j);f=f.concat(j)}return this.pushStack(f,a,d.selector)}}});c.extend({clean:function(a,b,d,f){b=b||t;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||t;for(var e=[],i=0,j;(j=a[i])!=null;i++){if(typeof j==="number")j+="";if(j){if(typeof j==="string"&&!nb.test(j))j=b.createTextNode(j);else if(typeof j==="string"){j=j.replace(Qa,Sa);var p=(Ra.exec(j)||["",
""])[1].toLowerCase(),k=R[p]||R._default,o=k[0],u=b.createElement("div");for(u.innerHTML=k[1]+j+k[2];o--;)u=u.lastChild;if(!c.support.tbody){o=mb.test(j);p=p==="table"&&!o?u.firstChild&&u.firstChild.childNodes:k[1]==="<table>"&&!o?u.childNodes:[];for(k=p.length-1;k>=0;--k)c.nodeName(p[k],"tbody")&&!p[k].childNodes.length&&p[k].parentNode.removeChild(p[k])}!c.support.leadingWhitespace&&ka.test(j)&&u.insertBefore(b.createTextNode(ka.exec(j)[0]),u.firstChild);j=u.childNodes}if(j.nodeType)e.push(j);else e=
c.merge(e,j)}}if(d)for(i=0;e[i];i++)if(f&&c.nodeName(e[i],"script")&&(!e[i].type||e[i].type.toLowerCase()==="text/javascript"))f.push(e[i].parentNode?e[i].parentNode.removeChild(e[i]):e[i]);else{e[i].nodeType===1&&e.splice.apply(e,[i+1,0].concat(c.makeArray(e[i].getElementsByTagName("script"))));d.appendChild(e[i])}return e},cleanData:function(a){for(var b,d,f=c.cache,e=c.event.special,i=c.support.deleteExpando,j=0,p;(p=a[j])!=null;j++)if(d=p[c.expando]){b=f[d];if(b.events)for(var k in b.events)e[k]?
c.event.remove(p,k):Ia(p,k,b.handle);if(i)delete p[c.expando];else p.removeAttribute&&p.removeAttribute(c.expando);delete f[d]}}});var ob=/z-?index|font-?weight|opacity|zoom|line-?height/i,Ta=/alpha\([^)]*\)/,Ua=/opacity=([^)]*)/,va=/float/i,wa=/-([a-z])/ig,pb=/([A-Z])/g,qb=/^-?\d+(?:px)?$/i,rb=/^-?\d/,sb={position:"absolute",visibility:"hidden",display:"block"},tb=["Left","Right"],ub=["Top","Bottom"],vb=t.defaultView&&t.defaultView.getComputedStyle,Va=c.support.cssFloat?"cssFloat":"styleFloat",xa=
function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){return I(this,a,b,true,function(d,f,e){if(e===s)return c.curCSS(d,f);if(typeof e==="number"&&!ob.test(f))e+="px";c.style(d,f,e)})};c.extend({style:function(a,b,d){if(!a||a.nodeType===3||a.nodeType===8)return s;if((b==="width"||b==="height")&&parseFloat(d)<0)d=s;var f=a.style||a,e=d!==s;if(!c.support.opacity&&b==="opacity"){if(e){f.zoom=1;b=parseInt(d,10)+""==="NaN"?"":"alpha(opacity="+d*100+")";a=f.filter||c.curCSS(a,"filter")||"";f.filter=
Ta.test(a)?a.replace(Ta,b):b}return f.filter&&f.filter.indexOf("opacity=")>=0?parseFloat(Ua.exec(f.filter)[1])/100+"":""}if(va.test(b))b=Va;b=b.replace(wa,xa);if(e)f[b]=d;return f[b]},css:function(a,b,d,f){if(b==="width"||b==="height"){var e,i=b==="width"?tb:ub;d=function(){e=b==="width"?a.offsetWidth:a.offsetHeight;f!=="border"&&c.each(i,function(){f||(e-=parseFloat(c.curCSS(a,"padding"+this,true))||0);if(f==="margin")e+=parseFloat(c.curCSS(a,"margin"+this,true))||0;else e-=parseFloat(c.curCSS(a,
"border"+this+"Width",true))||0})};a.offsetWidth!==0?d():c.swap(a,sb,d);return Math.max(0,Math.round(e))}return c.curCSS(a,b,d)},curCSS:function(a,b,d){var f,e=a.style;if(!c.support.opacity&&b==="opacity"&&a.currentStyle){f=Ua.test(a.currentStyle.filter||"")?parseFloat(RegExp.$1)/100+"":"";return f===""?"1":f}if(va.test(b))b=Va;if(!d&&e&&e[b])f=e[b];else if(vb){if(va.test(b))b="float";b=b.replace(pb,"-$1").toLowerCase();e=a.ownerDocument.defaultView;if(!e)return null;if(a=e.getComputedStyle(a,null))f=
a.getPropertyValue(b);if(b==="opacity"&&f==="")f="1"}else if(a.currentStyle){d=b.replace(wa,xa);f=a.currentStyle[b]||a.currentStyle[d];if(!qb.test(f)&&rb.test(f)){b=e.left;var i=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;e.left=d==="fontSize"?"1em":f||0;f=e.pixelLeft+"px";e.left=b;a.runtimeStyle.left=i}}return f},swap:function(a,b,d){var f={};for(var e in b){f[e]=a.style[e];a.style[e]=b[e]}d.call(a);for(e in b)a.style[e]=f[e]}});if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=
a.offsetWidth,d=a.offsetHeight,f=a.nodeName.toLowerCase()==="tr";return b===0&&d===0&&!f?true:b>0&&d>0&&!f?false:c.curCSS(a,"display")==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var wb=z(),xb=/<script(.|\s)*?\/script>/gi,yb=/select|textarea/i,zb=/color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week/i,da=/=\?(&|$)/,ya=/\?/,Ab=/(\?|&)_=.*?(&|$)/,Bb=/^(\w+:)?\/\/([^\/?#]+)/,Cb=/%20/g,Db=c.fn.load;c.fn.extend({load:function(a,b,
d){if(typeof a!=="string")return Db.call(this,a);else if(!this.length)return this;var f=a.indexOf(" ");if(f>=0){var e=a.slice(f,a.length);a=a.slice(0,f)}f="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);f="POST"}var i=this;c.ajax({url:a,type:f,dataType:"html",data:b,complete:function(j,p){if(p==="success"||p==="notmodified")i.html(e?c("<div />").append(j.responseText.replace(xb,"")).find(e):j.responseText);d&&i.each(d,[j.responseText,
p,j])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||yb.test(this.nodeName)||zb.test(this.type))}).map(function(a,b){a=c(this).val();return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),
function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:f})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b={}}return c.ajax({type:"POST",url:a,data:b,success:d,dataType:f})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,
global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:m.XMLHttpRequest&&(m.location.protocol!=="file:"||!m.ActiveXObject)?function(){return new m.XMLHttpRequest}:function(){try{return new m.ActiveXObject("Microsoft.XMLHTTP")}catch(a){}},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},lastModified:{},etag:{},ajax:function(a){function b(){e.success&&
e.success.call(k,p,j,D);e.global&&f("ajaxSuccess",[D,e])}function d(){e.complete&&e.complete.call(k,D,j);e.global&&f("ajaxComplete",[D,e]);e.global&&!--c.active&&c.event.trigger("ajaxStop")}function f(r,q){(e.context?c(e.context):c.event).trigger(r,q)}var e=c.extend(true,{},c.ajaxSettings,a),i,j,p,k=a&&a.context||e,o=e.type.toUpperCase();if(e.data&&e.processData&&typeof e.data!=="string")e.data=c.param(e.data,e.traditional);if(e.dataType==="jsonp"){if(o==="GET")da.test(e.url)||(e.url+=(ya.test(e.url)?
"&":"?")+(e.jsonp||"callback")+"=?");else if(!e.data||!da.test(e.data))e.data=(e.data?e.data+"&":"")+(e.jsonp||"callback")+"=?";e.dataType="json"}if(e.dataType==="json"&&(e.data&&da.test(e.data)||da.test(e.url))){i=e.jsonpCallback||"jsonp"+wb++;if(e.data)e.data=(e.data+"").replace(da,"="+i+"$1");e.url=e.url.replace(da,"="+i+"$1");e.dataType="script";m[i]=m[i]||function(r){p=r;b();d();m[i]=s;try{delete m[i]}catch(q){}H&&H.removeChild(N)}}if(e.dataType==="script"&&e.cache===null)e.cache=false;if(e.cache===
false&&o==="GET"){var u=z(),y=e.url.replace(Ab,"$1_="+u+"$2");e.url=y+(y===e.url?(ya.test(e.url)?"&":"?")+"_="+u:"")}if(e.data&&o==="GET")e.url+=(ya.test(e.url)?"&":"?")+e.data;e.global&&!c.active++&&c.event.trigger("ajaxStart");u=(u=Bb.exec(e.url))&&(u[1]&&u[1]!==location.protocol||u[2]!==location.host);if(e.dataType==="script"&&o==="GET"&&u){var H=t.getElementsByTagName("head")[0]||t.documentElement,N=t.createElement("script");N.src=e.url;if(e.scriptCharset)N.charset=e.scriptCharset;if(!i){var L=
false;N.onload=N.onreadystatechange=function(){if(!L&&(!this.readyState||this.readyState==="loaded"||this.readyState==="complete")){L=true;b();d();N.onload=N.onreadystatechange=null;H&&N.parentNode&&H.removeChild(N)}}}H.insertBefore(N,H.firstChild);return s}var Q=false,D=e.xhr();if(D){e.username?D.open(o,e.url,e.async,e.username,e.password):D.open(o,e.url,e.async);try{if(e.data||a&&a.contentType)D.setRequestHeader("Content-Type",e.contentType);if(e.ifModified){c.lastModified[e.url]&&D.setRequestHeader("If-Modified-Since",
c.lastModified[e.url]);c.etag[e.url]&&D.setRequestHeader("If-None-Match",c.etag[e.url])}u||D.setRequestHeader("X-Requested-With","XMLHttpRequest");D.setRequestHeader("Accept",e.dataType&&e.accepts[e.dataType]?e.accepts[e.dataType]+", */*":e.accepts._default)}catch(ua){}if(e.beforeSend&&e.beforeSend.call(k,D,e)===false){e.global&&!--c.active&&c.event.trigger("ajaxStop");D.abort();return false}e.global&&f("ajaxSend",[D,e]);var g=D.onreadystatechange=function(r){if(!D||D.readyState===0||r==="abort"){Q||
d();Q=true;if(D)D.onreadystatechange=c.noop}else if(!Q&&D&&(D.readyState===4||r==="timeout")){Q=true;D.onreadystatechange=c.noop;j=r==="timeout"?"timeout":!c.httpSuccess(D)?"error":e.ifModified&&c.httpNotModified(D,e.url)?"notmodified":"success";var q;if(j==="success")try{p=c.httpData(D,e.dataType,e)}catch(A){j="parsererror";q=A}if(j==="success"||j==="notmodified")i||b();else c.handleError(e,D,j,q);d();r==="timeout"&&D.abort();if(e.async)D=null}};try{var h=D.abort;D.abort=function(){D&&h.call(D);
g("abort")}}catch(l){}e.async&&e.timeout>0&&setTimeout(function(){D&&!Q&&g("timeout")},e.timeout);try{D.send(o==="POST"||o==="PUT"||o==="DELETE"?e.data:null)}catch(n){c.handleError(e,D,null,n);d()}e.async||g();return D}},handleError:function(a,b,d,f){if(a.error)a.error.call(a.context||a,b,d,f);if(a.global)(a.context?c(a.context):c.event).trigger("ajaxError",[b,a,f])},active:0,httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===
1223||a.status===0}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),f=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(f)c.etag[b]=f;return a.status===304||a.status===0},httpData:function(a,b,d){var f=a.getResponseHeader("content-type")||"",e=b==="xml"||!b&&f.indexOf("xml")>=0;a=e?a.responseXML:a.responseText;e&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b===
"json"||!b&&f.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&f.indexOf("javascript")>=0)c.globalEval(a);return a},param:function(a,b){function d(j,p){if(c.isArray(p))c.each(p,function(k,o){b||/\[\]$/.test(j)?f(j,o):d(j+"["+(typeof o==="object"||c.isArray(o)?k:"")+"]",o)});else!b&&p!=null&&typeof p==="object"?c.each(p,function(k,o){d(j+"["+k+"]",o)}):f(j,p)}function f(j,p){p=c.isFunction(p)?p():p;e[e.length]=encodeURIComponent(j)+"="+encodeURIComponent(p)}var e=[];if(b===s)b=c.ajaxSettings.traditional;
if(c.isArray(a)||a.jquery)c.each(a,function(){f(this.name,this.value)});else for(var i in a)d(i,a[i]);return e.join("&").replace(Cb,"+")}});var za={},Eb=/toggle|show|hide/,Fb=/^([+-]=)?([\d+-.]+)(.*)$/,la,Ca=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]];c.fn.extend({show:function(a,b){if(a||a===0)return this.animate(E("show",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");
this[a].style.display=d||"";if(c.css(this[a],"display")==="none"){d=this[a].nodeName;var f;if(za[d])f=za[d];else{var e=c("<"+d+" />").appendTo("body");f=e.css("display");if(f==="none")f="block";e.remove();za[d]=f}c.data(this[a],"olddisplay",f)}}a=0;for(b=this.length;a<b;a++)this[a].style.display=c.data(this[a],"olddisplay")||"";return this}},hide:function(a,b){if(a||a===0)return this.animate(E("hide",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");!d&&d!=="none"&&c.data(this[a],
"olddisplay",c.css(this[a],"display"))}a=0;for(b=this.length;a<b;a++)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b){var d=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,arguments);else a==null||d?this.each(function(){var f=d?a:c(this).is(":hidden");c(this)[f?"show":"hide"]()}):this.animate(E("toggle",3),a,b);return this},fadeTo:function(a,b,d){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d)},
animate:function(a,b,d,f){var e=c.speed(b,d,f);if(c.isEmptyObject(a))return this.each(e.complete);return this[e.queue===false?"each":"queue"](function(){var i=c.extend({},e),j,p=this.nodeType===1&&c(this).is(":hidden"),k=this;for(j in a){var o=j.replace(wa,xa);if(j!==o){a[o]=a[j];delete a[j];j=o}if(a[j]==="hide"&&p||a[j]==="show"&&!p)return i.complete.call(this);if((j==="height"||j==="width")&&this.style){i.display=c.css(this,"display");i.overflow=this.style.overflow}if(c.isArray(a[j])){(i.specialEasing=
i.specialEasing||{})[j]=a[j][1];a[j]=a[j][0]}}if(i.overflow!=null)this.style.overflow="hidden";i.curAnim=c.extend({},a);c.each(a,function(u,y){var H=new c.fx(k,i,u);if(Eb.test(y))H[y==="toggle"?p?"show":"hide":y](a);else{var N=Fb.exec(y),L=H.cur(true)||0;if(N){y=parseFloat(N[2]);var Q=N[3]||"px";if(Q!=="px"){k.style[u]=(y||1)+Q;L=(y||1)/H.cur(true)*L;k.style[u]=L+Q}if(N[1])y=(N[1]==="-="?-1:1)*y+L;H.custom(L,y,Q)}else H.custom(L,y,"")}});return true})},stop:function(a,b){var d=c.timers;a&&this.queue([]);
this.each(function(){for(var f=d.length-1;f>=0;f--)if(d[f].elem===this){b&&d[f](true);d.splice(f,1)}});b||this.dequeue();return this}});c.each({slideDown:E("show",1),slideUp:E("hide",1),slideToggle:E("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"}},function(a,b){c.fn[a]=function(d,f){return this.animate(b,d,f)}});c.extend({speed:function(a,b,d){var f=a&&typeof a==="object"?a:{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};f.duration=c.fx.off?0:typeof f.duration===
"number"?f.duration:c.fx.speeds[f.duration]||c.fx.speeds._default;f.old=f.complete;f.complete=function(){f.queue!==false&&c(this).dequeue();c.isFunction(f.old)&&f.old.call(this)};return f},easing:{linear:function(a,b,d,f){return d+f*a},swing:function(a,b,d,f){return(-Math.cos(a*Math.PI)/2+0.5)*f+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||
c.fx.step._default)(this);if((this.prop==="height"||this.prop==="width")&&this.elem.style)this.elem.style.display="block"},cur:function(a){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];return(a=parseFloat(c.css(this.elem,this.prop,a)))&&a>-10000?a:parseFloat(c.curCSS(this.elem,this.prop))||0},custom:function(a,b,d){function f(i){return e.step(i)}this.startTime=z();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;
this.pos=this.state=0;var e=this;f.elem=this.elem;if(f()&&c.timers.push(f)&&!la)la=setInterval(c.fx.tick,13)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=z(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=
this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=true;for(var f in this.options.curAnim)if(this.options.curAnim[f]!==true)d=false;if(d){if(this.options.display!=null){this.elem.style.overflow=this.options.overflow;a=c.data(this.elem,"olddisplay");this.elem.style.display=a?a:this.options.display;if(c.css(this.elem,"display")==="none")this.elem.style.display="block"}this.options.hide&&c(this.elem).hide();if(this.options.hide||this.options.show)for(var e in this.options.curAnim)c.style(this.elem,
e,this.options.orig[e]);this.options.complete.call(this.elem)}return false}else{e=b-this.startTime;this.state=e/this.options.duration;a=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||a](this.state,e,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||
c.fx.stop()},stop:function(){clearInterval(la);la=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};c.fn.offset="getBoundingClientRect"in
t.documentElement?function(a){var b=this[0];if(a)return this.each(function(e){c.offset.setOffset(this,a,e)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);var d=b.getBoundingClientRect(),f=b.ownerDocument;b=f.body;f=f.documentElement;return{top:d.top+(self.pageYOffset||c.support.boxModel&&f.scrollTop||b.scrollTop)-(f.clientTop||b.clientTop||0),left:d.left+(self.pageXOffset||c.support.boxModel&&f.scrollLeft||b.scrollLeft)-(f.clientLeft||b.clientLeft||
0)}}:function(a){var b=this[0];if(a)return this.each(function(u){c.offset.setOffset(this,a,u)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d=b.offsetParent,f=b,e=b.ownerDocument,i,j=e.documentElement,p=e.body;f=(e=e.defaultView)?e.getComputedStyle(b,null):b.currentStyle;for(var k=b.offsetTop,o=b.offsetLeft;(b=b.parentNode)&&b!==p&&b!==j;){if(c.offset.supportsFixedPosition&&f.position==="fixed")break;i=e?e.getComputedStyle(b,
null):b.currentStyle;k-=b.scrollTop;o-=b.scrollLeft;if(b===d){k+=b.offsetTop;o+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&/^t(able|d|h)$/i.test(b.nodeName))){k+=parseFloat(i.borderTopWidth)||0;o+=parseFloat(i.borderLeftWidth)||0}f=d;d=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&i.overflow!=="visible"){k+=parseFloat(i.borderTopWidth)||0;o+=parseFloat(i.borderLeftWidth)||0}f=i}if(f.position==="relative"||f.position==="static"){k+=p.offsetTop;
o+=p.offsetLeft}if(c.offset.supportsFixedPosition&&f.position==="fixed"){k+=Math.max(j.scrollTop,p.scrollTop);o+=Math.max(j.scrollLeft,p.scrollLeft)}return{top:k,left:o}};c.offset={initialize:function(){var a=t.body,b=t.createElement("div"),d,f,e,i=parseFloat(c.curCSS(a,"marginTop",true))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
a.insertBefore(b,a.firstChild);d=b.firstChild;f=d.firstChild;e=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=f.offsetTop!==5;this.doesAddBorderForTableAndCells=e.offsetTop===5;f.style.position="fixed";f.style.top="20px";this.supportsFixedPosition=f.offsetTop===20||f.offsetTop===15;f.style.position=f.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=f.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==i;a.removeChild(b);
c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=parseFloat(c.curCSS(a,"marginTop",true))||0;d+=parseFloat(c.curCSS(a,"marginLeft",true))||0}return{top:b,left:d}},setOffset:function(a,b,d){if(/static/.test(c.curCSS(a,"position")))a.style.position="relative";var f=c(a),e=f.offset(),i=parseInt(c.curCSS(a,"top",true),10)||0,j=parseInt(c.curCSS(a,"left",true),10)||0;if(c.isFunction(b))b=b.call(a,
d,e);d={top:b.top-e.top+i,left:b.left-e.left+j};"using"in b?b.using.call(a,d):f.css(d)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),f=/^body|html$/i.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.curCSS(a,"marginTop",true))||0;d.left-=parseFloat(c.curCSS(a,"marginLeft",true))||0;f.top+=parseFloat(c.curCSS(b[0],"borderTopWidth",true))||0;f.left+=parseFloat(c.curCSS(b[0],"borderLeftWidth",true))||0;return{top:d.top-
f.top,left:d.left-f.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||t.body;a&&!/^body|html$/i.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(f){var e=this[0],i;if(!e)return null;if(f!==s)return this.each(function(){if(i=O(this))i.scrollTo(!a?f:c(i).scrollLeft(),a?f:c(i).scrollTop());else this[d]=f});else return(i=O(e))?"pageXOffset"in i?i[a?"pageYOffset":"pageXOffset"]:
c.support.boxModel&&i.document.documentElement[d]||i.document.body[d]:e[d]}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?c.css(this[0],d,false,"padding"):null};c.fn["outer"+b]=function(f){return this[0]?c.css(this[0],d,false,f?"margin":"border"):null};c.fn[d]=function(f){var e=this[0];if(!e)return f==null?null:this;if(c.isFunction(f))return this.each(function(i){var j=c(this);j[d](f.call(this,i,j[d]()))});return"scrollTo"in e&&e.document?
e.document.compatMode==="CSS1Compat"&&e.document.documentElement["client"+b]||e.document.body["client"+b]:e.nodeType===9?Math.max(e.documentElement["client"+b],e.body["scroll"+b],e.documentElement["scroll"+b],e.body["offset"+b],e.documentElement["offset"+b]):f===s?c.css(e,d):this.css(d,typeof f==="string"?f:f+"px")}});if(ma){var Wa=S.callReady;S.callReady=function(){Wa&&Wa();c.callReady()};S.def("jquery",function(){return c});S.def("jQuery",function(){return c})}})(window);S(["bibliobird/Embed"],
function(m){m.start()})})();
