<?php

/**
 * Implementation of hook_strongarm()
 */
function lingwoorg_strongarm() {
  return array(
    // cheap translations
    'locale_custom_strings_en' => array(
      'Remember me' => 'Remember me!',
      'Access Denied / User Login' => 'User Login',
    ),

    // our theme settings
    'theme_default' => 'lingwoorg_theme',
    'admin_theme'   => 'rubik',
    'admin_theme_invalidated' => TRUE,

    // strongarm settings (set, ironically, with strongarm)
    //'strongarm_show_messages' => 0,

    // menus
    'menu_primary_links_source' => 'features',
    'menu_default_node_menu'    => 'navigation',
  );
}

