<?php
// $Id$

/**
 * @file
 * Customize login for our needs
 */

require_once('bbcom_login.features.inc');

/**
 * Implementation of hook_init().
 */
function bbcom_login_init() {
  global $user;

  $validating_id = logintoboggan_validating_id();
  // bail early if the $validating_id is set to a core id
  if (in_array($validating_id, array(DRUPAL_ANONYMOUS_RID, DRUPAL_AUTHENTICATED_RID)))
    return;

  // we show this message every time an unvalidated user visits a page that isn't user/%/edit 
  // or one of the magic toboggan pages.
  if (isset($user->roles[$validating_id]) && !(arg(0) == 'user' && (arg(2) == 'edit' || arg(1) == 'validate')) && arg(0) != 'toboggan') {
    // only show after the user has been a user for a moment
    if (time() - $user->created > 10) {
      drupal_set_message('<strong>'. t("You still haven't validated your account!") .'</strong>', 'error');
      drupal_set_message(t("A validation e-mail has been sent to your e-mail address. In order to gain full access to the site, you will need to follow the instructions in that message."));
      drupal_set_message(t("<a href=\"@user-edit\">Make sure</a> you entered the correct e-mail address or <a href=\"@resend-email\">re-send</a> the validation e-mail.", array('@user-edit' => url('user/'. $user->uid .'/edit'), '@resend-email' => url('toboggan/revalidate/'. $user->uid))));
    }
  }
}

/**
 * Implemantation of hook_menu_alter().
 */
function bbcom_login_menu_alter(&$items) {
  // Rename 'User Account' to user login
  $items['user']['title'] = t('User Login');
  // Move the 'Login' tab to the front
  $items['user/login']['weight'] = -10;
}

/**
 * Implementation of hook_url_outbound_alter().
 */
function bbcom_login_url_outbound_alter(&$path, &$options, $original) {
  if (user_is_anonymous() && in_array($original, array('user', 'user/register', 'user/login')) && empty($options['query'])) {
    $options['query'] = drupal_get_destination();
  }
}

/*
 * Implementation of hook_menu().
 */
function bbcom_login_menu() {
  $items = array();
  $items['user/edit'] = array(
    'title' => 'Edit my profile',
    'description' => 'Redirect to a user\'s edit page',
    'access callback' => 'user_is_logged_in',
    'page callback' => 'bbcom_login_user_edit_redirect_page',
    'type' => MENU_CALLBACK
  );
  return $items;
}

function bbcom_login_user_edit_redirect_page() {
  global $user;
  drupal_goto('user/'. $user->uid .'/edit');
}

/*
 * Implementation of hook_form_alter().
 */
function bbcom_login_form_alter(&$form, &$form_state, $form_id) {
  global $language;

  if ($form_id == 'user_register') {
    // honey pot field
    $form['url'] = array(
      '#title' => t('URL'),
      '#type' => 'textfield',
    );

    // user's language will be set to whatever the current language is
    $form['language'] = array(
      '#type' => 'hidden',
      '#value' => $language->language,
    );

    $form['#validate'][] = 'bbcom_login_user_register_validate';

    drupal_add_css(drupal_get_path('module', 'bbcom_login') .'/bbcom_login.css');
  }
}

function bbcom_login_user_register_validate($form, &$form_state) {
  # check our honey pot!
  if (!empty($form_state['values']['url'])) {
    form_set_error('url', t('Please leave the URL field blank.  It is there to catch bots!'));
  }

  # Check the user name.
  if ($error = bbcom_login_check_user_name($form_state['values']['name'])) {
    form_set_error('name', $error);
  }
}

function bbcom_login_check_user_name($name) {
  if (strlen($name) < 4 || strlen($name) > 15)
    return t('The username is too short. It must be more than 4 characters and less than 15 characters.');
  if (preg_match('/^[0-9]/u', $name))
    return t('The username cannot start with a number.');
  if (!preg_match('/^[a-zA-Z0-9_. ]+$/u', $name))
    return t('The username contains an illegal character. You can use only letters, digits, . and _ . Do not use any special characters.');
  if (substr($name, 0, 1) == '_')
    return t('The username cannot begin with "%char".', array('%char' => '_'));
  if (substr($name, -1) == '_')
    return t('The username cannot end with "%char".', array('%char' => '_'));
  if (substr($name, 0, 1) == '.')
    return t('The username cannot begin with "%char".', array('%char' => '.'));
  if (substr($name, -1) == '.')
    return t('The username cannot end with "%char".', array('%char' => '.'));
}

/*
 * Implements hook_fb().
 */
function bbcom_login_fb($op, $data=NULL, $return=NULL) {
  if ($op == 'post init') {
    // if there is no destination set, then we redirect to the front page!
    if (empty($_REQUEST['destination'])) {
      fb_js_settings('reload_url', url('<front>', array('absolute' => TRUE)));
    }
  }
}

