<?php

/**
 * Implementation of hook_service().
 */
function lingwoorg_device_service() {
  return array(
    array(
      '#method' => 'lingwoorg_device.get_content_item',
      '#callback' => 'lingwoorg_device_service_get_content_item',
      '#file' => array('file' => 'service.inc', 'module' => 'lingwoorg_device'),
      '#access arguments' => array('access content'),
      '#args' => array(
        array(
          '#name' => 'software_version',
          '#type' => 'string',
          '#description' => t('A string representing the device software version.'),
        ),
        array(
          '#name' => 'device_name',
          '#type' => 'string',
          '#description' => t('A string representing the device making the call.'),
        ),
        array(
          '#name' => 'id',
          '#type' => 'string',
          '#description' => t('The id of the content item'),
        ),
        array(
          '#name' => 'modified_since_revid',
          '#type' => 'string',
          '#optional' => TRUE,
          '#default_value' => '',
          '#description' => t('If passed, only return the item if has been updated since the given revid'),
        )
      ),
      '#return' => 'struct',
      '#help' => t('Returns an item of content'),
    ),
  );
}

