<?php

include_once('lingwoorg_content.features.inc');

/**
 * Implementation of hook_strongarm()
 */
function lingwoorg_content_strongarm() {
  return array(
    /*
     * 'content' content type
     */
    // translation settings
    'language_content_type_content' => 1,
    'i18n_node_content' => LANGUAGE_SUPPORT_NORMAL,

    // lingwo_korpus variables
    'lingwo_korpus_text_content_type' => 'content',

    // allow the <anno> tag in "Filtered HTML" (ID 1)
    'allowed_html_1' => "<a> <em> <strong> <cite> <code> <ul> <ol> <li> <dl> <dt> <dd> <word>",
  );
}

/**
 * Implementation of hook_block().
 */
function lingwoorg_content_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0] = array(
        'info' => t('Lingwo.org Content: Add Content Block'),
      );
      return $blocks;

    case 'view':
      if ($delta == 0 && user_access('create content content')) {
        $block['content'] = l('Create Content', 'node/add/content',
          array('attributes' => array('id' => 'create-content-link')));
        return $block;
      }
      break; 
  }
}


