<?php
// $Id$

/**
 * @file
 * Setup for the newsletter
 */

/*
 * Implementation of hook_user().
 */
function bbcom_news_user($op, &$edit, &$account, $category=NULL) {
  if ($op == 'register' || ($category == 'account' && $op == 'form')) {
    $optin = TRUE;
    if ($account->uid) {
      $optin = bbcom_news_is_optin($account);
    }
    $form['bbcom_news'] = array(
      '#type'  => 'fieldset',
      '#title' => t('Newsletter'),
    );
    $form['bbcom_news']['bbcom_news_optin'] = array(
      '#type' => 'checkbox',
      '#title' => t('Subscribe to the e-mail newsletter (1-2 e-mails per month)'),
      '#default_value' => $optin,
    );
    return $form;
  }

  switch ($op) {
    case 'insert':
      $optin = isset($edit['bbcom_news_optin']) ? $edit['bbcom_news_optin'] : TRUE;
      db_query("INSERT INTO {bbcom_news_users} (uid, optin) VALUES (%d, %d)", $account->uid, $optin);
      unset($edit['bbcom_news_optin']);
      break;

    case 'update':
      if (isset($edit['bbcom_news_optin'])) {
        db_query("UPDATE {bbcom_news_users} SET optin = %d WHERE uid = %d", $edit['bbcom_news_optin'], $account->uid);
        unset($edit['bbcom_news_optin']);
      }
      break;

    case 'delete':
      db_query("DELETE FROM {bbcom_news_users} WHERE uid = %d", $account->uid);
      break;
  }
}

function bbcom_news_is_optin($account) {
  if ($account->status) {
    $res = db_query("SELECT optin FROM {bbcom_news_users} WHERE uid = %d", $account->uid);
    if ($obj = db_fetch_object($res)) {
      return $obj->optin;
    }
  }
  return FALSE;
}

