<?php
// $Id$

/**
 * @file
 * Setup for the newsletter
 */

/**
 * Implementation of hook_menu().
 */
function bbcom_news_menu() {
  $items = array();
  $items['admin/settings/lingwo_dictionary/news'] = array(
    'title' => 'News',
    'description' => 'Settings for BiblioBird.com News module.',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bbcom_news_admin_settings'),
    'file' => 'bbcom_news.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/*
 * Implementation of hook_user().
 */
function bbcom_news_user($op, &$edit, &$account, $category=NULL) {
  if ($op == 'register' || ($category == 'account' && $op == 'form')) {
    $optin = TRUE;
    if ($account->uid) {
      $optin = bbcom_news_is_optin($account);
    }
    $form['bbcom_news'] = array(
      '#type'  => 'fieldset',
      '#title' => t('Newsletter'),
    );
    $form['bbcom_news']['bbcom_news_optin'] = array(
      '#type' => 'checkbox',
      '#title' => t('Subscribe to the e-mail newsletter (1-2 e-mails per month)'),
      '#default_value' => $optin,
    );
    return $form;
  }

  $optin = FALSE;
  switch ($op) {
    case 'insert':
      $optin = isset($edit['bbcom_news_optin']) ? $edit['bbcom_news_optin'] : TRUE;
      db_query("INSERT INTO {bbcom_news_users} (uid, optin) VALUES (%d, %d)", $account->uid, $optin);
      unset($edit['bbcom_news_optin']);
      break;

    case 'update':
      if (isset($edit['bbcom_news_optin'])) {
        $optin = $edit['bbcom_news_optin'];
        db_query("UPDATE {bbcom_news_users} SET optin = %d WHERE uid = %d", $optin, $account->uid);
        unset($edit['bbcom_news_optin']);
      }
      break;

    case 'delete':
      db_query("DELETE FROM {bbcom_news_users} WHERE uid = %d", $account->uid);
      break;
  }

  if (variable_get('bbcom_news_mailchimp_integration', FALSE)) {
    module_load('inc', 'bbcom_news', 'bbcom_news.mailchimp.inc');
    _bbcom_news_mailchimp_update($user, $optin);
  }
}

function bbcom_news_is_optin($account) {
  if ($account->status) {
    $res = db_query("SELECT optin FROM {bbcom_news_users} WHERE uid = %d", $account->uid);
    if ($obj = db_fetch_object($res)) {
      return $obj->optin;
    }
  }
  return FALSE;
}

