<?php

include_once('bbcom_marketing.features.inc');

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function bbcom_marketing_ctools_plugin_directory($module, $plugin) {
  if ($module == 'bbcom_marketing' && $plugin == 'block') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implementation of hook_block().
 */
function bbcom_marketing_block($op = 'list', $delta = 0, $edit = array()) {
  return ctools_block_handle_block($op, $delta, $edit, 'bbcom_marketing');
}

