<?php

require_once('bbcom_store.features.inc');

/**
 * Implementation of hook_init().
 *
 * Set the current country based on the current language.
 *
 */
function bbcom_store_init() {
  global $language;

  if (module_exists('uc_store') && module_exists('uc_multiprice')) {
    // kind of a hack where the country code equals the language code
    $countries = uc_get_country_data(array('country_iso_code_2' => $language->language));
    if (!empty($countries)) {
      uc_multiprice_country_id($countries[0]['country_id']);
    }
    else {
      uc_multiprice_country_id(uc_store_default_country());
    }
  }
}

/**
 * Implementation of hook_uc_get_message_alter().
 */
function bbcom_store_uc_get_message_alter(&$messages) {
  if (isset($messages['continue_shopping'])) {
    $messages['continue_shopping'] = '<strong>' . t('Please <a href="!url">visit the library</a> in order to start enjoying your content!', array('!url' => url('content'))) . '</strong>';
  }
}

/**
 * Implementation of hook_user().
 *
 * Autosubscribe users of particular roles to particular forums!
 *
 * TODO: This functionality could be turned into a forum_autosubscribe_role module,
 *       which adds checkboxes to the forum edit page about which roles to autosubscribe,
 *       and to automatically unsubscribe them too!
 *
 */
function bbcom_store_user($op, &$edit, &$account, $category = NULL) {
  if (!module_exists('bbcom_notifications')) {
    return;
  }

  // get variables to map roles to forums
  $roles = user_roles();
  $map = array();
  foreach ($roles as $rid => $role) {
    $tid = variable_get('bbcom_store_forum_' . str_replace('-', '_', $role), 0);
    if ($tid != 0) {
      $map[$rid] = $tid;
    }
  }

  if ($op == 'update' && $category == 'account') {
    /*
    drupal_set_message('account: ' . print_r($account->roles, TRUE));
    drupal_set_message('edit: ' . print_r($edit['roles'], TRUE));
    */

    foreach ($map as $rid => $tid) {
      if (empty($account->roles[$rid]) && !empty($edit['roles'][$rid])) {
        // subscribe the users to it!
        _bbcom_notifications_subscribe_to_forum($account, $tid, array(
          'send_method' => 'mail',
          'send_interval' => 0,
        ));
      }
      elseif (!empty($account->roles[$rid]) && empty($edit['roles'][$rid])) {
        // unsubscribe the user from it!
        $sub = array_shift(notifications_get_subscriptions(array('type' => 'taxonomy', 'uid' => $account->uid, 'tid' => $tid)));
        notifications_subscription_delete($sub);
      }
    }
  }
}

