<?php

/*
 * Implementation of hook_menu().
 */
function bbcom_misc_menu() {
  return array(
    'admin/settings/bbcom' => array(
      'title' => 'BiblioBird.com',
      'description' => 'Settings for BiblioBird.com',
      'access arguments' => array('administer site configuration'),
      'page callback' => 'system_admin_menu_block_page',
      'file' => 'system.admin.inc',
      'file path' => drupal_get_path('module', 'system'),
    ),
    'admin/settings/bbcom/misc' => array(
      'title' => 'Miscellaneous',
      'description' => 'Settings for BiblioBird.com miscellaneous module.',
      'access arguments' => array('administer site configuration'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('bbcom_misc_admin_settings'),
      'file' => 'bbcom_misc.admin.inc',
    )
  );
}

/**
 * Implementation of hook_theme().
 */
function bbcom_misc_theme() {
  return array(
    'bbcom_misc_badges' => array(
      'arguments' => array('roles' => NULL),
    )
  );
}

/**
 * Implementation of hook_user().
 */
function bbcom_misc_user($op, &$edit, &$account, $category='account') {
  if ($op == 'view') {
    $roles = array();
    $titles = variable_get('bbcom_misc_role_titles', array());
    foreach ($account->roles as $rid => $role) {
      if (!empty($titles[$rid])) {
        $roles[] = array('rid' => $rid, 'role' => $role, 'title' => $titles[$rid]);
      }
    }

    if (!empty($roles)) {
      $account->content['badges'] = array(
        '#type' => 'user_profile_category',
        '#title' => t('Badges'),
        '#weight' => -1,
      );
      
      $account->content['badges']['badges'] = array(
        '#type' => 'user_profile_item',
        '#value' => theme('bbcom_misc_badges', $roles),
      );
    }
  }
}

/*
 * Implementation of hook_misc_mail_alter().
 */
function bbcom_misc_mail_alter(&$message) {
  // Our SMTP server requires that From is an e-mail address that we control
  // so we always put the 'From' into 'Reply-To' instead and make the 'From'
  // always be the default.
  $default_from = variable_get('site_mail', ini_get('sendmail_from'));
  $message['headers']['Reply-To'] = $message['headers']['From'];
  $message['headers']['From'] = $message['from'] = $default_from;
}

// NOTE: Drupal's format_date() doesn't correctly deal with daylight savings time, nor does it
// translate the date parts.  This should be put in the theme as well, to handle all dates, particularly
// the node submitted ones.
function bbcom_misc_format_date($date, $type='medium', $format='') {
  return date_format_date(date_make_date($date, NULL, DATE_UNIX), $type, $format);
}

/*
 * Implementation of hook_link_alter().
 */
function bbcom_misc_link_alter(&$links, $node, $comment=NULL) {
  if (is_null($comment)) {
    // I hate this particular link...
    // TODO: Seems to contradict docs, this should be $links['comment']['comment_forbidden'] ...
    unset($links['comment_forbidden']);
  }
}

/*
 * Theming
 */

function theme_bbcom_misc_badges($roles) {
  $imgs = array();
  $text = array();
  foreach($roles as $role) {
    $img = str_replace(' ', '-', $role['role']);
    $img = drupal_get_path('module', 'bbcom_misc') .'/badges/'. $img .'.jpg';

    if (file_exists($img)) {
      $imgs[] = theme('image', $img, $role['title'], $role['title'], array('class' => 'bbcom-badge'), TRUE);
    }
    else {
      $text[] = '<div class="bbcom-badge">'. check_plain($role['title']) .'</div>';
    }
  }
  return implode('', $imgs) . implode('', $text);
}

