<?php

include_once('bbcom_wiki.features.inc');

/*
 * Implementation of hook_filter().
 */
function bbcom_wiki_filter($op, $delta=0, $format=-1, $text='', $cache_id=0) {
  if ($op == 'list') {
    return array(
      0 => t('Convert [[title]] into wiki links'),
    );
  }

  // we only have one filter presently
  if ($delta != 0) {
    return $text;
  }

  switch ($op) {
    case 'description':
      return t('Converts [[title]] into wiki links.');

    case 'process':
      $text = preg_replace_callback(
        '/\\[\\[([^\\]]+)\\]\\]/',
        create_function('$matches', 'return l($matches[1], wikitools_wikilink_drupal_path($matches[1]));'),
        $text
      );
      return $text;

    default:
      return $text;
  }
}

/**
 * Implementation of hook_block().
 */
function bbcom_wiki_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0] = array(
        'info' => t('BiblioBird.com Wiki: Add Wiki Page'),
      );
      return $blocks;

    case 'view':
      if ($delta == 0 && user_access('create wiki content')) {
        $block['content'] = l(t('Create Wiki Page'), 'node/add/wiki',
          array('attributes' => array('id' => 'create-content-link')));
        return $block;
      }
      break; 
  }
}


