<?php
// $Id$

//include_once('lingwoorg_flashcards.features.inc');

/**
 * @file
 * Integrate Anki flashcards into Lingwo.org
 */

/**
 * Implementation of hook_rules_action_info()
 */
function lingwoorg_flashcards_rules_action_info() {
  return array(
    'lingwoorg_flashcards_action_add_to_wial_deck' => array(
      'label' => t('Create flashcard in user\'s WIAL deck'),
      'arguments' => array(
        'node' => array('type' => 'node', 'label' => t('Entry')),
        'user' => array('type' => 'user', 'label' => t('User')),
      ),
      'module' => 'lingwoorg_flashcard',
    ),
  );
}

function lingwoorg_flashcards_action_add_to_wial_deck($node, $user) {
  #
}

