<?php
// $Id$

include_once('lingwoorg_flashcards.features.inc');
include_once('lingwoorg_flashcards.anki.inc');

/**
 * @file
 * Integrate Anki flashcards into Lingwo.org
 */

/**
 * Implementation of hook_menu().
 */
function lingwoorg_flashcards_menu() {
  $items = array();
  $items['admin/settings/lingwo_dictionary/flashcards'] = array(
    'title' => 'Flashcards',
    'description' => 'Settings for Lingwo.org Flashcards module.',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lingwoorg_flashcards_admin_settings'),
    'file' => 'lingwoorg_flashcards.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['wial/%user'] = array(
    'title' => 'Words I Am Learning',
    'access callback' => 'lingwoorg_wial_page_access',
    'access arguments' => array(1),
    'page callback' => 'lingwoorg_flashcards_page_wial_view',
    'page arguments' => array(1),
    'file' => 'lingwoorg_flashcards.pages.inc',
    'type' => MENU_NORMAL_ITEM
  );
  $items['wial/%user/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['wial/%user/quiz'] = array(
    'title' => 'Quiz',
    'access callback' => 'lingwoorg_wial_page_access',
    'access arguments' => array(1),
    'page callback' => 'lingwoorg_flashcards_page_wial_quiz',
    'page arguments' => array(1),
    'file' => 'lingwoorg_flashcards.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implementation of hook_perm
 */

/**
 * Implementation of hook_theme()
 */
function lingwoorg_flashcards_theme() {
  return array(
    'lingwoorg_flashcards_flashcard_front' => array(
      'arguments' => array('node' => NULL),
      'file' => 'lingwoorg_flashcards.theme.inc',
      'template' => 'lingwoorg-flashcards-flashcard-front',
    ),
    'lingwoorg_flashcards_flashcard_back' => array(
      'arguments' => array('node' => NULL),
      'file' => 'lingwoorg_flashcards.theme.inc',
    ),
  );
}

/**
 * Implementation of hook_rules_action_info()
 */
function lingwoorg_flashcards_rules_action_info() {
  return array(
    'lingwoorg_flashcards_action_add_to_wial_deck' => array(
      'label' => t('Create flashcard in user\'s WIAL deck'),
      'arguments' => array(
        'node' => array('type' => 'node', 'label' => t('Entry')),
        'user' => array('type' => 'user', 'label' => t('User')),
      ),
      'module' => 'lingwoorg_flashcard',
    ),
    'lingwoorg_flashcards_action_remove_from_wial_deck' => array(
      'label' => t('Remove flashcard from user\'s WIAL deck'),
      'arguments' => array(
        'node' => array('type' => 'node', 'label' => t('Entry')),
        'user' => array('type' => 'user', 'label' => t('User')),
      ),
      'module' => 'lingwoorg_flashcard',
    ),
  );
}


/*
 * Actions
 */

function lingwoorg_flashcards_action_add_to_wial_deck($node, $user) {
  if ($node->type == 'entry' && lingwo_dictionary_entry_is_translation($node)) {
    try {
      lingwoorg_flashcards_anki_server_connect()
        ->openWialDeck($user->uid)
        ->addFactForNode($node);
    }
    catch (AnkiServerException $e) {
      watchdog('anki', $e->getMessage(), array(), WATCHDOG_ERROR);
      drupal_set_message(t('Unable to add flashcard to your "Words I am Learning" deck.'), 'error');
    }
  }
}

function lingwoorg_flashcards_action_remove_from_wial_deck($node, $user) {
  if ($node->type == 'entry' && lingwo_dictionary_entry_is_translation($node)) {
    try {
      $deck = lingwoorg_flashcards_anki_server_connect()
        ->openWialDeck($user->uid);
      $deck->deleteFact($deck->findFactForNode($node));
    }
    catch (AnkiServerException $e) {
      watchdog('anki', $e->getMessage(), array(), WATCHDOG_ERROR);
      drupal_set_message(t('Unable to remove flashcard from your "Words I am Learning" deck.'), 'error');
    }
  }
}

/*
 * API functions
 */

function lingwoorg_flashcards_anki_server_connect() {
  return new AnkiServer(lingwoorg_flashcards_anki_server_url());
}

/*
 * Settings
 */

function lingwoorg_flashcards_anki_server_url($value = NULL) {
  if (is_null($value)) {
    return variable_get('lingwoorg_flashcards_anki_server_url', 'localhost:5000');
  }
  variable_set('lingwoorg_flashcards_anki_server_url', $value);
}

