<?php
// $Id$

/**
 * @file
 * Customize login for our needs
 */

require_once(drupal_get_path('module', 'lingwoorg_login') .'/base32.php');

/**
 * Implementation of hook_menu().
 */
function lingwoorg_login_menu() {
  $items = array();
  $items['admin/user/reg_codes'] = array(
    'title' => 'Registration Codes',
    'description' => 'Create/list registration codes',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'lingwoorg_login_batches_list',
    'file' => 'lingwoorg_login.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );
  $items['admin/user/reg_codes/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/user/reg_codes/add'] = array(
    'title' => 'Create new batch',
    'description' => 'Create a new batch of registration codes',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lingwoorg_login_batches_add'),
    'file' => 'lingwoorg_login.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/user/reg_codes/%'] = array(
    'title' => 'Batch',
    'description' => 'See the registration codes in a batch',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'lingwoorg_login_batch_view',
    'page arguments' => array(3),
    'file' => 'lingwoorg_login.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implemantation of hook_menu_alter().
 */
function lingwoorg_login_menu_alter(&$items) {
  // Rename 'User Account' to user login
  $items['user']['title'] = t('User Login');
  // Move the 'Login' tab to the front
  $items['user/login']['weight'] = -10;
}

/**
 * Implementation of hook_strongarm()
 */
function lingwoorg_login_strongarm() {
  return array(
    // logintoboggan configuration
    'logintoboggan_login_with_email' => TRUE,
    'logintoboggan_confirm_email_at_registration' => TRUE,
    'logintoboggan_redirect_on_confirm' => '<front>',
    'logintoboggan_login_successful_message' => TRUE,
    'logintoboggan_minimum_password_length' => '7',
    'site_403' => 'toboggan/denied',

    // remember_me configuration
    'remember_me_checkbox' => 1,
    'remember_me_managed' => 0,
    'remember_me_phantom_session' => 0,

    // cheap hack to replace 'Remember me' with 'Remember me!'
    'locale_custom_strings_en' => array(
      'Remember me' => 'Remember me!',
      'Access Denied / User Login' => 'User Login',
    )
  );
}

/*
 * API functions
 */

function lingwoorg_login_make_code($batch_id, $seed, $code) {
  $base32 = new Base32();

  $batch_id = $base32->fromDec($batch_id, 2);

  return $seed[0] . $seed[1] . $batch_id[1] . $batch_id[0] .'-'.
         $code[2] . $code[3]                               .'-'.
         $seed[2] . $seed[3] . $code[0]     . $code[1];
}

function lingwoorg_login_parse_code($full_code) {
  $full_code = str_replace('-', '', $full_code);

  $base32 = new Base32();
  $batch_id = $base32->fromDec($full_code[3] . $full_code[2]);
  $seed = $full_code[0] . $full_code[1] . $full_code[6] . $full_code[7];
  $code = $full_code[8] . $full_code[9] . $full_code[4] . $full_code[5];

  return array($batch_id, $seed, $code);
}

