<?php
// $Id$

/**
 * @file
 * Gives each user a list of entries they are learning
 */

/*
 * Implementation of hook_flag_default_flags().
 */
function lingwo_wial_flag_default_flags() {
  $flags = array();
  $flags[] = array(
    'content_type' => 'node',
    'name' => 'wial',
    'title' => 'Words I Am Learning',
    'global' => FALSE,
    'types' => array('entry'),
    'flag_short' => 'Add to "Words I Am Learning"',
    //'flag_long' => 'Add this post to your bookmarks',
    'flag_message' => '"[title] added to "Words I Am Learning"',
    'unflag_short' => 'Remove from "Words I Am Learning"',
    //'unflag_long' => 'Remove this post from your bookmarks',
    'unflag_message' => '"[title] removed from "Words I Am Learning"',
    'show_on_page' => TRUE,
    'show_on_teaser' => TRUE,
    'show_on_form' => FALSE,
  );
  return $flags;
}

