<?php
// $Id$

include_once('lingwoorg_wial.features.inc');

/**
 * @file
 * Gives each user a list of entries they are learning
 */

/*
 * Implementation of hook_flag_default_flags().
 */
function lingwoorg_wial_flag_default_flags() {
  $flags = array();
  $flags[] = array(
    'content_type' => 'node',
    'name' => 'wial',
    'title' => 'Words I Am Learning',
    'global' => FALSE,
    'types' => array('entry'),
    'flag_short' => 'Add to "Words I Am Learning"',
    //'flag_long' => 'Add this post to your bookmarks',
    'flag_message' => '"[title]" added to "Words I Am Learning"',
    'unflag_short' => 'Remove from "Words I Am Learning"',
    //'unflag_long' => 'Remove this post from your bookmarks',
    'unflag_message' => '"[title]" removed from "Words I Am Learning"',
    'show_on_page' => TRUE,
    'show_on_teaser' => TRUE,
    'show_on_form' => FALSE,
    // enabled by default
    'status' => TRUE,
  );
  return $flags;
}

/*
 * Implementation of hook_link_alter().
 */
function lingwoorg_wial_link_alter(&$links, $node) {
  // Only translations can be added!
  if (!lingwo_dictionary_entry_is_translation($node)) {
    unset($links['flag-wial']);
  }
}

/*
 * Implementation of hook_perm().
 */
function lingwoorg_wial_perm() {
  return array(
    // TODO: we need to make is so users without 'access wial' don't see any signs of!
    'access wial',
    'access other wials'
  );
}

function lingwoorg_wial_page_access($account) {
  global $user;

  // root user
  if ($user->uid == 1) {
    return TRUE;
  }

  if (is_numeric($account)) {
    $account = (object)array('uid' => $account);
  }

  return (user_access('access wial') && $user->uid == $account->uid) ||
    user_access('access other wials');
}

