<?php

define('BBCOM_METRICS_JAVASCRIPT', 0);
define('BBCOM_METRICS_BACKEND', 1);

// some functions specific to mix panel
require_once('includes/mixpanel.inc');

/**
 * Implementation of hook_menu().
 */
function bbcom_metrics_menu() {
  $items = array();
  $items['admin/settings/bbcom/metrics'] = array(
    'title' => 'Metrics',
    'description' => 'Settings for BiblioBird.com Metrics module.',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bbcom_metrics_admin_settings'),
    'file' => 'bbcom_metrics.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_block().
 */
function bbcom_metrics_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    return array(
      'mixpanel_badge' => array(
        'info' => t('Bibliobird Metrics: Mixpanel badge'),
        'cache' => BLOCK_CACHE_GLOBAL,
        'region' => 'footer',
        'status' => 1,
      ),
    );
  }
  elseif ($op == 'view' && $delta == 'mixpanel_badge') {
    return array(
      'subject' => NULL,
      'content' => '<a href="http://mixpanel.com/f/partner"><img src="http://mixpanel.com/site_media/images/partner/badge_blue.png" alt="Real Time Web Analytics" /></a>',
    );
  }
}

/**
 * Tracks an event with the given properties.
 */
function bbcom_metrics_track($event, $properties = array(), $type = BBCOM_METRICS_JAVASCRIPT) {
  global $user;

  switch ($type) {
    case BBCOM_METRICS_JAVASCRIPT:
      $args = array($event);
      if (!empty($properties)) {
        $args[] = $properties;
      }
      _bbcom_metrics_mp_javascript('track', $args);
      break;

    case BBCOM_METRICS_BACKEND:
      // add a bunch of properties that would usually come from JavaScript
      $properties = array_merge(bbcom_metrics_get_user_properties(), $properties);
      $properties['ip'] = ip_address();
      if (!empty($user->uid)) {
        $properties['distinct_id'] = (string)$user->uid;
        $properties['mp_name_tag'] = $user->name;
      }

      // so that defered events still happen when they should
      $properties['time'] = time();

      if (variable_get('bbcom_metrics_defer_backend', TRUE) && module_exists('job_queue')) {
        job_queue_add('_bbcom_metrics_mp_backend', t('Send %event event to mixpanel', array('%event' => $event)), array($event, $properties));
      }
      else {
        _bbcom_metrics_mp_backend($event, $properties);
      }
      break;
  }
}

/**
 * Sets some 'super properties' which get applied to all events for this user.
 */
function bbcom_metrics_set_user_properties($properties, $once = FALSE) {
  static $user_properties = array();

  if (!is_null($properties)) {
    // store our cached values
    foreach ($properties as $key => $value) {
      if (!$once || !isset($user_properties[$key])) {
        $user_properties[$key] = $value;
      }
    }

    // Add the JavaScript call
    _bbcom_metrics_mp_javascript($once ? 'register_once' : 'register', array($properties));
  }

  return $user_properties;
}

function bbcom_metrics_get_user_properties() {
  return bbcom_metrics_set_user_properties(NULL);
}

function _bbcom_metrics_setup_user($account) {
  bbcom_metrics_set_user_properties(array(
    'cohort_week'  => date('Y', $account->created) . 'W' . date('W', $account->created),
    'cohort_month' => date('Y', $account->created) . '-' . date('m', $account->created),
    'user_language' => $account->language,
  ), TRUE);
}

/**
 * Implementation of hook_init().
 */
function bbcom_metrics_init() {
  global $user;

  // setup mixpanel
  _bbcom_metrics_mp_init();

  if (!empty($user->uid)) {
    _bbcom_metrics_setup_user($user);
  }

  // do some page specific events!
  switch ($_GET['q']) {
    case 'node/4509':
    case 'node/4510':
    case 'about':
      bbcom_metrics_track('View landing page');
      break;

    case 'user/register':
      bbcom_metrics_track('View registration page');
      break;
  }

  if (preg_match('/wial\/\d\/edit/', $_GET['q'])) {
    bbcom_metrics_track('View WIAL edit page');
  }
  elseif (preg_match('/wial\/\d\/review/', $_GET['q'])) {
    bbcom_metrics_track('View WIAL review page');
  }
}

/**
 * Implementation of hook_lingwo_korpus_lookup().
 */
function bbcom_metrics_lingwo_korpus_lookup($user, $entry) {
  bbcom_metrics_track('Lookup word in reader', array(
    'entry' => $entry->getLingwoId(),
    'source_language' => $entry->sourceLanguage,
    'target_language' => $entry->targetLanguage,
  ), BBCOM_METRICS_BACKEND);
}

/**
 * Implementation of hook_nodeapi().
 */
function bbcom_metrics_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  if ($op == 'view' && $page && $node->type == lingwo_korpus_text_content_type()) {
    bbcom_metrics_track('View content', array('nid' => $node->nid));
  }
}

/**
 * Implementation of hook_user().
 */
function bbcom_metrics_user($op, &$edit, &$account, $category = NULL) {
  if ($op == 'register') {
    bbcom_metrics_track('Register', array(), BBCOM_METRICS_BACKEND);
  }
  elseif ($op == 'login') {
    // because we haven't fully logged in yet and $user is not set, we have
    // to manually set the user properties here
    _bbcom_metrics_setup_user($account);

    bbcom_metrics_track('Login', array(), BBCOM_METRICS_BACKEND);
  }
  elseif ($op == 'logout') {
    // the user logged out
    bbcom_metrics_track('Logout', array(), BBCOM_METRICS_BACKEND);

    // clear the old mixpanel properties
    setcookie('mp_super_properties', '', time() - (86400 * 2));
  }
}

