<?php
// $Id$

include_once('bbcom_wial.features.inc');

/**
 * @file
 * Gives each user a list of entries they are learning
 */

/*
 * Implementation of hook_menu().
 */
function bbcom_wial_menu() {
  $items = array();
  $items['wial'] = array(
    'title' => 'Words I Am Learning',
    'description' => 'Redirect to a user\'s WIAL page',
    'access arguments' => array('access wial'),
    'page callback' => 'bbcom_wial_redirect_page',
    'type' => MENU_CALLBACK
  );
  return $items;
}

/*
 * Implementation of hook_perm().
 */
function bbcom_wial_perm() {
  return array(
    // TODO: we need to make is so users without 'access wial' don't see any signs of!
    'access wial',
    'access other wials'
  );
}

/**
 * Implementation of hook_user().
 */
function bbcom_wial_user($op, &$edit, &$account, $category = NULL) {
  if ($op == 'form' && $category == 'account') {
    $form['bbcom_wial'] = array(
      '#type' => 'fieldset',
      '#title' => t('Words I Am Learning'),
      '#tree' => TRUE,
    );
    $form['bbcom_wial']['auto_add'] = array(
      '#type' => 'checkbox',
      '#title' => t('Automatically add the words I click on, when I\'m reading content.'),
      '#default_value' => isset($account->bbcom_wial['auto_add']) ? $account->bbcom_wial['auto_add'] : TRUE,
    );
    return $form;
  }
}

/**
 * Implementation of hook_form_alter().
 */
function bbcom_wial_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#plugin']) && is_a($form['#plugin'], 'views_bulk_operations_plugin_style') && $form['#plugin']->view->name == 'wial_list') {
    // pull the objects list to the top (so the operation buttons go below it)
    $form['objects']['#weight'] = -99;
  }
}

function bbcom_wial_page_access($account) {
  global $user;

  // root user
  if ($user->uid == 1) {
    return TRUE;
  }

  if (is_numeric($account)) {
    $account = (object)array('uid' => $account);
  }

  return (user_access('access wial') && $user->uid == $account->uid) ||
    user_access('access other wials');
}

function bbcom_wial_redirect_page() {
  global $user;
  $uid = $user->uid;

  $parts = explode('/', $_GET['q']);
  array_shift($parts);

  if (count($parts) == 0) {
    $parts = array('edit');
  }
  elseif (count($parts) == 1 && intval($parts[0]) > 0) {
    $uid = $parts[0];
    $parts = array('edit');
  }

  $url = 'wial/' . $uid;
  if (count($parts) > 0) {
    $url .= '/' . implode('/', $parts);
  }

  return drupal_goto($url);
}

