<?php
// $Id: uc_product_dependencies.install,v 1.1.2.1 2010/04/08 22:09:44 joelstein Exp $

/**
 * Implementation of hook_uninstall().
 */
function uc_product_dependencies_uninstall() {
  foreach (uc_product_types() as $type) {
    variable_del("uc_product_dependencies_{$type}_nodereference");
  }
  variable_del('uc_product_dependencies_multiple');
  variable_del('uc_product_dependencies_location');
  variable_del('uc_product_dependencies_order_status');
}
