<?php

/**
 * Implementation of hook_uuid_features_default_content().
 */
function bbcom_marketing_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
    'type' => 'page',
    'language' => 'en',
    'uid' => '1',
    'status' => '1',
    'created' => '1326542747',
    'changed' => '1326551441',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '7445',
    'translate' => '0',
    'revision_uid' => '1',
    'title' => 'Voice chat',
    'body' => 'Bibliobird would like to offer you an interesting opportunity to practice a foreign language: conversation over TeamSpeak.
      
      TeamSpeak allows more than 2 people to have a voice chat over the internet.  You don\'t need to know the usernames of the other users or call them specifically.  You simply have to be connected to the Bibliobird server at the same time.
      
      <h2>How to install TeamSpeak?</h2>
      
      Go to the <a href="http://teamspeak.com/?page=downloads">Dowload page</a>, where you can download the required client program - choose the appropriate version for your operating system and architecture (32- or 64-bit). 
      
      The installation is very simple.  The only important part is the configuration, which I think anyone will be able to complete.  "HotKey" is the key which you have to hold when you are speaking.  If you have a headset, you can use "Voice detection," which will detect when you are speaking without having to press a key.
      
      <h2>How to connect to the Bibliobird server?</h2>
      
      There are two ways:
      
      <ol>
      <li>After installing TeamSpeak, go to Connections -&gt; Connect and enter "t6.svoice.pl:8203" as the "Server Address" and click "Connect."</li>
      
      <li>You can take advantage of the sidebar on Bibliobird which will tell you if some one is already connected to our server.  Simply click on the name of the server - "Bibliobird by svoice.pl" and TeamSpeak will start and connect the server.</li>
      </ol>
      
      That is it!  I\'d like to note that at the moment the server has very little space: only 5 slots!  That means that only 5 people can be connected at the same time.  This is because we don\'t know if the idea will work or how many people will be interested.
      
      The TeamSpeak server was setup by a Bibliobird user and he is paying for it with his own money.  So, we will only buy more slots if the idea turns out to be popular.
      ',
    'teaser' => 'Bibliobird would like to offer you an interesting opportunity to practice a foreign language: conversation over TeamSpeak.
      
      TeamSpeak allows more than 2 people to have a voice chat over the internet.  You don\'t need to know the usernames of the other users or call them specifically.  You simply have to be connected to the Bibliobird server at the same time.
      
      <h2>How to install TeamSpeak?</h2>
      ',
    'log' => '',
    'revision_timestamp' => '1326551441',
    'format' => '1',
    'name' => 'David Snopek',
    'picture' => '',
    'data' => 'a:7:{s:13:"form_build_id";s:37:"form-b36e64565f8a5c1b38d61f7c2f478643";s:11:"remember_me";b:1;s:16:"bbcom_news_optin";i:1;s:10:"bbcom_wial";a:1:{s:8:"auto_add";i:1;}s:17:"messaging_default";s:4:"mail";s:27:"notifications_send_interval";s:1:"0";s:18:"notifications_auto";i:1;}',
    'path' => 'vchat',
    'comment_type' => '',
    'old_status' => '1',
    'last_comment_timestamp' => '1326551244',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'uuid' => '18190136-3ea8-11e1-9a92-d6b38ab061c1',
    'revision_uuid' => 'e0cb04b8-3ebb-11e1-9a92-d6b38ab061c1',
    'pathauto_perform_alias' => FALSE,
    'date' => '2012-01-14 07:05:47 -0500',
  );
  $nodes[] = array(
    'type' => 'page',
    'language' => 'pl',
    'uid' => '1',
    'status' => '1',
    'created' => '1326495033',
    'changed' => '1326551441',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '7445',
    'translate' => '0',
    'revision_uid' => '1',
    'title' => 'Czat głosowy',
    'body' => 'Bibliobird chciałby Wam zaoferować pewną ciekawą możliwość szlifowania języka obcego. Jest nią możliwość konwersacji za pomocą oprogramowania TeamSpeak.
      
      Jest to program umożliwiający głosową rozmowę ze sobą więcej niż 2 osobom, przy czym w ogóle nie musimy znać nazwy użytkownika naszego rozmówcy. Wystarczy tylko, że będziecie w tym samym czasie przebywać na serwerze Bibliobird\'a.
      
      <h2>Na czym to polega od strony technicznej?</h2>
      
      Wchodzicie na <a href="http://teamspeak.com/?page=downloads">stronę internetową</a> skąd możecie pobrać potrzebne oprogramowanie klienckie - wybierajcie zawsze wersję Client odpowiednią do Waszej architektury tj. 32 bity lub 64 bity.
      
      Instalacja jest bardzo prosta, a jedyną chwilą, kiedy jesteście potrzebni jest wstępna konfiguracja. Sądzę, że każdy będzie w stanie jej dokonać. HotKey to klawisz, który będziecie musieli trzymać w chwili mówienia - osoby, które posiadają słuchawki mogą pozostawić Voice detecion, wtedy wystarczy, że będą coś mówić i głos będzie przesyłany do innych użytkowników serwera.
      
      <h2>Jak dostać się na serwer Bibliobirda?</h2>
      
      Można to zrobić na dwa sposoby:
      
      <ol>
      <li>Po instalacji TeamSpeaka wejść w zakłądkę Connections -&gt; Connect i jako server adress wpisać t6.svoice.pl:8203 po czym kliknąć Connect. Już jesteśmy na serwerze.</li>
      <li>Można skorzystać z sidebara umieszczonego na stronie głównej, który pozwoli sprawdzić czy ktoś aktualnie przebywa na naszym serwerze - wystarczy kliknąć na nazwę naszego serwera czyli Bibliobird by svoice.pl, aby Windows zainicjował otwierania aplikacji TeamSpeak i łączenie się z serwerem.</li>
      </ol>
      
      To by było na tyle. Na koniec chciałbym powiedzieć, że póki, co serwer jest bardzo ubogi w miejsce - posiada tylko 5 slotów, co oznacza, że tylko 5 osób jednocześnie może z niego korzystać - wynika to z tego, iż nie wiemy na ile pomysł okaże się słuszny i jakie wzbudzi zainteresowanie. Serwer ten został utworzony przez jednego z użytkowników Bibliobirda i musi go on opłacać, dlatego dopiero jeśli pomysł okaże się dobrym ruchem, udostępnimy więcej miejsca.',
    'teaser' => 'Bibliobird chciałby Wam zaoferować pewną ciekawą możliwość szlifowania języka obcego. Jest nią możliwość konwersacji za pomocą oprogramowania TeamSpeak.
      
      Jest to program umożliwiający głosową rozmowę ze sobą więcej niż 2 osobom, przy czym w ogóle nie musimy znać nazwy użytkownika naszego rozmówcy. Wystarczy tylko, że będziecie w tym samym czasie przebywać na serwerze Bibliobird\'a.
      
      <h2>Na czym to polega od strony technicznej?</h2>
      ',
    'log' => '',
    'revision_timestamp' => '1326551441',
    'format' => '1',
    'name' => 'David Snopek',
    'picture' => '',
    'data' => 'a:7:{s:13:"form_build_id";s:37:"form-b36e64565f8a5c1b38d61f7c2f478643";s:11:"remember_me";b:1;s:16:"bbcom_news_optin";i:1;s:10:"bbcom_wial";a:1:{s:8:"auto_add";i:1;}s:17:"messaging_default";s:4:"mail";s:27:"notifications_send_interval";s:1:"0";s:18:"notifications_auto";i:1;}',
    'path' => 'vchat',
    'comment_type' => '',
    'old_status' => '1',
    'last_comment_timestamp' => '1326551244',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'uuid' => '5076b966-3e39-11e1-a725-c6361d6870d3',
    'revision_uuid' => 'e0cfdd94-3ebb-11e1-9a92-d6b38ab061c1',
    'pathauto_perform_alias' => FALSE,
    'date' => '2012-01-13 17:50:33 -0500',
  );
  return $nodes;
}
