<?php // $Id: block_titlelink.install,v 1.1 2009/08/28 18:24:05 ngmaloney Exp $

/**
 * @file Installation file for block_titlelink module
**/

/**
 * Implementation of hook_uninstall().
 * Uses the variables table to store title links. 
 * This function deletes them.
 */
function block_titlelink_uninstall() {
  db_query("DELETE FROM {variable} WHERE name LIKE 'block_titlelink_%'");
  cache_clear_all('variables', 'cache');
}